---
# Source: longhorn/templates/daemonset-sa.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-manager
  namespace: storage
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
---
# Source: longhorn/templates/deployment-driver.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-driver-deployer
  namespace: storage
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
---
# Source: longhorn/templates/deployment-ui.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-ui
  namespace: storage
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
---
# Source: longhorn/templates/postupgrade-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-post-upgrade
  namespace: storage
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
---
# Source: longhorn/templates/uninstall-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-uninstall
  namespace: storage
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
---
