apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-elastic
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: '/mnt/nfs/elastic'
