apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBo40/jCpgqOUknEEi/o7mp/uHCJlGIcJz0NQs56MbEQCzsRucz+dzOj61TJkh+8g6HwMrzNPnM+RIBJpEtNBKAAvyd/BryrKsdw4ddMp8wzFu3IOaUkLAn5l08Ob2pDiXG3dPt9HzjvU4cNuUzaimhSMYBDRe6DhBV1q8iPGALtnlhc4+FHeIwx4h8FUaF3V4RWVrjljsTr9MBgb/kbhpmP9emLf16ANMVTc8gp6X+0S7UvVKl/RGHmJukesnDBHJ6qOMRiTOqEKBJqXlN1j8GBN9y8uJ3h2wOfnRgkGs6mx60nq2FxLM8IlCrd43KwOyWRlXmITkeQW2k2YZNpEjlWYTgLO6ktfWc4PvGZYhl4a5oBl8jVQrW9Ro9dcDzIhkvyZO6NuOK0QftAzO3oo+SIaqAg1V5Kp4kFDTL7H/FhxUDOiI5S40EfrOtFO8zt+zsiz6WYP/FSJcJsWlNak2IRDEwE1AnRJAIGu5NvurKM2c9+4daRl3j6mnJPLpLBRoWgYPkRUVWly/NoCZPJsPLf5e65YVxzlOL8Km9l2cEMecGeDpZByd7OXSW5ngoAD7KLBZP4w0XEfu1EzA9AZJLqudlQJDHT1s/Fu3geVAoSUf3Wed1XV26Zm6XtlYCms8iip/9x6rb8o5/szQ3ke8HIeqzYZTdi6kQm89gOmm9mddPrjlBhm/RDGT4CUoYUwvyvubqwT5x63R82HOOeW31Tfex5Hgyki/3zkxt/Jpbpy4whIp+HDnskwIEHMS9ZgvyUn6TVNiPN6Lx+hDDKo6bacOFJz9seDYhxs3+zqPiKR79/maVW8hs5yAvFzQecrFm0EJiAWwdfK5J+06jGJLtLb+ggwFrMYi4aGdP0o6P38TYnfs5mNEKsucIIkmarJZ0uLveKHwQtTkAAIFXVd4BYfwHnxYg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

