apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBvYoYDeg8dykLSreAhFcy0yG6+JU/KUwSJKjVF+JCMmTYWSqmzcewo0rSG+XqBNwAA1nqG6ArtUvf6kXqQno+2VgjEjEgIpD0yJK9CJa/olpEf4G7AWlfU2O3N4B8Y3BcnI13cz9Jir2sEYOcJlj2GqRrdBfq+tDKHmb0euemmlTR39WP3pbIiXU7HEpqVN6LwI0blfe7IUCKixk97UUk58GStTcZzQajYwb8Hwt7c0DENwpns4oe/clssMM/nZbYiz/DvSJJNVItLT4qyhMoDOdt+/Oh/BmyBlHFUTh1ucwskIW+mrNUDxGINpzYlYEQfT2a0UrEkAWaQ3oBYbkKd9J3CRd+Zo+XIz+skh0kGZJG89ULCx+n5+r/1QuvhjgumTKLRaHa3dglO9dEl0l5tU7fevnJT0b3kv5U8PzlzR54m5CspJuWGFXIJc7ghsnb+AgL7A72e2SxcrmQ6wBKF8LxcneKCuTTv5oqJuwi2qmg+W9Pf9y/+H40NGbml+h6xPk35CI2VGZ0LAgZzCKy0JTWFnXPaYdP4Iu7g5QKtW/t0HGDJKWAGjB4FZTbw1beKllDhc9tBCP2FgOMqm/rrj2lsVUg7suVZsWir4Y9oobte9JdAKiXgoMrJFr3Pm4t6yuM21PIlY/xS/Ajnc1hsTeXhV5fU+ju2S4pwQivZi+SMJur/SfFUFMwtZ1YD1N/zv3v8mlU3xnX7RqH7P9Fz1BhN3EfdpKSkDvtAjPTyR43qImGfjz1S1eUSJXHX1muyxFmr07gt1gU7eiXqg6o+JqWJkdHqi8UbJlYNZVEn9C0ajJwlh4qOc0GDabJp0Fie1WmZGinIagyxjeyp6G1puByCZ0kRPsMHbEI1lIkwmAnRyoO7W69NuELbLFCBJSTSOT7tRuNLdSwPwk1wtAI/GpwW9ZQr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

