apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCb1e62mNg+RTeJHqNd6obIIHH3ym6Bjl+ksyoSrgXRGhSLLVyhZkJDeTnyXUKTzOkw9ZW5NfhwuC+AgJeP8iZLO52AtKu49XGQvPgbi+9leMyCh4iEeRhaIDoeDLouo0cdOOLWU7uU5qwAgl9Ssw41AzZRATRUCVYHM0MllUzZy6tIuu2Nac2z0uHYeQ9n0kfaktJlZ5IiWj41+lvnvSf+BnfiiSQN3RZt6sSC7RIxJlfAybTcn1j+aUWmLWZnXzB/QUF03RbcK4mCDV8HUJOxfeqEfwq3eioRphLsWMuV7CPcvtaXpfuJtcAbyG+EPVw64Nla0ujYHBneP4gqpk1NLQxvreEVDhqcB3EJB3QRO6K+zXzvkwiSAg1rQT/X0KQZHOs8yxwoO5PMRO8SBXvrN2ieZOb/b+PAjPazgKr7bxJvySMLjtrEB82CGvEEPAyXQ9jK7Kf6KwvppYWeu9wFSEP3RAz0vVKeqHMdNHtTipTQTmTsV6oHEksm5Brd48HMVcuWOQffwWIxiGiTnajBKs1ODBYTkgHgmPmv40J0FvkZxwZ5OkXAJwlVLHipT46zDPcU5uQgMWMZ94aJNdegBzx1goZ2D2tpZgEMR4UxrHzUbhtgy3EhuyCPxB6z6F1wu8cUdIi5smhh+77RZpTEqhWy2RJZ9pP0Bkx9WgkOnSxaXmdOcSPBP2mprRdIrqxx3pgzfEDNa/D0y7+I8RE9GNEYuSmRJF6cVGoEc1y9ICn7D/KqFGBj1wb7JF8Bm2rxuahmCb9q4U7a/yuwGdHLjIXCaOVU/l5cGUJFGv44DqXBSPfpPeJS5+vXa5lnOIhcIaIwq3i3MK2tzeKJEYXoryk7DybpCa4BIuaeMynWnqVk9Wan7SBOXVNiR6gSi2P8vA9mtwwScJ6Ei/XLnx2gfQ9y/of5
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

