apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCdGhgqMIP0kLAoYArP9ToCozdIT2vTy3xfHQ1QOBNpXxS4bbOEBegcEl1JW1dqSvgwjIG4KpbEL1ni0YPaOEbV+pbRHTHQYfkhaMZRq4/6Yhjm/AMWzqEjMTfaOJUhqHQ6RpbperNUNY27cN5IyP/KpzoPwAcsRrzhk/Rm/wB2E+ZNeN1L/coqIRr5q3M4VRq1rzg/tVKPMGzxAaY0aTs0O0fsiiPwnhULzo1kmeOfpvG8eg1UKpVuE4S+JvHYLs6KY+74iPZg8Ealdfl1uz6ODHPuFPcv0W87hZNbN0BgkYOffeyPWWwLavYEcRekZ1zJtYSLcycVf8V++cCdNJsEjWZluCLQIPq8GXjRkZy39wGOAGf8QdJ3IO1T5Dx6CFT7M3Q5PD//FE2srkwRBp+Fak+pVFpyRvWUsc+bwxquVEMfEM5uL3dRfrA/fDMBp16z0xyR/nzIUVVqEysrwd6nBFAQYYbaxyNkkwBbQF6hRFjEORWaH2NCnd2YDpeqoY/7bb9+3bhw+6B5Ilf38SdYzRmGh5UXODPbTe0IUsMRrvppntiRdEZWWMGnMWaHBtNa6LQ64kimdmnu6RNINQynpCSeTcrzYe5XT4cdu4Hnylpqwy8jfo1CpGMxm1bjGVRc3h7yqhkZS1TqeoA6+32yn+Iya1sIMXUZ0wHm73UJy+zvBMXakJVrwss+Xb6KFX32A3Wve7qdX02cSkf3is53CrR91YK5NzVLUJSOU0vJ54ThNZBsvw9HJjSJmT78ciemQriFfL+hfG3oAlN4uBn/KsMe1SncS8oBEque4dXrJ6TM2H6fJ+1UVL5yGe+QlqF9dr2VZAN2HbkpOVLsjBDCdmn0buIiuTO8lwwug2H+s130IzijY0Ffo6uDINEOsCzs9YodM7bzJ5TUiGwQ51itjzUQR6QF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

