apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAMpzYGJkdcM5nfnzDTgVvdeb84LYDkgBjg0dgjZBP1WXKB1z8GB8U7W5tc3RzmrnxnHeaOFK30e7CH7s5YJD7rCDNBvFhXlO0cj6DUkzAw5IN/ogUcOCtIP4SIMSVC9X/fx8P29XuALYJsalHvWFWVL2tlJnc+ZCNd2o9f5b4pfNQVO7XJ+iKs9W5ZnwXHW7fGQq1/WQVl+YPGXlWFZ8s57FarknNNHIagAH90zDGm95o7EBh3sdSwbg+GMUBsVxSvQzLAw+Bslj5xVXrS8E2GHcFbD4wl3vDEKsrykzkV84VcoF0N9rPn3FDky0V7dH3hksYutdxcDpnqQUn5Osyf1GBRk0xHMui/k2Z+zehckocoXQVK3vUIgKRqYdgMSGf4kAtx5Z9V1ZEA2iWEUGLvD3q9DGGuqSSF3KIPkbqeb93IrWMLnS4PQXLpexCHvE0DKuzDKhETV5KdptSSvPBXYQiarFMQMupJmhO3KOj8H4rtAaaN2nI3MYgpITGq2rjRawd3Sbsb2hr2Rmw8Lf3a3y6y/Z2LArYBN68GGeaGm39ND7yVIYhNrpEuYCixuWvAxYIIIDUrx2N0gTkL9GzGmN0n7aoep3AnHqWBV8sRqt/PDhgw7BerIV1B0jR/n4sOAnZ3KsRtNNlL4r7AGj8E/c67Ab1UhzpMH5XNw3dBgsuGhoRTzU1xsr6AfSGxpAW5X4u65ZvonHf5unQ971Qo7TpH3fYZX6PC2bd8teO4Uv3RZkLV0gYhv+QusaPikvnI+G0WwJDnUkahdOk6xvtTthQ3FhzWlCX1ufnl2eIvRsvmwjcu0WW1ks+EcwILjgguZpR40g/mnFbBmhazxEEDog0AaXlNnNRXYXxQGlFJTUSvK7K8Cy4XrLp3FMaUH8RK91dLzkQMlqhDXn82QzvT698x6YNs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

