apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBT9JCVVO+jkQLzlv0wJ6d5rucq+QEaOUr89MetuOKq1N1teVkoJU6CLbkbQHZ1y5utKBcvmNZOEAf3Jj8bP8yjpxEHE9kuoOeODmrBsvROdyBCnXnFIv9eF2KqoKwIJC0XI9yyvjkKKQmow5NkU4TSq2FcITgt5DstHf+Q7rPITSJavWeP6LCBG8i2Ov6aHqy2GdAiar1N+309+EVScXSPW+XWsAQNpACaQci8TRi3yQsMT1FPK/BxWY51zuF3oi2OMfZRrSjptWEuLCortfbb3PHXXlWyYJ5FKudIVNdPeK7uelyiaf7URcUfGOWUyEjbt2eulWYOy4bUIkTwNq8XyFPmdetpVsTICq1OVeEj95YXYNAUGJ3Pu9KJexsFhedacaI95muLXZJwJzEs1tkT/aVbbzRqorSy7Tg9zbgo0iHi9wqljkXDRJ3kHz5hjNGMcJy1PSzh2LZ+CR9x+T+r/EyQBmLcHysQsNPJJR1SzmL1SMDUDHhoBNVkRMnLQpTzli6VvZldsRWmGCxD4CGg7vuHu3wKGWhN4VLief6shCD56i8Bg2jKrMOJ8Vwx1tbJ+EuXQUQg6RXDKaXka8y/5nFITav3Wj7SaP4VO+WmajvomHjpFMK3WhB4W5Ghvxl/7N4bvLNLPVVzjOcbhAWp7WuKrB4IfryOwuYDmOQOLWdvV4P+KbBJCynWBKfcwwHVpox33AppZMfD1YnsT7wvxLokFoDZEj+iHGCpp7+d9X1Ghbq5JKYX2tgD4TqRBI317rXqGR3NEkdP+D45ogHeQ/rVgdTaKgqJ5jQoDm0lBM2+/h+8w3QXo26c2QtEK94y8oY5w8o+WtmNsJBxnoOXV6Z6i+un66JNncVPhPGJHjWhA003/zJcx6J6oTF44Z9p/XnsSfgON/yX9rEYp1kZUMfxVNh2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

