apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgDK6Za1+sDljEb5awGwfr17uUZ08VRV+yEefmu2Xk8ahsR4/0cEpGGLTQWfcbftNiDF78CHNlrl8UzY7jeBit0WlTjyQj5pHJTR9I71YsQ30JJNo7NwU4YW199DJjILGtK1SG/zDHx4ffxs+B7/A+s+D3elC7fnEC+LcKLesPTTZQhuEqOtGAxoapdgu/goyOWLj0PERIwwhhqzbPLwc2K5s0oo4bZCzP2gtrCbvUgKtR/1hi48ToY1ZxWUK8AOZxjpKOfUwMr9jB8w9Pv7P18Jm8jdPhhMsPI/xZivptoIHzRZhfEKasVu1BiIyX/ls0n/qdRSw0JlUvYd9vsWVuE9kMlIQdyfn/ZfUBVq3k6IN6yMTw1bvUWnB3A4+/X7GX7vhhwfgRueYxIAYbbNJ/nUpa174MiKnElUouHGq1Nuv+mnfTQ0vC7gD1XNMhzuKkkl644SVdpvy7KPX03XmATNsdcVMU7gosX2sBaNd2L1yrpoI2beBEhR82onowIE9CbyrpfGY6L0r7fazG9KJzPP0LuteJnsTRNhPzHlOBsajyZuFYzh5gLC1ZAyJNlSdGTUtMlq+76na+T8a4JIkJFqyO1Zgf1K0qNkU7Xitj7DMSV1YoWGWknKhcJj4StgWf0+YKcSx57PRUNniuR0U27i6eon3PIphM8ruGYMvuv1hR8ga18aAgQFW4TAtb0EE83JqQPt2pGgCFE3L0DQ6DGp+K9qBGgAcx0QueGckWtzsK/LiD9yJy5hZ9yv25Uv87B2xTd8rArWr8uheJQ16Cdyo45o7dGg3fZaFFckxTcCob7yjEuGuJiUn6aUMpB60FyOe7CRrdBh3Ql5Tuim3WEJ9nDm8WfLf3yECo9EU8RO7xsT7KjFTrinMqvEw6xZHOoqLgk5mhRxxB49kPdkZbTak3iWCWmL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

