apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCpKqBSrk/9hE8lhYQ1vHp8RYYErq5dBtHGlYxr7nEcOlPW5N+qPBY5HYjAq/pVJg1E1UHcC8xFPOhyjc36DineLkNRno2MEBz+5fgvamicvmEm5yXZ4uF3u1/aNiWTjbuy9QTMUC52k/iku4q6Of+eFgsPmEFzZFH1yTerFd14h8G1zRcDq0k0FLRtosnDvfE+CT6Ky6aXB7yf8u0NlJHfoHL+FKxtjKvnUiHvrBVlTFRTCiWi5bwSt5e5bdn6+4K0wjZFWNYdb4122N4OBCcF0KVBxULMCYna7rjlXskcOhTMViUeDZ5CwOhvmIYhtpSVZ6msum7cIVb1rYPEUSle607LElbkOSrDfjtY1iuY5JBGrXvIg69D6HKPGl5v8jNq2H2J5KL+5pgdbZPTvX/VHrNf6mECR5AnhTSwEbKuAj0QHSpD5MV5ceMO52LSIpyxM9Vuy1XSdIfcanQpTOEsX7E90pmtbFM1mrNd8te62gOFgjG+OgSrP+kREVpehLn3YWYBrwNp8ZdHcvMds44XXUJFyy7oM2tz4hGRPEBCIaU0CCk7w69Fdlm/1AjPxqgLGDsrYXYbOItO0J/VnUiz9efRBux/Q/twSDv1+cRT1xRE8jrYDmMEnJmAIVWus253OvA/ZqoGUAxO0qI04bOczwUVKZ7j1oPmG2fMF6qo/DjXazozEUxB1i+TL89lHx+b2VVvR9guH3SvJHFtNM3eFC8kHmYzlQmOn26IFvpUx7lqthEetcQqOyR103tWzLKL0jAdJjPEJyxxzZ5a6zpRpH56aKlS31gGq0uMT28NKBHw/EVLJx05dF//D1K6BWhUbyqoyV0CB+0Hz2zD87o2xHjARWit3ePsgrIEuorIgqqfDdQWeHhD26YlZ0XADRMPeEHGCzUzW4B7SUJMbhw5l4xqSBYP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

