apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBWM1crY/I3Q5/jWK/M+m1aW8TuJPmWoGqUHwd9DMOb9BGsbQccDhTCZcHbgW/l0kYhqJVxDq2wctdZjSJw5ZvWub8I+2i2YDIC+eYD8yFvhGBTy2YAFA+X8V5Um8Bw2bqJW+huuxpZmUpbblbTs7QT8FCgxkro/5TiTgoPjaWD74hz2kSMAYlGWmZ469R0LP1XagReiV1tqLYkCCCpUzX+cxjjlmzYdEczchx5mEI13onZnyg+yf+YU2gfn+HHvD1GRV6zxhZqUZ2AKnyBaatEogL/b9ZATdn//6ZcoHN3rYk+svlPkCYH2fKz2dPicz6oiAB/z2Hu9mfUSgv/CAQd73SeJ6h0RvGEqFK0NPlUoQ5VlpHuveDgKQ1C3OWvQ/H0LUzfo+fiHot+pXt5eLJhRPyZ4Xh+XmnxFY9srMORLLsZh+TJ+xnRYrMC11ndwMTj5QcT2bKKY0qH6Um7r5X1HOdYtY2T5S3tEv7kXqDhCOZkVluq3aZGicf5oJ2f4HxcA23XaPWNSN1qCDB0sDMH60fQBvfZwxquAz6PJZGNkIMWuyZaLJLKg4zt59+/iuy7hsP2CiMelIW/ik0NDMuOnrZ9M/E+RPk7Kcg//d/YG5sYuS8EAyUZYmqkQYIBxWhVgYXwBLoAS8jzd5uEU1fwa8cy+iRtUBb/UJhmpbkeqvDOoCIJUp5V6EQUyWoaymvT4XZ1BKtoGcVNwsOk2X9yerf0mJFIUkZsqxwIn9r9ExrGrtGV4wioODxg4Dp69PAWXxwXXTiX2EhLOKd7ial/MR7g4zsU76ogdpQ92gpCf4yA/48yUIXk3b64Idka1nIz9m3cooyESjCppTPcRV+dEOejauZvvbkLKeMIyzZT3c3vQ66M061SwBZ87E+5oa+uLxK4CkOOa/pwYk31pyvf4Xxp2DEq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

