apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBTbGBikxa/gz85MPKxk+0mRGCrRBW59Ai7hY6USNat85HarxHm0bGCuNvShwuGFDnhbYvULYs2w+clvITSE7Vc6vKX5zR/xmVcEhkDY4a2rHHYEn2hQYzc8ChcSUYoQp3eHast9lVESejoB0UWYiO8q4+YzuXtBUuxr5VdxutQX0q3c21XDyl0nw8ECnVXRExWGeUB62ix8OfqG4xDtxvFBTRmRmjk56kxvKK0U+IJT7K+W8NANOUU5qA7t9t479fbR6CYsy4fwqhfLEx55bocc7UIdfvP8kIHu4frH9YYJpwxck2IOa+y92UKaHBDl8mapIz3/wU4/lNKhG5dA+o8fKpGM9Ek4Cq7c73ZtIHKSy6OXfmSD7eBKI0AJA3exySDN9BtIBIcthJj/FCNDrcAf9oPKnYNgpznGtSsFgh06Tj3c9jHnXQEGAQ3aEKA6t1KWzrCsfq982KggjWAUsoA7VJffXnkjySzDdGeNPBIk59mT4bT1WyS00eW7RcC8bbJX8xYJJgtfn9JYJxIL8jDSW81OiHm9GgkCko7B2j9vd7TA5KLLj4oAh3ptQaO6QeDXYG298qUB880tAQTZVuE9GgE/OVVKOi21KJtFhRUVNeIC1mcC58m3IqVGefa2kLDR5UTKVfiixpMf3h7q6xQC/hmSlzjH+NdknR586p1gKN32h8hOkd8EpFA+oe0/eh5+dmwM5wbImokUnk9iCLQ0L+smVEbj/FKrupBBaQHKzR6nMOuy6nIzeSq9YTz5o2Q0bJ+9nN52J081T9veflzNW8ebgENvDTxHDWvI7mZAGq9QS+xOv+RuQFMvLEeuEOjEsVCTI1GYflZlBW4tBJCXqm3bKFkYRGIx7dE/3SlYKvpP6pN+9vGtsqahlzD75ZyU7b4vM5193MO8wTphHeJ7S6dh1DL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

