apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB3O8xcgRVuXWhtIAkWfJ4KP/NqP8USxqWBFFHZ5Cln062PAo/2TKxVpUfwVP0jbYzppnX2+q97YhBUq18O8VO7bR8u8T+1TTmf00ssXagrN3VGc/2SI+VAkjx/RJk4shN/lf3UImNJUUHUEWLGWeDDy/Ur7rdf6tb/5M2vVkCdxK+zGuWioWXvMgOcVv7MjLokTDDApGm/KmVhEE5kWgAvZMVhDtPzOO1z6gHkdEqaDgAzMeP1CgM1flcgwdTduFPRLaq2mrx3YiMN1aFLuDBpwfnVzdB7A85dQsRPjh8V4yQXCu7HW0PkCyOF+mKWxbtixHlyAZiPmc/Bz9/3I2bgk7BA/g7W1wmZm1zKgXbxIZMM+J3LNgHr0CFiSHzixvh2KCSuCHOOsw6FA03p06FD+JXr+i52FIQPsS+xI6N9YevWz82poT2YR5BalCOBN65OtHY9MHOqm56LzXDxH8z7xZQr6f5G3RLQdN8PUSsNJQ3wdWS/aGSW3V/DxOx47GbCRsS1/K+6W+7jlQAmwey0cvgKPYpzftz+IY9vi6oNz2HPX5x5voKQMGcWmjOn8vYNHgXJF0iczqtYzkNJUgbGkdb7DQLIdDAmbq3XE7EbWzLJCY6hNstcmdas7p8IfGI1ljabFoC7sMHye1A0TUt3+OvZlHsmM/vl/ghh5gh91magntBRDeDfH+47nZnpG69tH3/QCM9f0U3o8783gXRylBOu8+UaZ6vH/qxBxMbZwemANejZnDSe9S6b3gj1ZLOF2qf/qpg4FN6xq4jcAobCwTfJw+ERzE7JjvBO/FKPlsIf1kyvBJus1pOaiUtsjrARfhPM1vdSx15kzKXOSNKOHVL1JaL/R6GklfvLb02yGa3EvEEBstTYJtM4huW8IeTxb5nEDWJybv+O8sv+b+e5PnJl+DvC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

