apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgDng5JOhSQYm2Dgpv9TBqsNTnMkTR5MLSTLngh/dkNyC99E1Ww6IxpKuPktzADrNLfLBVowu29tY4YCS0xzMqtpPP6CZ5KFKV5GeN0xvQBlmWOFRPfwAiO5bVsMtIbeXs2AnE2USxhxjC6cazzN0qAtl5HwyVImDC8v4a/Gl/dsC5GVEOkozew/Fg8NRd8aCKF/QFYP1Xjz+A2CHHtiY4i0i5j7RsogOysYkqK8Q1XzV92dHETgOOCHghUS3/O1ABkCMw2rz5e6w28Z4Cl5C2V5ObdqG1IJMS8wa02TXhqBVnQyS2UNc6kscRoOFUX/ai+bvwh/9zEfI41WKZ4dwyD1Pfiq3MppC3m6vFhMCwme4KHVn2kslSS5kJpctbBmXajux5JHSAKJydeyBcK3dHoDvQaOXd+pSLcyvdx3b6dL2F63bEMa+30WcVaAP8vpyRi293TnDdJl/HjrwwCmjWB3govZLESf+vjpYXtQ3rZvahj96PIzriKTB3eFFN2OA87G2fq57Eypzj/wa6qMXC5Fib7ynlc+Vj8HjbxM72T6f+BoPtE6I7MHN2crJEMBU5udEgxoTEMIExYokoqtjKJYhZxn/2s+ehtsMUPWQ8CZfZ9QxqfwqifMgsMSgBXGhthRJOf7l/E+fBqkp/Ei6r6ffDlVTUUoa4lCOT4fRGIKkzJL4kiAxI/d+cW96sP0ASrYOoRDS6QaNeqERxSix+EtZ4JLrC2MU1SHtxaQsmWH1xuuZgoqJXR2lYD5l4NYKaTV5FrW4bfb6Dfi7uJZ6p9/38zjgSmwXdtg7PNSrwSYldNC1HovEfNCn1IDsemtHYH/fMvs3fU56NEkUK0kVS4p1LbiBWAOgIVYBdjpeiO7WR08AxeGH3oQec7MT8KdVBNI2ertUm9EwD1ZRvyuj7+fFe8NcPO8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

