apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCwLvrIPlEZG9Y3UY+g2E1Y3uKgG+EKqxmwEj9IpigvLZ7JbwvDNZWaGM/RgwUu7Rb4aZ6HTk+oJvaw4lGAxabZ5YOUVP9HqHeResZ1mVws/ugZQWV4xlq1X3pX+/vSbmuux8sL5UgLfCiYXCKoD0EkCgGtkMddJulkHYmnieEW5b8x0gCPld5lOkdaUkxI5IZs2IbpT903lLqIgp+K+eQ9BvDDOeoJK4uAb05b2tSbv8BpceOIlPnLQruz79DmUDpt/BtYmctBCDkn+JI62vQj7ijspBKTL/Glj3yuhFpF2ztdYvASj8RImiGidNj3neGtcxub+hu4IhgtXxRU7vpTnO0kbX6X/dNxsCWd05wQ/Eu4KDO/ht6GpgreqzB1SxOXaKYNTfvVAsDdTH/MHq4kt0ZvrMZKBFZSfhm5b/ULqGAF0lmVnVIZID9ISXxSdcgvcJbZWswAmRuhJM+5Ec3xBOL4XYtiRwY+qxe+HsYsWXqQQ6haEjtXuHuaXIEMz7GSxG3DXGwXEYVjRxTk4CNRub3x4KHSkRoxz6feNFdrnabRHrjCP+w+UtUC/yzd4ulfk/D/HmSNx8JOMUKQclmWgtYMIN0cVh3MSKe5bqhIb4uRRscetlkXtyphXUOmRRqNQtmMwjsK7aMP7QUluI+ODa9j92XF1hDK1iRpTK7veP+CV1mJY3gHy8ORDbsmNeGx5JcWrF7gr7OphEq175QfY2dL5XIAyLzUghbKJe0Q6HKnU0qnQ+/Kv441HwZRIe11obUQ+G6CCI82OwDYk21wN8DmRiGIUcaZcdYpU0UjLenswKUe9/csuAKAH3Cs+EbmccGBvmlpXdx8N/Dz1GDCXr9XKfApV477a8tmqSLkw2pwtAfvnAUNnGDOb94KxNVMzhW8S8wARbUxOOSUPklcQNLEXezo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

