apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCkhXvykpi+Muv8hTJb6gNkw6uWO/lbIJ9yV5oATB20G+48uN5h/V3WTBEB+hzx7TUN1IUAThYwM3u+2Pg+NziVSwYqIndGNnBkMPcDd2LMuA8tgzVSmQ1UPzWyMlFGZBsTbCMDGehwmeta8yjgpfRUgpjSan0znOwVqy/9Dfq6PHLi4QFpIgNHpbc3RJm5bt3nBvbKLKrR8vly0FRyWblNZPhKUxuLZGx2NsQ8UrL36XNtlzsDqWnZRGQgbcRLuOIL0wQErzShbEs23XKnvXt+mxuVO7wahwTXxlUyfS5hj0L+9IA0c48ry+oxg7x85/uUyl/ijuP/jjd8Bs3qCBUbfaxURL7RcACU/5i6RVx+exdujx6RqOikU4YTD5LGSqywx3AiQH9/WoNTC6bP9ZAQtg8+pE/RCpm3xboNwUziAxUZj0UkJHjyQQn8O4fQc/6eim5K+EKgrBaMvfT9od7QM5e8IFuNgSqg4xdU90vxsV8sm/sdGn9nTqg5uIFXOglEj38TucyNiFgnujjeQlNRlr6VOjRKzXjzxLQD0ECmv9AlOoAq2j4YY7YPG/jdCP41C6jQvpCcE9N0mB+QW2EM6Bd+NLNZ5hVfoHiXd1vQV0/iftQBRUFdeT6mSieOrptNPFt5OXQ76XpT2yh/ky/y7xo0ZP5TZd3ybZYiqHJeimS0MHFK2Hve7dHeKf2KZh4G0nWkMVXsQQK0dopzirrRPcX08nfAAwFIWmiNbJ/fMRTH0WCTG1cnZWpj7kCi0W1CTh6ncq8RBQ343g/lBhDDe6tQOfeClDysFmd8bzS39nQRXzSCTtZM/mJhAH8u4O+P8KCfOBU9kIrDD17AVPi0RdL+wjeJ/dB7GSrlJtDK6IB3tgLbJtp6cvIwgtYj0xKCvqXfajmqmYfVdUxYN/Xfyo+HRpp2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

