apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBbR/d06c/holLp5qj8DMWfEZRlKFywQXyfM1PBeghf//u+JxlsSYVhefUjrWlyZLdWoA+Zncrddnv2WQV0143fnRc17a98kzc8wye9SFhoxwKpciJT6dxuBtNqMhvnZnm+yVjrO9rcPXw4YxX6OyIIvGRDm18dvDMRmVPXbRVAoxceP/bYq4L4ZPswkyDx9Bbo8ctt4gzL1HCWk62uk3Jfr5iXvvWYqJaW0EUGYwZ5mL4PHC8CBLrr/QyUi44TMiBbuxDYD4BclBmgbRf96MYbTXsQYU4BWHp8XsE7WmiwLzR8ZOHVLpWyF6xUMIvcJsjR4h/iF6r3AoDp5/RuKSaEBO7dgr0gwrfECjrJEbI4R9GceohhIGX21Nt5WLCVVDVMgFwG7TC+ADWjZR7SefQWLGm0g88uaj33XmWYlrH6aJL0jk2xqFONK8KG0YaFMDujUmLOuZZbvT4rYEwgA/QET0Md7c17wW2bs8FiJ/DUoaDQWTtajnG0okK2zSOWLFUDyD+hGZ1kmJc/WwY8FbZ5+fCbWNWdck79lWi8DLyluAcIrAr2v3X7OOZdD2IObajWdPOcHI6UTXuRgg0Hn6I/qv8hsw+ob6KWxHu2AISjxufhG1O+hgxks7LJohpm92leQ23nclrqzqDbSzyePuy6vWiH/WhMBWtdlnsbj9xjSr50GICzhI0pO5xMIUzr4IK90GIlDMTdoIi0oeciggrr2VT+XBOdv6lD0lIh8ukU4g0rYkRvpA+59HT1ZLNGd1gcPW5l8hyNkFwyDWfmlAW70GKIgjwIsymVeaeoDajexEq7dzfo5SOsFF6duUkUEA4qO6/m3w+785H5/ruAkLD2hMINnxV3yhl/ztiT9Je2Fq3DeWEX2e1SBDXQ8zxiYpEBwPFgXm4aQ/N6zV+Um+Gt7Ll//5Py
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

