apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAh7pVuTU4RwHxYuCKesPfZjFyfgyunBSHsNd90b5Lt/lUHbb654CX9fYMBj1qZ01JO+/wlDxIPIKWwQHkvog6GY0rC+235eYs9DVPhxYvU0ptrq6DqgrxAeLCcc438PgtQ/vkC3AvcTexn3eVr0D8SoiIHABSTqBOIVvEAWom3gGRP5Wc2l0UDdOQalJDJQI8hifQa8vswccYXTU5GxP8u9anoyVwqIJM642OZwL2m19am8ASZt7fGAbfgFVYinVijzE88NN0WFKYbbrgjnl8AN7EsEuy/LJpJcwO63ogY9Uuk1gi/i/hdA5phDXZBfC5AhvN0KXH5uA/VnyZmKlT+YanJEfPh8IOT2Vqt7vMiBHqGxZc0vbYezCCOnRdmtJ5R37xC2VVyKor+7CHde/kFzmOXGS0vAjqo1/21O93OtsJ5i9VBbw0phyQPE2CAY3g1mb/AJjevkWQWJBq4Dp63M3JGMiwAzlQHZODDZw3CFC5STHpxDyLirdbLpS93ojC6ZMuSHQHVupDOz4HE+AntTnxDgKcXLugwoDngmg0jldUfoGO1MPT+hh5UGiQKy0Goh8q+v6rI65FU7We1yQiaO9dXagpksDj6d+iNSVAJnbTTfWSz07cKZ5Y1XPvHRy/dibOEjpORFBtFAJrMtDBFpYZKhFrxiBG0iaCbPINFdwUzb7gGlphQRHYyMaE7wvd4Np3ptYj2kkGzeYjJ0vFBiWU1TqwdGJxUD1jooxdHT4aYSGt9X92Kl24GrgiIE9b6p2MAzfolnq3zt8tiWnBHFdMpZXbvejMaOS2dopfzjUy0C1WXtQFTdwdeMCDc/9dSmGs+seSdVjjjeAEozIymcIetA3eAEbUk0xMo7PXysXeLirogIyfFfJ4mqmiVOy0m6WczH3M1Xj9MCYrjE3RYmS2FMsCB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

