apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB3BOAJZdGTWX+5WKZQTx9frAa7E9FrUY7UA7cXC447ov7Lo8TrCnHKZmmRs/rl6NopRJJxZwCD+/UZdbhCM2XzJkLk6dGOGSLpQ0qMnHoiiocPthYR88d/3FgoEt9wzMRJSB5LOKCBVoO1T6ETknNlb+jE5pMoQ9nhbiOfBYIaCbEp4PwIS/9SgNo4FSq4Egz+rH5Itvo5MUkquAQ6GSptIlDRZtwi+2ATZET7GOijhN3IS1TgbIVS61RDANmsmb7/vGF5FeMOU4CKfiqaJ0HtyRgduYJWZzsfMsKZCBmhT0tlMON4CcLmTZ4pjVTc1C8w1PCeLhi7e59Vjor3gVZ8faZn6Wur7cfOjDVwAgS6vNH+CmMgiIQVqpWIFH7A/Y7gHAXxK6gpRMQ5ufPXfE1n+w/4du1Ymi4KscBXE+3s52sKL5rzOlr+Q2PXqi0SzxFdySJbARX0P2oJcMiMzC9J9p6HQn5WtNQuo7gzkdn+Y58QmG/PZ6hMIoQPlo5RFZk7rhX2UADamSNkO9Er2H94dph82ZDNy7ZvAv+Rxs4Y5kN9SylE7PUv6IC7Kt+MaaMChPVIAY23mX2HoOG219xKPZu3gVbROoUk4OOTBF3SYkbTW/4qhuQYWmwW/A2pmhOQwm3xYtKTNsKt+/BNE3D42JSApGPJM7yRlm7KmYKkKtzeru82I4RLLVNbZdDP4jb7KKf3dYEEwpprjHT2hFOa7yYER/GKm7Fg+S+bdKhAnYBd/MRfKjRYeHPLu/X6cbsipImpY+7iaSMMqetT2sKwxO+Lq60a6/yqujAn6Ty2Urucf/uYijgw5FF93k1hJmaztTf6gN7VQX02w1NddPAwlDl4NFp+Xa3XCX+opGYLojU0oieHRD+VCbBoMSonSVf06QgKKxsSN4OY2bnVHiVfooYutGfb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

