apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBE+TxAzUbvaZSRZObdaJgWoPV5h+548UYBef9M0JqGoEku9j04k7dZTshTUEUXRezOEjqCjyKgmWHC/Y6F2laGiLFkpgKE743Hth+kiL5WUbe9fXwOpeSUMZ1j3EfUs6Z5E7Oy923ZI3jNMtQjv5vtAeJD1BM/mfWZImQ0etzqRpM48T4MxqvWXUrkOeXfhrycsNLMU9WWbuHFrI10914FS2WgJlZDzfJ3A0h8DJC2aZARo55QNpgerped2h+nEK/VSMm4SgpcfKoF9RMuYYN56J+n0XWznrmWz2Lfi4zmyEaRJR7rhAeuV9iEokYfMIe/VINbzgF5qMI/iPSyZhO2g6ijay6O3hlxS7nktJhgTDrhlP+Yn4E3PqdGGZWkyjG+xHP046UaxO2H8PmbT+WMdo7XTOqwXzQI7xczAbM/uSGkYv/6OAUPoPPdpDkAe+IaEBzVtJpZyvNK5lHTMCMtSkuQ0d4JNSBVaajqDT/yqWdBu5tsfR3Kg6p6nx2AzF1ta0Ds1l6uuViflhn5eUZgorsBThmJztfHAnmSX8fXVcZe4ctNauHZPBUGGMTmGXYXesjZlbhg9ezQpY8pICGpszdHz+mTPIQQ3GpiHwROVEQcEa3vnCedtIhlb/EpggQQsfIjgdOdcIkJgPN9tLvySidc/czH6qIZFgsudRsZa0iEzvrP5V3NYSumcg2TUav1xHZhW13dBOea1qEPXnEtG753aV91V3w3Yv+zst4WVhPSo2qqvIbNeeeyLGM9+DJ6j56Ksuov6KyQGhldpjmcavzdb86FpwqNa3kDc6/qAa8qWdstJHHtD55+YeaYeE8F4fwcer6XMT1WdxWb699VSr+SthTUl10d5q8gdNNvwE5Dt6UPPygI7YechJcckDV6fmUTsCxEMyZjxsYc5SBrkl1jJNgd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

