apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCt2H+FG51BJ4ER4O1MTGTT78xy7HNwuWxGyDx6yHJnI3wItr5sWey90v1j0swd0XodJeKBsf274/WnyNNDRiwC1OMHRkQDWTXpjcMck7VIZbSDKCMWdqe90CSXtWOuDxgQgbcWspMmNWhcIfB3lc+b2vEDP6GPXZN2RVbQYkimlmrjMDb8YM86Qg29DNLuoD5z5QYovQo8WRQrzLSqlyfrBQkh5Uif4LC31vmSjRfEyMRNFcwg9hsOyZK21lbKRvEaiyWAGY9bX+Qaq20DIw23Baj6VZWdEBe9TG8VOGUn7SOAbCMk8MS6k/vErNvyX9uTfoSnoF4ZfKd3GfgZBPOwG+PKNHpTOqC+HNXSQ1/xOxQ/BMWVPv3MIIXKGmm1GhUxQe+oaHvRth7EG1TOehEkxwO6czllOnFc6HIPOCMifQl/mRJJyT8BVcyQltwWyHGG+gaHQrSuSOk3ZOZAfFmJTUQnQf4LjHo14o/64wDPOgmVBe/Zj4wyof9YLaZ6kCbg6jYlQy1K0uQO6bsn4Wr8Z5oQK/SnERsLeL3wWKH/6TMlW4XoSR4iABjto6T3Xf5qaehU20Nlx33gp1gmKCq0hTUEkwkD6LkJ5i+/4JKGvgS1HOoKsKMHYCAEPPrYqAHpNmR8DdZ9M2viHDFWi9mevdhw8DLbcW76ijD4sDKy5fun5gFCiXwDaPuKgWKBpUEKqNQue7vtHj1qPw8MhBVy8gUg/DaerQD74UhcLKZIzyNJubO5l4GeBipQGCrt5Uama5B3TV3DsK7V02J/+wUJF/pULubSXHgT1CNsfeghDfy3QvWJSm6Sax5zXgVMusNpl8xNmQV3isn3MRWYFF2HKmWHTZGze/123Um2SitNdrMRhiR50pniomAoI6wyD9Q2ayeRafOKo55oLnh4RuGKrmP5viFV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

