apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAJiADct/Mr5mxK/8NhTfG+AHekczI1uP7LvXFJC8XQ2Ts6gKk3OACcH64Fg0vmswAw4f46thBUiO1V2f2sLG+z9PriljkH7dAb2pHPfzpiyuGeIa/cRfHJWP50UwxyViWZskxY+BaEfq1KW0q8Vd685EWSzdTc+KXVHpWXnpf8/ejriatfRYzWQYTABYNNZlFH6rn4ffTDwWPX/M5yhQB5Ug76vZEzXhI49mEkkduQXouJcjjpfOzRLWKm/jYdEL5wyWVg3Ndr7n4XvM0SGythsZqyRIFW5H1E7omcIm2WnnWl2TJB5mv990nw1bwHCVhE2LZ4UIZbZpF6i6Kg8grjFE4soMtfKpgxHREiXXvAXm9ISr1F6cHHR/CwALeDgqLiAPM1/fWVvdh3jpXoODZpqhuXv3YBPLrXgqBF8d6R/+eODf3EZeOFwvEsZmc5gLbeOD6pBcCBsUt3AbS3+aTbejpdD4U7dkQhWY4b9yKUzQHK5RbJzIdXxXemf+EawJs45j+FjtPhtn8xQwZL5zPe/XfWSaw3wYSO0nLckAubsYtCq/nVE7/CNjZNtKB1BO70YYsrA8pcXu6s6LC/u18xLa/kvCCG7gYCpcJ6HrdfQhk+2/aiyDQsQ27ET98OGPx3vr19HabZLuy0W4rSYJxwpm1bR7sG2WMeO/MBOiM/SAqpohLTNft39H7Th08wqg5IU7pkMUbXulApTpvP8jmdp3/ES2xeFJniB6Y51NbOYB8ivMWFK1KnXz0K6QjqE/1zu7YO/zNar/6O1rxEiyFZzS8IpVhKigIN0Dkl79PpnJLg55cHfOS+881/WDkcaHYz09jSpHKSvQP48fEmkLXZUPB/wRBMMHy2RegaPkhSIAYB/lKynHEYb/6VvfTpXUw+42gDV85MhOei8SDmj8G45V1Uc/fw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

