apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: longhorn-system
spec:
  encryptedData:
    .dockerconfigjson: AgB6LSNCO0VT40USslI+jcM065+qBq5w4WL2yhP3/lVp7nNp/G+HG9JGh4ZGLXN92U+awG8k7s0IY1xKWQxKe2sxRug1DlvMIV8C7AhktgcCA/k1FQLmS/jhmnMQ1jojrs5+T7JVvW2KSuuOP6iuul44Hzf17+pTn8E4/7cM9xvSAVLuuPKjrFsjfEplyQCVAjRsK/SzsfTLfzLctb4VRHTD9YagbE6S0RB3r2qcKBARC89CCrPnHdcrh9V5IFKcbUUG4vKXpztjrswyndStFVXQiH0eXgPNXZH89624xTunDz0TNTWDwDPXW1RGeActj2Sy7YJ2ThfsZWTkRm96g3/EnQBObf003qfTv1oYZLQu5QNqayfT1JoaMWiPv1D2gy+DlNxr4uDhsNeg0pxg3f3zWPafYNdZuXkOx8gM/A0BzLE/B0DkmfIp0qTAMSaxJWkcMczp88NnMlBZJI4rGVJr0IUiBUfaOIGLtz8loRVEiu3mTCZQNde0I5FamYd1ZzzxR2Iu5wuV1+ydhBYo7+k0Yido+MY28jJv2C2Mp6HzTj4Vt76STz+hk1dj1QBaNcMcKAUQ91IM+pk/YjporxevU/1Q9G8wAMJbtQ5sRMIMlhk71aX+QQYs9TV2qDvO5PhFqUgjeT6ptQj4GHADEzGNDMxqsY5sUM1cd/xNCNHdj7zvAyCj0A1q+MmY4otffTc+ZVsm1BZQorO/sVMkubceeRg5MH9KQNMIMaj9NYqCTYLlocfAKStMbz7DRnzaBbBmmiqtzMlkCmpsr5kfoDhLex1G/XpnVGTWqnJ6BygFxf4Rc0qijkbmxmjm956ezX/1iuKlSLKFFF62u5feSz6c51Y6lFPc7H3m2u1mqRvc9o0Ch4hjeI8zj/7xz+WnXR8Fk1wqrYK/LdSeCiH8ci76M5UyKxWg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: longhorn-system
    type: kubernetes.io/dockerconfigjson

