apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCdUPjhCPI92eg8Y1znXwsMoXwG2N0h4U9PwIsCFBHiin8TBZW/Ul/F7vIcyCtHyNcE7XSBfz8k/BaOBZRZX8wpKi1HfQPP9oLjS8xS9k2YEbtoQwpHLjmlxc2xl2eGT3pEta2yqR6URsK9YlSCon40rGOipIsxZV+mk2OiXMuuuCBYufa7ClraGnLbMtaDZRNXonaXVpqkriNdbXP2C4NznxnG161Csm1rrHkwKUWtVDKELz4zMAOiTeQ3G8J6/lsCtFHQz9/gxlZkOEQBTcP9bsrWDA9TsmcMjDPWpd14DTwmIc6h2vx0T+7/TTiUa2YDzVyPBkTE1SStz/s+XiUEuiwTcaxgZixrMLljS+kjr7hlKX5U4Xe9SIz8nzrsawr7H8D5jjW4hWj35yBe7yWmOgWGLA3bGIShuFyNl2TmR7Q7BVK0cO7br+6bJ+rDJTfjq0fCbjiu8QdgYqPzf1xNmenWEWOiP3TZqkDF77YKX7sVamvJiT//MubnKe9HnDaiBfAn9pdT9+o4FQl796gO8ti/ZBl287gA9IGwuKayFEM7XDGRtGSTzdHMAEP5an/je6XRxx37Qd46WE+pE6Xy2KqPsvGsCXJAEdcUWK+w8BIL74Z4zeRJWrgjpevA8sWms7TsuInbSiFohlWVddBSifb3an0oOO5fg6UDwdhjyz1DEzjDi5Tm2q4KPPraqPpR0CYwAnDHg8lffGgD+gD2cjnfgA+/HnEXR127WEdlW6TVJNZ7IAyYQXSQfP/2nvbjxmH72J5daEo6r0nYF459WRN3PdpMLC6eWp9vLNqSKAZsQvjNRE0mn4kEKM77PMFyOHGvyRTfhOpg7uEsTq8vU0i3dviO8ahC/grwHDVFr3CacEgI3ySyVSL1j48cck3lw6qQMqpRZ1cb7Lw65O/lRPbpj0KS
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

