apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBa7n09Df738z58LiRpeqApXF49UKbU6VeFkzvc7M6lnaWR1E64PMlgF55Ag3TOYqRb54KYpcoVM2FuxmUFg/AXrYNVgNiIHuAT3v6koYWfv8AMMxf2IDa637m7WuxHGW8oefkqPab7z5naxd267GEEtfYE9zf2vBwV6k0PR7zb2fmO1KpllQe1LiBv9tA0E4UAtqWd8L+LjxSw/a5XAPc+6e8q6WYAPoxRAzwZNIMihIC90reZeeBKrViz0I1EYiwI5Na11Rz6Jkz+eJZH+qSpwYYhAWcnNoZ0wyirgr7/ypiARTx8Dx/G9Ks0mrhpuerfcBZvn11Dr/aN2cUzBtNmgZbxygBewlxEXdVOJ1SieyFy51/lrYLbW/fn7L9CfdOifqIb1IyrUZz2V2NnPIvE+47ZxUrFVvCIpGkNbFpHqoOMAjA+1bHnQkalx/tEV9eT6Amz4yW4DG8mksg+zL2bfvFXS8kaSrFDpq0rhNU6MZabZHy3UfRbjPD6zC5/vhitReKZ85ufGnM7fF21PKi5A2hdvk0eV7oZU4HSQQ7puy2F3nEqyL9kdkCnTgqlDflmoTGLsazQCrbcS0nTINPtBypE5gslEN7e/Vgx+IvBbqXQrdBj5iAlIXWFbbWuULuMKKzTILP+AgdYK6YAkqIit99XZFiIhi3/Xb1Q80RdJYFELU/ArC1jNBUBmtcuZwlVoDN3GMhDb3ZMdlMc7n7kj46K1fW5nj4BidkZOj/DhfBDxA5Hkf87+0N5bGRLp65XpC/r+oqQ6Y+fmdkZVqwN8wYW1TnnUL+qacweeC8c1DIKQn1TjdXvHK9czuve6Lt1hDmvjc7ZRguyMj9h8kkT4O7LXXSloGIlqAcSCg2C0MUq1pXcwDMDxnvDLqgrJu81Y7+AYjM/e9XBvtmKtRmUC3muTRHK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

