apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAnJAvG/d5kdAHtmWCkGkP1sS+fnHRFfSw44TqRD3rVP9Ra5otUfMLcHYglHdbDSYVFnXlTosKFThv6OVNB0n+XuNTq6Nuhhs7vuXSKFNJ6vdnVfms5btGK/wLV7GCxZ1PxvbPOKbywUbXYkwYpT9iOelJ713ovhAKtZwhNO1O/cxpBvedS1RQR8rDnU69uSI2OES3FvpWAp0PCYDs/0FxsRcwWDBLbsUTkFLOjLDvZEXYMPf7WcIWUSXqqpvWAdY0FUgtgbEXh8aJVW8l6gYxAjyW0BcaJzxrzAabUVQaTO2KGsInJvqeZiMmwcGgphBfY4GPNDuhzZKHywZxS/ECFyIV+7AgcgO/oaDqn/owCF7nxktgbbOu69Af5fmIW4h4ZqBqemJteS4edz2b3euyA3geQD5aftC7Kwm3KmZ0+Pl2KYakQI8jq3ODZXhdJXUWwDoMXRHeRJ7F66wNZ8LHCRNuNl/HoDPWmHqVD7aBQwZIuuKCYtoOI6Mxez4Lk/D2NeeO41PfabYcZI2WZXhmoWUiOkAKlMsbLKRiBhWQGkLBq5BhifQYE6XatTW96hNYuhyILBx0szNRIvQFvhVgc5XDx4N+Q8CYGmasRDXeKd2Ho2K3L9UFK0q4krCGla2wjEzuWwnL0Z746AWjzxWqtkwerx1afOSFvoUQqnoJJEbNdnavTRQUHIkXVFc/HZ4uUyD5C7NISZNlmA9SdzwDXkKbSZw9a9Nx/TWOCISI3Is5OaEoCZTDu2Tg55rqgvttJ32C/1qYHeO8EIke1qYxJSuikRErX3DQS4Wll++d0D4zwWye0g78dHDaqVqyRq0Hiozd1pTYBzh/s81HSLsfOX9vJLsmrvZbTGA0WktY34dlsOy1HhrSTQbQenTXOQ35HlK+OSGnxF9GHUFw6UhE6dbSUU8jc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

