apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: longhorn-system
spec:
  encryptedData:
    .dockerconfigjson: AgCR6ztn1HmOoYhnjU3fuXvjsQF7WvG8qERia35vQxPOnuT2OjLs4TWZeiXKH5smB5Nvwcmz6uFynPEhtNmHEpX7W73aulWME3ApH5diQ3cnOFPzCyyAiwZpOEpCwCoeWGniCcqoy5L/INCaLtizHHaOVzWeO0NuC/plkGWp2iEL+QiEp2kN2y3GtsDvJxEct2VCvrB9vqhC1EKOnS1/9L/SLwsDtRQMv5i/NRWeC1wHdY79w9vjNX7M1iaTYxWvY4Dbyjgu6l3jAvgLaQY8f/r28DGRVR+ItRcUVoEpvKmBjRm6RdnVV2+IErV2ycve7o2MgwtOSfSqO/u2usm/qhQcT4oIYCEcqbNdg4get2prTv+gL+yxIYBgkBlfy9jfdmfgvsuCMnhgqW4Sp6+dWrSzTuxFYzcxXyqerSxZ4cM4x7Wr09sToA/ZNzRTxpZaFdQ8rdlmDenf0K9o53wImJy6LFDKXtVw1xeUzJzL/Y9XTyL/mEXorVw1Mz/EhvrJ1Y1X7PMMVHGKfsAJctx63KhVALqNjsXVMr5rB52+6v1Ow7Bu9NbKp1logpPZGQjSK7XKvmbnngKmhrUL3eGpYMvLmo+9a1C78lo3FqS4h/k4T0UCjYm2cTp8P+6HHZ5syMmdZXprApq8Zgqj+Lk5JweCnHe0b4Psldi7lZhnsiNy7uQWM4OLG0y49ZM+8QD/crC5e4pkoQDgJuDUVIDw8ifUlSJhGXw/fgfWeQD5MoR0//QIi2pmIwag0wHsYC0XGjjf/JFfPtWcp65pHYVOtl8mXJZMTe86bu0sSUC66y4bsKErkvvcr5k7nq5Z1y44jlfovDEyAItblKc2Te/SXoY1gnN2LIA523D5KH2A5LwxWc9lDItLanGX3ZSjMPHD+MvfyVdlSuzr0QiBRcnReUBwpWaw3KVW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: longhorn-system
    type: kubernetes.io/dockerconfigjson

