apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAwU5PKA68TXsGP+uJ8AVZooPKSrY/H6q5QvOHuzhVNrgZDufyZca1vmPxf5kWpq24NgrdboKZX3WJjl7ZOuKT+DD8BvN6XRwarC7Z4bxfOKetjLf7nxzw7b6KX8lJqei75DQ/GR+SToWEVchSFH08KkzZbURNsBs4sPA6LvhgWDM42x0ZDbQO+3YIxEgWRgBgDPY2rGnnhIdTJaEv38VESqUIq7aInRgVPvCljiDSggnU1hTlkPVbE0KBZliOJK6OiYV1u1M8PK3xVuGe5b6GQbeoa+WVxIO3KPr3Cizpz/EtBlJeyD26wC2av+2YIJQlo+2rVQtKGK59qA60rgEhnaNv/Sy4LhFT2031KiLIzOyALBNyRclVSjYIXva/GG1hl7RYSCHj26xSSB2Vz4NwRM4oJ8Vfl1kJVYDCA56gzrrtpoFJUBHPcHe/t0achO8tXcF+XUu3wyWTA0H8tWWi4/vUsVTG3dKFkp9ZVb+5BQjP9I0yq5FOMFKw0WWxIJ84d7fPrMuRa9IloBhkY7xIgOl5W0gPNCfujpLOH7Gv3sJyPKUwEy5y3vd8sHYJiKL8yvS/84C169KBfEqhBx2AqO1q5VfHDNDDwkGNDSNZ7Wv1emhnacbBtf6URucRpin46XpvscnEAAGB4Rz3aJKTENdEzWj0zW9DvQObiSGaeQAKB2MVNNHB1xKowThFNfiSmGpzGgQ0iUTre5qQwKQv75ZB3WI8ahVcW4dhuQDo3HU14ugg5/GGaKblnNdNKmK41pyqjnyBKfzuzwnp/JYTEo0b0BgplnheSjUJFfFH/eShb/LvpRhFIpvP5F1cvJ4bjAns276b++ptRBU8Yx50WDxsR+yvfJ/zwfORl2dhyTd7AxMMtDsKDCV2X/JA7J3pSzXQtQUdZmVBsPi7d3BF7hPbb5h/k
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

