apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBquQcmtH9RfO+s7dzbdU4Ru5eyqFEjau35wRd/CLepWN/3m20QWs7zEkMCpmdIWOSQ0RSZcUYrFO+wJME5sziJqPywOxZr3TeQz3noetxEUBu5ttldHXflE0l7gDP1rNkTf32u/7ViPuyzS7AWYrayW3NLuZ1XBLdJl4JAjsEl169HuYB6Eo2xcujDVlBPtFpDxdkOeXmhxKWQhM+PkOrZvO/P40PpE/o450f/JyH+NJ0ZYmiWaAgZXnNFN7XkfNMSHQwa1i4feQ3hnnPtuEUftZwHoLPSJgjRnks8IJqd/pMyKAYTt0ZJ4ps57uU6yIufQTQtp4BFxjQc0vePXgNmolp7LXp+gayF4XihW3e4l11A0RvdbTQWGdCeiKb19i9YzBUduA8VU9466f1cvTJcKKJo2nawIkd41KWP+EWuekMRzkY6xuCJpFzHTmum2/TyuTHrR0VGS0M7AY3tmsGxak4vCVBZnjFj3ZmJvTTzM3H4xkuHBEL8jsnP3LzWct8dltBmmoN7KKfvE3P68eO7mRNYnNuMbdao09kypBb04S3wDD8+TR5r6o1DE4vNqBPbbseBOiHxQwt2//NpZB82ZBt2gdyZuOt+c6Qh4q63qtZRDbKRZptquK2IxUcoO5JJ0rucApWscd1Om+inuk7WX0Rdrh0VThLUaH1aXCDn42k/gtW/QIZJVqAoiXPRcobbZRMLW+Z0kAXT+JzQN8RcFqZJlss0GR3ZCX+6S7C8JkXX0/hyg+AT3oYRJNSkXuNP7M2tFJ/EcNfYEaCRiz+ITMF+KDM+qe3oU66xjr4Lfze35q73g4YeAiczgYqQvNsId9Q4Q4Kq9BHypDRZuIHJLQTTR7lLJVfWn5s6/ueByN3WrAQjrAc4RcKo/Xt13ot6ApVvszClJsDb9CBa5nwpar4qfEcD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

