apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA5VfzsiuYPg8kVKB+1BOTBbd0pZ3D+H6He5heOZWnnpz5FRYxc5kDu5s6CZwHmUp7xiwMz9C6mOZbHAkcbNxlFGGdmBa8LWkKN1hCqMRcwWOnE4t0L5+mV9Tvf6dgXhUkRHtEzCM9Tj5CRghMg4o+ou9qgTJ1+HK+SJE+Dp613eljoaWDqWyjFPdggl0vLs/ane/0OnNMZF0Rax1LfBbsDx3mhpL3GQxdAweNj9CU//6XYzYV8REIIPgigEuaZoK/oK41hg4zHGQe7XHdINzWsXuMWJ6KEfGkAz6jepaZsSXIBQeel9pntEfENGjEQHvqj6ZeMYjaATLiTZJpL3v4cu0EfjaIz7y//iUObijhJJ748c+MLhHeki/iXJoYmy9LwXe9Wfij8O8qwyrSIHTulejnAfceWu/fPUK1zus46o+uv6abL5NBQTA5Qv5qmgqs2gF9+8PqzwTVsYSU5eApWmChjaiJqyw4i8RlSHcuKwE3AnPxO1NvF2OgTaNPtFJaup57MCGK1X49yO71edaONlmnksuhCIyL9dgyOCXmb3VCB3LZm/ygtB8BpKUWqzXSWoCldCy2V/cdy+i/8SHaDb1EncB1Zt/2k7D8rTkuMekMNq4typ36UGDa4JFl39rnwxM0+zZjMS8BGxEE2Ev/82rbZQZY0/YqPd8kq4mZr+LlYvAJyjdFU+M8Kbjxm5Omnejzk5QlKRKTskct6CZJ7na+TCN1RKZDLKI/4FQIJMQ4vjXgDHFiEolPxo4JHNlIUGKYqjXysweIE+P9BaCbOepp0eyq/NsZ3HpC7mis1Psd5PBihhjMTwEoJZdi0L+H37emE4BXNfLRgD2aHWho9AQhK/gmy06yQlapYDkWENgWEwnnXFe83EIBleWwc79RAI455nGHCZC6xRgSUOITQKusjk2JQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

