apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: longhorn-system
spec:
  encryptedData:
    .dockerconfigjson: AgAgQG8NOsDbapbXzN9zW2fypRSt+Euud2+U9r1j+/o6QV756R3bG1w3vUiPZVpPTJwBSexMBDf879QMMXUg0if7pyYbDyu7i0TsY0IfN9Jn8CLaOQyxSPTjATtJOtfSYQYsS06hM/BhNdxVHUvx5LJHRjob2HB0cSKsfbMImL8f3wabJhNtIpiW2tERnSsR+84K51IqBRr3i9dIOH6PkyhEid9bpUY7dPCQ7ezGNo2xKMDpMHFwTLRBSWPPX45JREWJV4xOPBWdeUoFUvl3yWBdiOMvBPPadcFMzEuL8xBm+LqhvAmFcB3mvQ3BqWuzk//hsWmj/79h9m1ReuqW7Lb6BlI+HzNOhcLmBklCdZ2An3nQxH4iwNjqP6hX2qUGIXIfTVswLwQDVfXt2/fNnjotecPwNc/xNgmUhDNaVyvBl3Ts+67bJLWs6CK1RkTuK/fkXadaY6x/aq1lfeFs3bL4dKUG6ME7woParmLhP4ttdzsORo3Qg3Iyqgc3cJHfLJ/+26C95ygmRtPgmRLmD9l0/mfw4hfIvWsbFg/nQAak6ueWywkbLfwWhPsKj8jIxM4cqy3xmblKAwarKJVTk/xxe+gROR1ZoImswELS87J0JTEMt4lgfvNuDn29lqn7gGj4jYBp0BbwrrzLJIkQKklmBkD+LXhEpMIMybj6VTSw9MRVz7tZi1n0cRcnUXiogij/XVYzMtJFGZYAzT+RcVFba0nc0Zg5siZmHdIImhtHRXwvtcdrZVNU0AgEB9hQYM5aal0+ZZZ67kkulGQxf58mjefA6eGZAQ3zDeq8vW0YqqkAKM3aHg2yvvbjSe2FXIKFyC3E7zR1DcMwW+Vv9JIHwPzLxw4mj1mIrBx4PJs7irhDzYE3EyMVqXK7LMyq0bk6a2sP35GLys+h3Tiy0Bk18uUIOpSj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: longhorn-system
    type: kubernetes.io/dockerconfigjson

