apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA8Zyq8hqqEul8gNfCNoCib41q/ByXjqDs2hUgxr9ugTWlgD8l3RBCiOgXJtmLh/tens1fkjg6/wDC7GovuOJWKn9lUxjg49iAa3Rs4FT+nd/+//chnvug9lUlQbVSL8RKnX5rROUoOzv9IPbO0kQbKL8yIefvQW5TOHZietHR6H1yjEzRwlMmD11WMUJ5x4bzEZUzXTYkNL0PftDzrg337Yh5AwRiwvWJ02/Ag8AMhmlAqeKUaoNL2WjaoXvmIKweShUU1XfYxXINCSiKrT2E84SXP05TL9fskXhdSNvtI7zA3A52gLHU74xhvAbpdOE6isEFKvWAdV4FvZRJ5IRGQtIgomCb1USzJergUd5rSYyXyYd+aQRI6AhPdKu3RlTGCf9fkglgwEgRbBIjw9PLfIETDfBqpC7K3vkksV+ZHR1BE2tnWEjsagxm07cVEcVULlg3P1n+jaXx8sAGSAFkC5acZT9IpxxLaCfvvYwfMmWTWvX6YpN/CmsrDjY6YSzkPVBrbHFSL+RzjXFEWw3Uj+cgDrxpY+EOTRCjvrggTOWQePMRwgaSpD1viU+VgiHlZQyMElfSMDajlzTDZawxbz693mU2p62pMNzbVHXce41Eo+q/rU14Wcy8R97RFiPBk/a1VP5qfkaIVDlA4WxgkZrAWe+NPwbrLOxe//zyawgq2xn3EVEXePKbULUMtMInzc93yKacxhF4KoHUwhnDeAwo2oQ1SgPrWqM6Vaq1qQa5DdO8rScPSCRT53v51lz5UBK+VoynT//PecwLJ2aHau7JHB/kcyQeRMpUKqZj90YFMndngUfdYU+AIU8WF6iGcnPzP5dTZ8so4lvkrtCiqbFowHgGYTY8WxhqZnwOnFbkzhvtQh075P7Bo7l8pjqkkP5v48jdqznI08u1uPNSAcq/CYtyl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

