apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBmfNpjnMxnP8NVaM1fV63piUVXmEI8452XOf30Mn+fptqU/87UTuuPKOSi9jqC+i7WUlvumEqLY+HxT4+EhtEF6f3151IiBMNUL7N501QmgWX7xNGVOk/B6duLH+IVwYO7RDV0EBel/sceHJ5Ds2AKcbUrMrXS1eMUk9/vk37vEDxYxKk8YrynMmVSZ+GMEPtDK8BtAsyQbcvGZ4uHHOyzCmKJsbO7xL9O1NOgj4cXhLkAliKHPwqGDNNQeuJwri0HAxDjJUr2xHV+iJX+1QxbsyM8pH3UIUZh63egmYid0NEy6w7aFDtrQ0stC/IYQSXEZs5MndHwmpUAqIMsZGkiXJBmyD9Kqh3BcaYci5vAOOKEuczAShuvVOFxcfXHV/jtoeFiyWJdewGSA0PiBuiV1WqkelkUP/Ksg57tLPkrnMxWZsP7NqsD4qf+/WSjneY4HZJNJzMmOvaYh3X3/m+uwCAovsT7NHoxtvY7A0oIj8zwy4iVPPmMTvyUqzyOL22djc2mx63u+RfCXU42SY1bN+ZDM9lBIK9DPsPSynkriWJ9MAMpUmpXvYuTpIK8CPRdqehleH9P5F8bS+WDB5Kmgn4FLlr2VJWVm3Z81oRfy+OE9viv5QvwDsTab1T13QNpvWqHXNB93SLWWGEsxFG1m0KQ7zhq2K2e4EZZUtsXA6A5LIHkGaVw1HclYliK9lTe4LyjQJyHiBBQ9HgqeYy2TSGRjC/Q9lwNW/sgujxBeOGsI973uJXHoL/+tzgyS/zSZ54dTi+U+u142Z5YrSy+rJ5omtZ5dk85Zn3FTXBibeaIi5IuU8+JEJONd9jI6+l3FHGczkY4Hx+f9wzh5VspQUJ6u0wDsj9/3pNRktLGsi6ucJpsfCcUZJ8BSH+PwJX3qTiOF6t/CCNotCFZeS/oHPQ9PLpU
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

