apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBgJewtPMaidr9o+iRZ7CkHXfWHWdMXPnmzxIIGqDauFwkW+V2GrieNC+WGQoJ/m1n+LRNlw8bmNDnAZEBe61RGmdi7d7TX/ZUdrCECzGNX2rM/pvEDfjF7RIfk5z2hR10I2yqy/R4whk+A0r6EujD1rkALBX/mW8bYQegKHqoz0WuvJVh7NiwORAkSqhfwFuXjlezbnrToRFDZe9rN05UgIjzW94w8SfxBsEtTpqXLEWRSvXoBakghLuQ7SARZLj4j2SV9CoJ6q9ZavCZzeUAcZmIZlfuxuUG/yaCwqKhhdHV8w7remOwtolRM8TwD6D5odOY++4kzpU/6WbO35KtLsU2Lr2t/TnQBLnMeMXFFagLR/cfGgZAhGqNJrQsqtPZTSGIZ3N9vVWrKqsQeoTmL8uwlk9o82nZZyLUdmPTkolEIn8MXLsqnNSVJZmtzM2gH9K0YjxjTo/w5jZiCkNa000If8YayO0uRloelefthURSt3GqaQaqnOa1nusYrmzZQaGjbIfi2LfkAnMH+4yKG7s0NMCbJYlw6fRodm99GbW16/sM1RYNnLn4utmpA60jM7SN8wFUVUwrnO2I7/awShb6TCIvL2y+tLFXvCYP+emostW0CNPrGH2W6xiLrwTGmywUy348VZrG/GnTZO5ZQFx+M/zBSwrNvyO0/85zoa4nGwA4VrOqpJwHpE2IUGvaXwP3oEr4XldBxlzq84tkeIAZrBGpt5znZnkOXx3ZHjQoH6Qf4NNhbTsCEswvgFNmwmX8trA7OvzD7djcdrcoY4KTBxC9+uQ+98OYLajtyWeQMSItncruoArlSnFppuAYYVcU9sB7sdDcBDnkAeZE0vrp5eS9UJh3EWwcPudgucz5jerIoAXyPjMG5i6P0EmZidzEy6XnfIRVWT5egj7oahzFe4lN+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

