apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: longhorn-system
spec:
  encryptedData:
    .dockerconfigjson: AgBHEzGwdN6irjLkDLm+V11/LqU50YIISeYrYP/rAYLxSzRWcUkvvcq9xiZ01cZBKliKY3B9bfvUj84BsVBB8l0KTcZn4biKKOR7Cq96unBuX/zxIv7P1bGWFuz58SNeL09pp6xEOlTEH+Q1swUvjpicJnoNnVbN6WTmt3RYZ1CCsf+1j2R6NbHkQ+SJfBqUUoyqZj1zuHxkcDUueNWUpv9Wyk5Y+kPpVN5OzIMTH6uYnUuo1dcZ+xJuhP/P1mYP5O1zGThLh8yGqkQGeYkoZDayrTn89WfldzowYJjxpUiPMmHnv4xDCrwzOkd4MA2oVencR0VBsnEya5VRXiFhakfB47DHx46MFA8CTRGvE/fs7P1l9+MPcrivNQYD7x9indo9c2SwbDu3zzG+QJBp9gReZZ05kptvjLLSahBaIHVBjCchOwGONhYtSUcWJCVonv83D4VkQHeQcHJzecf7PJrk4ps+ojvxwwMeFzP5krXgVCRDjTf21M292aT05PdHYmeIR/KCAM1Zyujwi4ls5G+I9M6KZv3ea18B1W7+gEtXSImz1W/LLLPa+BJiTEywfe02sSFfINSNGvzauLbdULP8qlYt7dw/gJO+YyKx9/uUAWdjfHI8kqtcJCL5AU4my7grMJmBcycTP0BQ3d46cyFieIyl4/IBeumGVoEWCds8821kEpebj3fuEy+LXw/pPhi+p9BT1JsZSed37dIp/+kdLgNl2QrP1xA1NTNexOtvYBNVvMpeCxx2mzNJobVBTo3ZIpt/uxrvaWjlpPyQjSL5bmov58nu+FDMLsojUl1JUsA/g+2tS+DOWYb2ZB0oRZDz+fB879Wfh9uOWlfYqS6Swl+UkebhR3Y/Wrr9ICxbOhR1DSnItBDgcjycMl9KU40vy7pM6XzF4FIEbxRpt69qYv2zGOEC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: longhorn-system
    type: kubernetes.io/dockerconfigjson

