apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAzBbmzfOD2Cfdyloiy/djHPmOFu8QyKH/4YwqZwBmPG01EQhJaFEPSIb9y1nWdHHESuGNRtcclRk7K/l8AA/N4iJ3zzCTOtTn3kqlBsS4v/SohNBbs/dm4ONGtO/y552z9UzrOAdZsIgZHm/2WeEygxCq4PR9rDoYZM6Ijp2FXvHdz2zDdbDzbsKt1NJFrGgMQ0G0LSWuMNZpRz5t7BaA088n4hfkxF8A/K8wHF6MkkTvRG1cp4tj6SL+1ltZ5ywjUt7TNqGA+/Wt9nJ0GpYZS2pZpX8wnH0ZSBBjfbEq/JTI4G9BfsMFr+HqFz1cKGHQM9C6dAJGQsBT3juevsdr5GegyhUhGo9SkA3Hv7IR4TADAFVZCVan+jUMe36Q2yDFNz8kX2CNzuOIL8JUUK3AsDieV2zr4jEPXnaJ5+6XtdamzQsBVoti7blUuLK2S7hBr+k2zHS9jijxn2TC52SAQ56pjBmy/nXsMehwjY9LyCV5B6s2G5svP4crfkidvBNTt+ZKgmDXwa15meXVp6uCxvnjfd797VqoLn9GRI2CvlumhF8SF80cOk3RbUsqh4OQeiVNtApXfbfNz8tA5wMLBQa9RCrb6r9+HM7jyUrjOBBQI8JObiNmpUFYOTVZj27lBkEqo89iWLq+h9DNpITU0JcjkccQspSA8CQgWxpdxWgqD7JxjrVc3vTUuKAqUkcuGvBpqA7GmlqWpvpvpNz7y/MLDnnYQBUG6qKSCdK6Lv4agqHfBKNw6zuOuqZh0WUNi9ZqOQ5UirKIOjvCJ6vNmyiZxDDRYEgXXp99URm2aDVP+IanKBUUslurpI+i4VByigeDE9G9WnshKDkMijA+uh+ov5JHifysgE1Ntc8O39FAZdBaigrf6yUZfWMOdKCGfOEi9AXmMYQ949osuyk6wIF6m4SjV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

