apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCDLJU5ELp+bl2kUOPFHUJaPg+4vQNpNwsXOF2UECKP7LvMkUwpTg7UtUPh/qsnEaL204kywbWaNgcze5uFQ5fnQ2F6IDHYwgILjjMqjj+N0T2bRfTBcqyC7YR2MV52FonN/pSwU+4MPTky8BgAHJDRtSagwcy7obUqdRwFBMMq6Vvbob1+X4Hiup+HwY1v16cCDHUlJPAKTtgKfHtdarDaU1Ta+BRCdlG5r9MNcpjBsFniwwWehGoZZ05JmFRI+n2yaLRZCjSCxb27fSqSjpm5ivwzBlFP+4S2kwcCmamQs5ySOE8tDh/So34MlFUqcz8mlDTQnzyaQxUkaz5woBrvO04chzOac7rWGXSgxx5f1w3Rb/g9rv8+sgR29r4FDg+ZMXPRJ7lj5Qr383VkVlq0/UMxz2z+RjL9jpBDhLhmAToKeDa6BrCYfOKTRrPxvqEx6gnj2x1TT1W/OY9TtdxBW74JtvF3nxl2a6PCgE6KKCmrU2kg/V5n+MkYrhpjLWW7SEJhNm9lHKe4YnSmBdCif+AocBkZtl4Avw//cxxvfP+ciCoXtEfLapE5DuC/3NNaaQbvJLq7j41w6CarivhSPf/QXIjY6wybEJGrf+JJXULV+LcIFTSgxa2G0R+vXiA0DXH4I1XBqstoT5tIhukDxn42MiiD1QrImQq7L/+g6bGrQ3xhfDyHj3Jw5KGBZMZOYg5NQTs7vAPmN8ldPRZbqYgeq3wFSBpxb1ObJkSaRZZKBZ99C1TCQuPZ+vHPPH+SP4cGnu/Y8/U6RXAnBSrXcIIKSPEamTQ06PKdpOSFdItGzsMzg3apUWM801jQjbK+tZ+f8Dwb9yQQzA95i1BZKfwbO59+zqxEh1/dPwhc2oEgzEPaTyLHJ8XSv0M5+snAd1Aswryr8brzrJ+EjXFAVh6BKlfd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

