apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBu2pzVX3oeCUBoPH+ZlrQZBNz75EnZXc5/GwVS8g2ql2d9iCkgVD7WL15lqUDUG1LUlHQ81UTkg/Z7HAL1MIqNXqTPYBB5rxgsnt+DGtNDHwA1MhMS+7l9qV2nBp8AjhVQAeYnZhzE6OnCapdOv83fdqxqjRU42XIjq9IUusmcbOxuNDACn5pTSue9FCxBQyjsw3QFCy/7Xn2GMZ2Y4iA30pUeey8fuUICdXvIXuUmyTRFhgyKTLos1ppdEl8Zv8lApyzXhswEMGHA8U5CFoTvIhhDzBimyUS4Pz/TplVQ7ZF2q/xkttJNtuacDxwP0op7Atm0ZR55Ed2dkFz6xyXQRAinQuHI3+JUHHZY+ihOePK4kshcplbyGYPzBilfR4zEjwAE9NwVhwusKQPyLEi/tsUjRHDKcfKWwbfmRtBL9fDLR4A/SFel0B7NiClYlvuYrHLP2kMhHAS9qraR28Kq/mWOi5gKuNUd6IMU9Hh8hC46qKoUfsHVlKK4PDvGrqFvhNuUVi2935JehTIMEs7dIMdvJuM/IoELei1rjP8F3NUpui3WGaa5Ae1pvBZCjIUZNR3zaM5IvA5L0tQWH7HXiTnwGgb7aOc9bvdiu4gFwHNOChOxugkl/MDX9cJPLmuQZTTjwPlKetrpY88TaK2+XXIgHfErNFa8pG/kh6WPj7RJVdMaD36Hcn/0RgJ7vzXKxzyD5chtuKxwV2GORNWGAg18IosjSVlB1tAwx8eEixhz26iMUDA+aSGm4JyevJx1/KdlYL9/q1M5jtR7ds6GNcab3nFVw+DvbgtPsLKE1UhYsZsMK0lPEv5fCtsWTMKFpjWRYKTOd/lG/sx3nZc2EuobVclU3sqzh9JyiUpuT2FxlD934a71CqYkH2IbfbSwdTmV3TK3o7hqRo6MSbZ4sOguaVWl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

