apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA+1y5lqGvw6FfTnL4+/WvEu4g2AMet7VO2i0RBNKxCnCsDVoE8t1lS8knjQ803d6eo70W+mFFPRazsoU8bBd6gkMDJ5jno5keywZeYf5XMXfVROlma3+2fcNdUsLp+w6FC+SClJNpseHd2E92gb/mp/BfRm6I384X6If/iOnBadsw18A1kfDcZCVBIxQAcP/mhlz5tQy5Lvq0mdvz4Dh+YQHuXVzcJjF3xYX1IGGitK78raPwMoMkY9Epw0dbqlTR/FSE199doCTPWKi11K4vv05zi6nZGsV3Xuu+MRNvsrHG0nc9dvhWltJUVgnzzS5Gh/h9S6xJfhzEc3g/XgCEzA6DtFLjYpZat8X9q7BoS7gE+SoEKnQTi09UW+y1e6l1Z1YK+ZG/hpY8LcicJqPp34FLzcy9rnFY2rs+tn6LlbfnEYKRcKN2whv1HYCoJ3zZ8LeAy99RArU5ZTE/jicFCAd+auVCArk0tQp9wBLq93fpas88+17VmQzJPEvD+WnQpukht6YLUfuq5ohMaj+vX376mxA5D222hrw+CFYxQkhrcFJRZwZ6MEsrKJLeyzrkWtHH0BrQOwQAZGHKOh7+49u7gG71BjV2Uebb8WGx25Ig4ldLEusf/zErzBeOno/jvmnaPdcf9z4lEk76xxZLOI85hClnDsP3j+dhY8QVqJGgiONSo2SznFZp/icTIHJi9mTOgYseiar/GlC1ija/vlexWAV+3HWBuoKJmJ7AZEtz/4PMRFZELOaMUQ64kjuOig7l+EUyS2AmCbc9b/0iJfdVFtIv4Vpr+R+0Ew9A/hdATpUSt53V2JnqGZelHU2lW63Byk/YkJcevCquKGPbcTv7+acFEnP/fF2fVoQIuSDaLRRC/35x3ZWFjgPA+8C3CDSl+s8m0qJ9U/uwvDMBBq7noUCnJ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

