apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBADglbot09BPclXtD+XYuRKM2H89lE7XKZa39UzzdSozG4a3cHY4zwCfEZu+0YGA4UCY6MmhdHVvue2UZWUArDKw8rApdikNaPANdykTqpb7P2cx7C2+2beunE6ix47xDGwy/OT0bIsA7DoSeqdG5j1G3t5/tQRmi+rJXQpU9hzV0OlkZflBiIA+FO1kGu0Z+H+hxnEk2QrSpq+5+rgzcSIILcJCy7gXuKee4xdSvpX9Ep0C9OE5C8gh6xg+1HSBM23tRsVHJCshx5JcRrscy4YoN2iWgq4zpJIfrfKUz+TNqTkervGuSn2ALlEt28dH6/h1eN7ZVbUlqMA8nD3J7MUHPjaM8/ba7Qgf4LYdxPl100rZ4l6rm8llCpc+vkZ6xawyo/9/VKbok2HqJkMRaonz9VRDbQPwP/Ocs1MnU6qS+f8ePBdNxm14e/nsFmwS60qtYwoyfq3bE4Dmiz+F/TLqDYAfLL80MuUhX60hIFPVdLT61Hji1CA1Ogp8HTOLJyXCjhJUXKIL/cbWFRfMj0En6Yy8drkDxRoPM9cWlv1Dyf2LsJHezFXVOxEXzyfZ5FyeV/JElP2+QYRHGvNXAsPATk0X1wwAqOtvbCloStc8u+7yBvmk/5JnZjsntUyW299e/teCI9F3Rwvw+9mGEETDdHuxlAd5y6pa4H3SM+CFo5S2g834Tk5lKYe0Pw7yugQNfDYSLEkE3LRqSM8lm8va3ENpvzgnKWp8zrS8HD8y0CX0lwh1L8uvpFVSchJmzNirqDE++ofafV5jhSM6N7/D+/RzXMfEAIV6v/AfOp0Zw7M0nqiZ8/8h85MgfnRHnm7EtPvmLF1iwbSiGUgMg21SRwbGMqo1I364ZnsTAa0j6DVEvylkviHzzG1uaYkL0NiWBVmrj1KBnq30DAUShvhcq4froc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

