apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCkLPG4rB0a5Hft+7zQKL0Gi2qCW5YI8n+ocKeVnjiPPjkpXDsCpuEobe2KXHyjgNyTkx9S41CjNTfZjDz0r8StCohaV1xiRFgg5/9kW6LPcQbVknQgKJDjCRTtvbXsfRpzrlgCf2hQHcxLBGPlgTUiLBm+4NQocl5HcQYERAZ6uotCEW4yT4ARdVh6+4DFXYMiUXhXiS4fq7x0VVwvPFZao+S6W0i3skELlNW2bZx+I9ctzLeDvaeweaE/8wP4pKtjqi4Y8C8Idl7lBY1oYocsNLs2+IalvGxFAGDigdpFFd1Rg1JqgJQYbyDFIgf9bE7e2xTKq7MDH5D8zoQtqIA8l9HaDK5kFYf7xnZ7cT3V5efisMiyDLYPtebFk/WzwGUJ5yGugiA1+61mAediqNGqM03LH/a7Qv/LtU2Um3R1j2fZdc570kO2wqLLg8hRR7mNslQzzHiUGJcfaAB8jxzXcVuB+lNGkq62Vksgs9u11mrkUo+v/gijRzX/csF4wH8+HriApp/5ZRtw4BiEsUCDQLJi5GJ+hx7JG/wD/75NVtekI6aMQhrXQhwvvTpRrX4NblSe9UWI4UTi5iKKAuuQLt6TckLebw8uMjvPChjtO1N7TEQhHWRfIgr+vwppkOwtjro1v0+Nxzn9siyAhySDm9jYeNH4+Z2u2TJEF1u7UjewhK1ViiPvdKDq/5AUlc/CQ/plpcyEGkupuLqsra+ZnDB7Xcf7Fh5WyJpVm6nbfMYwo0EiwRnW4Oqx2u4CE4xjNnJ9e+2MTcyvXPB1jidkUjwIKLsNyoC9y7/M9uLNCSiN9VqI10+T6I5gdOOm7psDolO4sm9TnbxF/GUelMHAF5ROkkC0xgetV4W1WfsibkH3GxMlwe1iki9EacZq4OyRp4v9Wu3mBIM8f7JowPYLdoUX6aKM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

