apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBUq8qLl7V+0N6Y7KHx3PvWpovIR26R+oq3UC+F6J0NyBoMz4ofYr+XVOc1zf0gsXi2Mp2uFPQjDnjcPPbYVInkYosc2C3gNIKUBVb3ROKKWRlhuWwvmtOlgGRQUP+m4SfcAXjSktpG6hgXM3zIbx7fGt1aI+iLAOfbdfObFvle5ZGAnwq1j7MmDppb1VKFESgVrESgX/tNnL1CUnwg5OVqEmvf/nrFwvBh0bCiAjZ+EBIDwIev7D/IkVw6x/nfQVLxUT3KHOnfkIX6TTHKsgg4zFwpd3eNh4/Lyyx5KKQj9IeO3S6UggZWU7M7iDp4/3bkZIInIm+9/TI87Oy48EjWr1TvG8ABTFBGEzeHOOAzHkTEf2MV6chaarCBpYTFt22YWW4O/8pdpLmsfAWkie9sYKV6qHbRobtgp5AmORM+946V1Ec/+alE4WYWRyRU5N7eaMm2JzUACcLVtjfFFLKkeLXWZsybQSl3NUWtIrjYYLjEI2qdmycYUKfD24RGZ9NJ9TV+oyUrnxSoG+wnv2OTqe9xziD6LD2GZZGOv56ddBhn2ibRCuHqEC1FH9v93zNTSnMGG1I1a4Z3yuNtCzq6VdvFktApzW2fNgqWnwh0ickYXLPxzr5bZvqbyDK2tHHe9xbTFWJqbv4Pp0LlOJaxLCb2M5Sv6Xx2aPpeUniYPLBfr/tphST9KBEi5a/ncLGJInT11pWAcAXiiTivLN7KtGnNt/y3xlW9mNugme/S/glvZ1/wtvDDseBC1rKGWajBM+GSLZFQAlpy9xtu4doMfHo9eVJD1xwfMVZlVofH2hopmgES5oKydiwRUPSJ9sqVIsV2o9Oqn1YxxkGKnTc7D4GmvRqC7m3vxFvpKq5PZUlRARLG/Wln1YBZv2F72eURIuTCxud/bGs2UY/EUO+ORa8iUBf8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

