apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB1r0O6FUWXV6zdHOuIQWHSuqwRCVtg7mcmjB/jhVEJqGWrTLL8ugLfC1pKkix372XMOC9NHI6J8vcyJHb/+O80ErdQUsIqYAGYD0mu9tn8eMKMTr1iIOTm2AMjpYgCES8gyP5vWJrvZ/5s3kkLjOI2VTFk7jia4gD6Yoz9LbSKOD5zdpKcbomdg6CoVcHE+XPzlaVntkQchNPYoMPKEid0CehW56BvYmAaKSX+QdDtkXDWLNXmHsbFRLFd4Pr1XrXdGfxhj8SWpsrcXcTs3hA/FfmGks8hef8qWAZxbfD2rsKhcFPapNqNoQ+6YhvzBgKx9RZfl9On9LLrVJaChBi+FthFqjTuSqCUaYpQ1VsTWzXQkNkzvdC+ReF4CaDm6fCIKshopnyj7W83rvvjEu88GNO/aDcMXbZPSJem4IHxmP+7BJPwl7yJv4zshpaGkOttnz8A1hHAlGFbgqOQ+7UgPWMB4qnNPE1PEuyMvXrIa+5sRTdrqUJBdkkwsKJ6ZUlUwssTuatCQ0ccoo+NB/HAMbPL1X1zkPoPZ4lcteY7Dyq1a7zPQCA/AO1GBMUrJoV62kgqlrYu2asiVsfbcMuxfqYCjdInmVLAqthOnR0AzEa4noEQ5HpUmgZsuCSk0xUfefh1tV+5AOUIwFYDA7PcTuGGbt8yf+ltObOc/VD4k6hVWadUMDHrr2AZWCaviVvglpg9Ti173n0ZMwzhDQpOmdLCC0spSiuSEl5sSZABI+brRuZgLw69G/eemQ/jGZ94JHNpoNKgREBRbUKMjfMqCq7ppuuNnZEHGO20GMuQYaU6CUWY4lGDOFmUxszXquRtYX5/dvD1wxJ3H7LW/1s7iG3yOLY/qyZ0d2nQ86rvgQAg01lVopWz4UYDZfdiouJ/M3G/xY7vLWQRQFaAhx46sCaG9ZB0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

