apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAyR5jL4cOSVaQpPrqt2fNdFnlrhZf1+FizrRQHL/7sHbumwm+zphZN8zZlu4HxU1EuhOfcSE+YXu+rFJwCmQOYdLe7fnAMv77cul4tIHaU3wVd2NMZJi8iaeB2RMENPc8xwQUCB07o7Zlw1xqkwpTsrPCOxAAB7214uKKVpFT94PTMoxEZnhHiRmHktTg1M/EhrUsMfPyTaY8EUpGgnjeV91PNBPFNnEf4GlDqSgQtCeVJCLSBdvqgiPYBPJXM8o6MPf3X4kgSj9ltPLk9lVN+7sJGEEI4K+oD6DN0mOOop18iW9+4legx2q8OqQYCdrl7Nd/Y2PzspfoGCllq56NEEQYJ846SKAb99sd+0jqHZBwMcDbm4LJRgz6rlG5UZTBZuCD1Lo5IeGdNN0rRPufxe9Tpt0o2bsakIJo5PMnAA93V/gpKDBs/g46BOkrMbB68U19uKoB65CX5G8u2mEtl3mUl5zaPPpIn7iOwzoOcMGDcw0D448U0o1g18Vf1j/ke8+YuQjcDd6o4CNUd4qnZtZRoV0L8StzjRASOPvzCeJLFxU29UVh5DpsjdcJX7R9qe8rn97lRiHZzMafLwUDkdNGDwz33oYjccNQbIf8FUoB5mnD85PTs4/SBSzCnbzgSGp52KEan5FGu04dlg9qoZ7INYHZb1N+uBzC7QXNFWsgVzTDwCzQVQW4KPq8HsPgCEhoaDInySxYiI7v2ibizfwIctAPKXn9u1drwks7t0KYssHUIRVLov0nCOXX1qrxEu1UqkAx2T5h6MnSIKILZQ6Ej8Xj0sjlicg7pfASDocU9pqPOEPUDXUC4+x6CGQ9EiWvLrauH1eZ/5iMw/Jqx69lmGflVFZPVNB/pS/XLhwHr19FUdI6bC0XeNLEaqhatqNBtmEkxbtL5+ZCaRAfDuLHjhQ4z
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

