apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAEymkGy9DMnZhU1Nb1PDZxpNhw1a2zvu6DzYGEnLAqT6/gj0JjOgiOsDFIdcp8GImsH1gmuJ4RamJvi0hy2uORoy5791NyKWBIeo7dwDIqqVw81hT8o2RjjUDsGOXns6gYEREwfqRIhoRGKIK4D8d08yEvNPeJmgiXSxfQVRPlgKW/OUqlYsNfwsaeZV/B4ZpfQkK/7cjKSpBRjzJIvOR0HoqNdf3Tynn1CXNmIKhDRxVn6I/mQZnuE7zJGBSPYSap0AlZfNB7SEMf6Lm0x9veoYVsgMu0GbbJZXTAxIabknlIzox3gBi9sF3FwZe4HoC3dZtUq/ab8GIzqxEs8g9oT/u0EJabBh4IzuY6MZw1h54juk+Ch+lw/hrTuPvzau74pr4jd1Rly0Row+Sc8kJw/3sJFt51f0I3y5ca8TmpdqXmRkUN/RSajfZ/ZLI56qn+k5nT+TcvYSJfHf/vK1G5SidwVLPn61SchDk4iYiyE0enhaYNn2fx+0wohH4xYnXRNZU66CqpizzFCA70gKKWOO9+CWp9BE6MwV8oB9/TipNjKelPuMw+0RbbWIUdckCjk56bxJ/32j5/uxzHZ6kdVMtdRhnxmshUrMvQAvfbBobleACIpCH2vzWriHpFUaYJuhE42U5t47mBAAraKx1vsvFKm6YVQBsuI9YS/EXjVi6RraV87GIU5qEIf70FMzjOOt4SALiIj+wQYWwWdO2IJbTc6sj5h7VN+N1cV0ob3gMAbJ0aRYAMSR8m6ohBL9X0WQ+PZ9VrrtBUgXPgduNKS/lPIJBsE6KcDn7Q5aQC+JuiXKCQjDzEbH1T6XGygKd/Wu6Vz2WvplawPcXV5JbxtvVEMjUcjJ4RckHvzNU2gF6nS5VcN59d9X03Hh73cmlk7z7a/YJfezSO+U2hWiIptY8MPxwn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

