apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: longhorn-system
spec:
  encryptedData:
    .dockerconfigjson: AgAwgsBELHsKQmfFVmIcyB9d//siB4V5UdHxwNbTbcc07YOEkCw0Jt5t9uJLlLcVeT3OnRY/GBwtJWBtUhLps9F0Ym2RPsLtXCLOzvYydK1lM4Lf8oAoEu/aw9C8d08ZZ8ojViMbGC/bkrJww5w2u5qkC3hzih1jMs9SQxchY/ML+i+w+C7/THRW4DjGDXNkSHsaVvbKqI3zK2MdMXZ4PMu3jTkKlbElBJYgjIdyRt8GZK+qhXfzZBpv5hh0q+7YImI55k05JBBY2KIn6TLM4L5wXDSD9ZUYDIy8WALH6XdiSQXV+wbw59rsRWfpN6FRdE83HFa4xECfBhqrMZzf8w3CWhRDa0N5rug3WMP1Jtz2Y6VQ81Pxx0BG5xiifzXyi7PYnfG7fyZv1T+22Kqji2uRixi6JU1aq3hzINqYheT8/A5fzZtQVGJYRY4Q26TQA6UbhWJbrGPgfFDR8DhVsBH2cOJ64vQRHyk1tH9j7DVurF4kiqx5KLPhcgx8KtUnMqE+Kr4Fjma3OQrOVNEZ6ngp3lJlyFhVF13pZlZ67JKMNIJZm/g5FJDMFHA3FXztpM2Xkpf44pW1VBkNy+gcA9MpxNudCKvBh0cr16Z4XtCHyK6lqcEJle3WE+PJIaUp4nCI8dBmQIKrPtg8TZCbqekqUCcRwApP3UDfgUK3i//tmG5JhWvm7EeQK6wAt/3xmsNeppccNFkBNXgwkOYi4J17y0NGfNC2G/YI2t3vCD3AgNCdc2rgTfqTJnkX6Z/r0yH/GlxKebPKQtYjcFZUgPu6EXH4dg0SzNY1Y6/5snwaDchgMDabx4t/rSWbHNMGbQAte9WFvBTsSAZEO+OJdd/QH8y3v8NmFRUf105zl9KvPrYfBDA5dEw+hBrkG14KHFscn70o/10HRzFw+KhA2rWp/GVX9YoS
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: longhorn-system
    type: kubernetes.io/dockerconfigjson

