apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgASAmsImqBUhUBL84W2qb/FRxjtxhsVqst2HK/tvPRJ8AolAGSKk9ZPln8NCFIl/xTr5+CQx661w3a2TOfctV4KanrfQj/6tGNfEYvQR9nSNlMxYjHb1V1UszDZVM05XiDEc6T1NhRSZJf+HHxWGjY97kyty66mYkK5rRJkTQjsicPPUuizdGcy4Z3zs8krQduJL8gBJXfZ1NLbIoGLGJpBJR0KHpKVf9clQWh866JhLKhjWMvZbo1kJGzRRrjftaw33tluhaugXqa1vEp5gu+kG7EulEnrUeBGIxEo8UEm9h+5SEEVb8DiKlLngt2pZWkU5HylnPYu2uJAWZPW2zA6gKoSOH3i/MBtSodGWJ6tRwoxotpLokGdHErysYvEM4+H0XvPT/x/NyU+mpjGu/BnPTBvL7wT1QM/mlzITIIluInuvxjyF1/i4ruA073/2xcGi5EMQFY+les4bU91JQUck6g/amUmF897oB9QOAwfa1q598BNo6aPHg9VKz23aNBWUR2UxysQ9Xre8meqnmejsQISjpWP+Max2H2PhqPeFDV4TnnG10hs1e6Dj0kuqoPMOvYhHNaOqOC4UpiiQHo5ogZ9VoMsmEutRbztCm8Fn0qbFGIAfwdOKzlXXvXqxnCYteSvtxd4tFKy6bcZfLN/TGxXQDPoeaJpCgsPyx8bWxsn6zpLGLaFYwdgFn7UtzwM/L7HL5fxNnoQjb5GTlNuPgWegYjLadcVhPhUl4dLwP6xO9OqcCHGrgc3mHv7zR2gdIRdX84kL69UzwuUaLBqgGGt1iWlx75DI/oaN++4SmtEbzckXVyBR/vTU4Ca5uI9NEQ+AAG6QTWefYJ5ArZVOo7QdyMnHliMX65u1NL6EPgEInS0PXAjgOk82W3F0ErNUCMkINxyGcwM0vuGPLTtZJq5hv8u
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

