apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBOXTQl2rF2g42ttV27q4W5QXar9lU1uzmXK2cpS35p189EBkEJvqyBBmpdlSHZlWkGMNHOL0qYU2iAmbJRz9Iec4EngUX4HjgTpYtRqgQfEWPbT7vFbjvUcrU0yym3lu/+CydEW3KxgDJeM5N9PXlgYY9kr0N+azlkm3YUV4s4YPXx2JGZMxs6NYoYnuToAbW/I9AvqwfiMdDTSoL2/lyMX7N2ePIkjiehXlmTgvlVp7Y4oHYAyTe/qgZ9QtgCG/ouS1DFQf3nRO1c05wkssiMf8aARvNv7Ig1vb5tEj+QIjQaEV3+r13m1/rRUgtIK+L3QK4e1dYafGRGgvvKMphMNXQHGg7+6pdV3zYSRbkDx3bjfFKsp6PqQ2vX77L5QsHLrpbnfMkmsvjOUi8oXY0YeB2o47sJr0RJpx0xaoidK+rfoRMPQR/bi/EsBqprJPvdQ6SB7qDoXecCT8I0PN0W5yMD8oqtEpmQ7xoVa19N2V1YzwJNKU17f/BGmEPgP0WF/G9vxWiDhr5PKPt2knwMSZJASVljNKQ9qhDs6xTEsGeG/b2sEjVqvWFizSqMtmwwn2jF5AEcD0nhcwEu7ODOmO8LrLxkJUI8ctQq7K5+teOluQm88yaTU4KfGrvKL/nR4r2TJ3zZLiS7myiLYc6tBG3sSKIt/+Edw3roFCdb0R4xTjcwogmd6sYwHNzMqQqqTIxwynGFO7PFumzagvnjvMpFfbMDeI8SSxKQRMx/RvmxBMpKUUcWQ1CN00be7UeCSTO1Hz5OAbmudt5lhjDBWm6FNljEWF5lHHiQHZ93pN+LYuJd0mutOFNelHmVIjdSBhZVr+RWhLQpbHjcOpu2KghPd8LybivSE6oCi2/yhEtfWVmGGi/ZXv9H83VozZP2Hmjblk3inoV1moYx9WonQeYug5UP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

