apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBPUnnlG2xIGELx2QLrYc2c7FTFu2SSixsAxqIm4uLic/B2etD9lOFfqFjub5Kg0Rf2lDaiW3rAIiDcKK9F3sRRxLdYoeibRszqAMbK1ZGpg8UNO0cdrD0Bu8rQCaxJZN3rMb73S9Qpkjb9ubB49veqnB4GRcDpPYJ99TojYcFB0qhn28rBv3Crh4Ix3k4xhUAuRchApQO0P90INFZOjVkl7lNZteimgtk85PEBAY//5Of+9Dx3W+ZYqxVFPGT490dRbsCkDRcPnpRV+QyqfCt71YM90J/kBh+faaoebSevo0hPWAGWfDGJOO08qqBOScZRCWb5276XW6YpLVxITNwZbRCtYlacKRxuPSjzVESDMt2uzs+dV+2zyi8h/VjLA2FgBG06RQPqqvYAjw3h96j2EpTJcu/b7rSGjEX464wIQqDDQw47Qnb64320IMPkVgBVWDOUmtYS3XATrCKGaek0p+0D/33vNqEEZwW6FexF+8pdKuMkOWrGCR43mxT5roOthTmgl1ykW7KaRNxhyPxe0ZopZUwbgymzk4mhzmBk/XMnq/CGJiwcEMLxe3oEDP0cyKVqJpYgcSJ6S3Z+Z/2UAvg2KCFb2YqqvDJCJq/hR380NB4lfqp/AmB/qgt+kR4RL+tZHHmGcsnDSZcGIGlJKsQItEfbkJZQJ8r+z2omcNaGZetRBI+Lh2i6zAsFuyuBuWuhRCCITmiX5WVh9nvT+j1Ry01+CgO4MnRuFJn0JI6D/TNZNE3u2FaBzmPenrCZNRHSOjEKIN6VbCrES6kxu8IXEqIxTOqp+i3NPSiTuy7/l96yi7lzkezi0ifEAfvpcXspPfCp99q5q3m3QxGGlgMW5YsTJEGyXWvSdH8wFtg3NisJxUAXhAKCIFpqRupt1NZyRXvdc4cAQZL2Swm7BiaOpBF4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

