apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBHnF2wEuBnCrAPeut+FxItWJpU4cQOw2I6uoXKkHDRYbToxP9jRt0k7VovO41OwgZivy2083CxeXnvyd6tb2HcEPCT+vWDPHgtavkt2JlYcDWwqbBTpaCAu8ej6RTpjgA604v03/Ub4qNMriJ6K8XGnB54KBoMkw3b4dDv/DOQcxuFa8oCm0JH43ZDnr5O3G0Tq8thWmdCNBau+IE27fDiQoR6Gt0Fh7nZLvaxh/8CtYKhy3/A1rO6agzG0tARFE+pl/Axq2EugdbJLXG9fJ6DIlZsQPcBINfBHZfJNVHEJCo6y99hqHKr+TUknT2Rj0KInGV5uRFbU6Zxqso9hvfk9GR82BM/lcuuKnV32puJ0wt+VroZ/7qSNGWa4S2iYMaYj1YGHAY66oJnD8GEyE/SVE8+pe0HnE8hHMOwbONAvmP2okQp3i1sDB13RJmR2yQdzo3y5bb9H/5BBb1xWDPapv95OuHdYppVTX6ixX7ZN7Je8b74xq5epoDgu0VV76cF2duWliaXnIlpyFdXQEUwcv9VdT7WUSHH2cRJR+naCy/Dd2gOa+1cDKnVA17Mb45HNfzXwsbNwy3UzDF9han3d8uqAcJAI8n7udUAftt8kK4N8LQWXbFYN+oy6hc9K946ChaAPnkJtLB/sazFqQO/A3Bi7LVfno6llWqh48Vw61UPRORrJ7U6yrhMhACZWxMRggkTr2idOgQXACzYfe2mZPVBRf4+cRntLML3F/8fQ+G1EsR1cmk0At0RjEZNybGy7pCAb5asNXSnCzSAHy8tz6Kw1U+h6dw8SEu+pYspBKYQMK/DXRj8+SiVLUtiTz9qEhms4E8Xiwn2AqiTrmiLIUsDOpMw6aeXfz6EIUgQqqX71LQG5/mvcThUbwQ44h6NSvNK4tweoohHRRUMfnjuX8iFacaH
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

