apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA9F9gGl2g4u86+h43synpO1ixsmfUQX6oiVd/KQkWOUvZqXqSfnXsSoELDEqvDv7NObPp/2M0H5xDRCl9wMrz5oNAiRrMNbn2ajusZcTnCfvMSsjm2Krpgf9gLRh6kb87AzWNDL22tnGxi/ykzM12QFiym44HblzGfSVwMnUznEinyDsJJixs8zS2sKuP1Os3twmBNazJD07spnDw9U6u+8uLMMvVm+9ULhhJJlPajiv17x4aYMVk3XTFiAvBqtMMcP4z068kCgEJyBGzu4JVyS4wPwovFmyWx9TTTIqSzR/lD91avsyES/c19Iwso5tu6ebeAI33gWcCGIE6Xug5yrYNZqrvLoZoctyEOOplnB4CzvDmP0Zx05/PlHCj10qo+GkjSnZ5EZ5DEgexXdoPhHA1LiKxAyQixuoc4gEVbcgU3kveCyXbHOf8kXMfLO31pA4fIFn6l7V6Zz9G8VgAqTLMDEgkqtbV1p1AQ5CPwWdJUsz3YsVwQFUEbPlJxMOT6HGCiG49BvuC0VUdP5M3GJO2RnTh5/AZlUJxUmWYldE502vrHvLa5qbbtl7/KxU1gVWeWkeCW+1L7/QyUlY0zG8sgHWboXrwb8o/phdmaRCJzMqoJf2468sjtctipYW1uXjFG/pyAni7ZUwmPKjsNIL1Y7MeIa0u6CDfy4+lobfsmzZx1/ZTzSCIRVl4VZhFFwHIcA1fpHdq3794Mo1GFa8HY7g3NGiZ1DlDrUQSzqqkXop3gnPy0JhafX3tZGxzL7l3HBSLx292rWWL3zXX78fqrLQ25jYyuyu63PqwdrZuoe+EInIjTUaMIOV3wplWwiNOnVjOO1h1nZJQ0wqfcZroa85DT0Brx5l3omGftaYiNGeLWv4Zu0E+Zy+DKqEY8Sbi2I0gVsyTBT02Htm7aiSdIOFA/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

