apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCebkgc8FC/5hcv+7vw0yKWFOD9jD3HjjCbBNgBlZ5l+yDLJAIAJp0alzTXr2KhVFCPdQYINVeyyVoR9JlkJUTiJeFSQ6yZkFznd8ML1ZogqiAMaK2kMeF202CHr61U0iWFV+HxQuI5msezUSSoY+bhQAs/3abTaFuxXhOxVq8PIBfBRZIRlLlworMDpo7upu53SFp+2ttj5OfRH9g+vqycsjBuRFYTGO5cOgpkvjEDCZ7rHOZNw788Obzkr2WeYQHZhhIQnoBCP6LXK7NtefvAIijAWijO8oPLP6RGHYop+LhCcua87NKsQnZVqll7nNIio7R6xubS34KLb0EuXMuRM9ZHdZ/qB9cL9ISV22Yx9NBuVmhtDnBujHPWeB5zk4yYIUC1EISJz7RtIYkMt7C4tRISUkOLMWtgMaW4TWXyjRHLU8qIpPVC8oaNL1sHPXmK1AZHdhRb2lRdecNETqJEeZg2fdVpV5V/MMd/kLTdWWZ8PRgpXgX0Mh62PfiaJjDJ/n1U3KTgjr7QnNEfgPrAam121VqEAeL6rf7TAsalP/HuF1q9FfoJrHt1sfn2tR/WFZaeVeCdVwRBi0Rqq/VfBlLFT880jkl61qzl7Xe8h5BvQT9MzCVRyk1Pvor7oNGVXT5/f5BRtmZNPQFLi7vY4EqAAULvXJ5OJRE3jUAgsPS/y+ezp9wk1raFFQGXwXwHJFJ2oHpu9FdO6+nd5IYM41SlW5QYhov2NaYE1hMq11nm+cYZAW3RjW9lXQeQg+Oixz+P0AFufPhPxA9toF6RnyocEkv+77HWrj+xBAlUYPWeHE7BHVZALJznbnyaUDe4zGOKWhAGnJQb0u/t0ek0Tnsx5QuG2/6v06uV69w9hB9DlXoWEa73WTMV1alc+doqD+C90ngMS5TfCJWSwm4lU+6y59CC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

