apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAnf4WNEx6MzStOSZDg5w7l3OwfDPhZwShQaVbUjFzN8GkeuvW1iJoq6N/21DpGUiXsOFmGU7BdlrqQGa3eniLRnewARcDnLGz/EJKu7nldIsrlKNMzyE+hKEh3ApW2N7gyxfUYGLK7ucS7IQXWMd2Kl5tBEAP0JZvGHLhVjk0eLewd4dgknqPSS21piv6gll/IXOtIBiHXbJu61vumOWQkkhtiRypbcgaMj+Pv4YGHhALwhH9KaVKQjQifYCHIYiosDvszFIxLn/hIN7K0bZQ2IG5PPl85BXWnc+OoLnZhCBfUF9YLx6MTGjqOhhQT1wi3SRZQprYdlJA0C2/hoShP+q2RZ32X9Xm3eOMQWnA2Ygdxkl5dfjhVctjF1C/cdBS24nMvMx+PiQRcoVpuav/tCRpdYTOli+asVcLTxTIqctXN0y30szkUhS8s940mbwgyFRhQ5PAyPCiB87UypXn+tWezFv2Zj7mWQRqYAMlyh2eAzAjFYvx50nZY0OFa8xhY7dAus7Vp+SqAPZtLkp76zaPCZJ01QjTkjuXpLh/jV80B0tGDx1YWrkAMooOrBvIj6XAH/IrgrV1//ax5MyOyprDzP84wfk+GpbwplutvqEbag/EGiIq5PDj0IMp+fxrv2JueWxzC9G9+ReGl+ldyNSJ3ydq7f6xpgqc9RDErEXnf0vB7jlX7q3EGAwq5mGNY6xxfiNBo6JA/SGJE/aXIdgvk2dc9eGTez7fPPnsRi/iK3QqSvq2+pUrVEMzOIdB5JqhBnWU/ydidPJ0wtBp5lCKLYmxRYLaUhuKHFTwD48m+Z65CbiCfK/FtIO+/oHvd9xifDVIanKw+XilbOXqP4oUAQMA7agmEpmTijpFT/tfS9e/WqGmqkFNGvYk1keP17jO49RDN5C2/HvALpL+vuckpJVY/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

