apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBY9QAbAaZQu7EbmtweFtq2WtiwBiYeKI4EqRfatBApTD8UncPpXHymXK12XD7SlyhDuI5MSwZpvCpUiHBbwTDzG1ex1ksLno/HKOZEsW/XgKSHFrhItlQo58eVnbORA8C/LOaWJg9IRygzuEQInHjfIjUgXEXlyFCJew/I6wsoVJfY2be2r4uQAYK6ELCQ+UIAAQ8SQ1gKPmvfoMMq6FpBAc0+OLbojkPihSQdq6ND6Yxv/KpDhF1kB+eSQvT7uUd9LffmZJBcqHcsOEyhtBFQFTDpEWOcVu+thPqiDupwUVz2VW5KW7TyxfbpGUT7mVf0BUcztE8vhstx2eyfPmVLmo+QMEdaDxDtByJlC07kczk82KpkVs+BIphOMIGG3NZh4AoYPp0fE2+yXxVgD+EW0iDzJ7T8QpDvT4tzFXVhyjBOCExtpidhBkNWIMIT0G//LEsGPSyt4WSv4tk4seBWmILUDjcYUKny4pfkgLPXYmUmgt5fu4wKjskEH0cvACw7VbDeRLHlsmFvW/53mo3oajYFnRzrR5YjgJ5jRk06KN26+c5tmH7TyVKUJ62bRUPxTq9oUGetYHcHb7uU++jbCrWDU0duD/YJXb/0Xs/MXMllYS4Xh+URF0WBKgW/U9LlFEM0Fk2JPx6R6E0b0JXD7/QSu80KBfteyueXh8naQcQnrTz4ns/MeoDdSwGHj0zuxjM/h4yYD9uctM6F/he+alHI1TLezRjwyxgf0Sal7167JbjwSrmZRipK2fmyJ/o8f3TT413J49Th06jQmddGD/sAzFelpYVu488rzN2IkEo5L1mSPHwWqYvHUh3zFIqNSwomQ75bjRsiKGi0sCIxMAVl+7KaWXbVwkqH8zQjbYXZMdWGFlRpa6hrr/qUTSMTn+lfqxbCXJhaNxPJIs0ePjEVGGZu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

