apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCSCmRYNuYveDSqeODWAiSJkW5ga8sEClrAsa1JqufIybTRttdsBiNj8lQq71FpaDvquLct5dU85VsBhj3nMfOrXgUfKxw9Y6f9/ZVJL2wT1fEOamWaGY1bsurUvCoT0Y0XuWz8FTuvHU9TBsGNhMqH4JL+sCPP9JE38yKnlRX3WIdxfVuUSiUaJUg5ey1nHK3EvOfG3BUkebtV3SHq2YFkzH+tNLELcwF91UHcZ67Dlja6HL+cXG0uITifl5sk9R0jBUT02b5N9Vxt1roA7Y8b0B964kCd4jFsDlmxjEz7D525VUuHqlPdqeVW2+NCFuIE+HTXqEskPu/Dc3TbS6Vsry4jqDsCEHudo12018+hrULm3L93edTfDW8tr1S8seHHev0yqtvHjBKOOBYRYFCqqm5x0hmpLL9VBYgPSvr3KG9SzEeKoPFpU9YexfjKM6ElkqO7rVKP8ZHwf6OUspuV89FbnAGwEGSGrck1aoP4Bi1fXKgyV1qStul7Ww3rqqphMb97+59Qs1e4Z2RsOhkk8oXkLq/m3IgnhBKhXDOXNw7rBiYGpntmW8OYLC7UvSRZkD13aTMvust5MvBMVmNxIIaxIDH3iGeUtL/4up/Q3ONoT2Z37b6xBeZ20C4rn9M6oN2TxFdmerI655Z7waJKs79TB8Ii5ex1xmZWPG00emy9Zdm9w8K+eX8lIddP1q3GtAlGWZ58or8HDUAQ/PaCNmHSbCTJh5N4tFKyxyBxi8aGMevO15aGPjmZlDSdHDtPpDXp+cpD7x6bvfZAsvmqm5ngNy/lVei+Y4msOZdstwfzowntoKPmj/QbrOVEA86hksjmPCbVQGlwJVo0Ku13UTXa2MHyLFI/UeOHYJRSKvbbumk/s1a4/V0KZnVoj6yYKuLgqxtnMimfYMmSfAv6rvShzSV+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

