apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCMQQp5ivjUZtM17ztt0u1srCEkJ2eVH/aMGFTxof1MS6sV0NtvYDtHRAuwnSIU713bKqUXmwjwfTOzIhKecxBT7VRTPuNHtQNoFKHQOqZWHtA6jc19YeAgWOpmp1ELF8DUvUbrLXeqhnfRLO1Jq4Cmqr6YD0kEzhn8/g3YIXH9SZteOR5ju9Hy2GNOMPS6ztKCzKOGXBubuOyZ2FDLnzQsW0as+6QDGtlqHa+lueNuiypo+FdE0HK6uNflW1IRY0m5uzgWRsbpuAFASSMrsLDFUzi+gNNh2WTRvOS7w9F9UaR/GhR2NtEARzVduTy34y5dvhdy8aMhHXs0Oid0MG5wSgwjOevQeiMQpD1A+l0RkEbruI9VsH6/Y5anyUzdc6ElqPB7cjzP8sjCOQy2zIHMyUo3RPa9bZQdVUNhrA3+vZ02GndbcHq0PwLtsQQbpg6ioz0mKUOiJKklWaMrmSHxUJnmFxiYXxhBM78nu+X5VuT6iCtBvu9h6IxXX/tCMWQVvkapXlsKt3/+zbcJKK3cHBfZo/QSukA/guhWrntQNUdD7LdY9jeCTjGDGNdtMOipjuWpdBJjGdO2mypWDNloQIMADmdxblmT4lD5x5Yyn8dB1QJxlh02+DwG3jejozdBKFkUXvFqrbCtPxT0Q/mqAa9DKXIl43NxyTRBttVl2FdAuCX5KPs1VNUsF8au6M1f47KpFgINl8J6s6oXmXq2aZgQaKzEsAp1AtqWSl7Amlx56NRVuE+D8u3ehOq8Tg0FBtooF9uMNMAKp/XYXxRxJ+6wigN5LaGhLcyDEJBpGMCcFLWJI+ea9Ht74cj7swS8Yqnm1TSax7cMsoYKgMXfclZYhh9q7D5NC5jT37rK6U101PghY73I1gxRtXV6oykQMIk7Nd8ZXJnIOTdTaFdtLL3sMajm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

