apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBdu+1MJ7DYIDtpf5tUyKfmHao+m4l3NAit/ePZrcOS0vr6tXyexbUFWYKlqsHR7P1xAOOC9rmVP+gx2UD40IP7IYAPlEdLcCE9rAWDghhASVv3Ph6g48j5Ev8trOFlWZQn9ShxFyMAKfHwn/2eLmXpT3dXvqLplWfVdFsd5ph94L89tR5KUjoN44tINL+yrGJrDGFH2yUAIegEIQ+Oq4TbfqUFWdB8yg7nh0l2lBIEbNs66DsbC4Rv9QGiRbPg8EcM+5DMIddmhAHOoU6mJGdGgx4QElF70IWaifQQbzZd6AUw3Ndd8PxjqMQiCh78mm3iiwbQ7P4qY7fdoJxIJaMi+bszSAxDOsM9wG0W25i/0dRlWCysMvYKSthnEUkIECmeR1c07BcTB9ZPMFNfdz9MQQsUNl5abOuMBp8MA+YF1IHIqGykR/KYw3EPcFXw9EeoCzTp1qrbTf4Pi6LFjZBkWQ+eeRoEPZ8HV/DEo/9lM5MEj2t6OD0WaWTU0Vs/RlAh+KaJngLKp2603URjHPqXpto78JCXxx3uM7hClexKP9COj3Gl9y8T4czfU0Xxk0GlwEZXzqJc9AYmIlqGYrFeiFr0yNKceEm/4GwcZuUNNthHwqIr4wlahOoGqDD/+X3pT22pBje18giRG0F1J6gCFTRYXaD527DfTOarANx8ZGEpTlo5ouDwWcwFzLuwtO8F6C+Bn198oUTv7ZG5bokzUeqenMLvW9qHLqBTcpS0c4otN9uSsGvKnbHdWP4/lzCB2xTO4XaNb0RuNvzyEQ+imhS3iIyYZEor4DrEMU92adcP9oiwJhZ1qS+etkR2wIPL8h/5kfYgEzzgdqZCWJ1uOVMb9xkLSnzTG8ag4ggpiWrE1vNRIqZcU1NaUYbzXJBDRmlO8zW/eTYQOd8RVIYEzK9nxdX2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

