apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCo3OWqhWCfZB5q5Apyyzglg7V5x/YKtNz2ncwk2wkp/FyIOOPgJich3WSP4snclyISyi9KdM6TVAcWboTZGWEtIH6NTianXk3lQMQvpPTfy2Gbw6fMWeW3D4IvUuxzKWp4cfkxpMrDBYgfAKt7YRR/08K5ueNncCkwbDRI6CRilJ9KNe6gd6xIS/AjhuxnTWe3V+gZZwMTbIq82JzLiHtGfq0EQqerpjQ4nEnXkI4iWOISKoWSEa1vshxEG/J0kr6kzJEelpjdlUA1lyIu1ru/G/Ki8gpq8lRNV5iA0LE3kMGNjJGRBcxn4aVZdj8LGzUKBdTPJgKgABWUj0+0J7cNKuYMutPWySAOmpQVB2H3czM4Qb5GW5dm0WaJINeANFt529w4r2/e6HA8xEotAWkbZSKIfpPSwsqz12ne8Rcj+Dnj+IvKzM6eVLUlF3zK3PluAEQClaR0SJaVblVo2QY/qqMDZ11KxOeyoq/aF+7IwLLFrl3lIddOeBp/nN+6oy4h7y3gmXYsl3hQq2CVjGuaFiGpijY7C7qoo2OB6Xyk441WvrletBVX0Hi0CXmSmvbqgdN1IcVwqmeZOi9isKTn5bQN6YcTVANUC74ZmsgTwCtbQHmi5G2Hb5UIzCdSNcnqEoDwI4WELfBuGPZUrMpyNdOplB3jIrQoXDitaa+A5ZEMSLN9FMCCcJIzijFPxGRLN51bC7tSETYV7UJbjAc32cku85yNigmM4V8e7zWhb4JqL8TeSaNJktUBsPCQD0PKkAskwveTQWc+5Ju/4KtLdaIV7kevrPZkvC2C62QR8F1VwIRSsi8MvNsAgLK3xoG96gJ1lpMPmwBswJcjUe5CdO7QDKmuhDcqQcrUwa6vQi7upmgFk0saBGYCcMJyh50nIljiBOA3+JXqJX3+ARxpZEn+8JEu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

