apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCVMgvje86tEmCSF9yKB2ecfXLulO8+I+Cl5F9/pGPq3eXq/z7LKSACdqvAbCc2PgWrqXKO5Oayg/5zXjwFONb/kDJSAjPWV6KMoCvEgVguLhUvZLj2fA7hX0GhotVWYH6cDFIxjNsKDadP2XUdyGff2mhGFM5PEvVX88x/1ccSo4TY1RsC6poVXXmlumWp78LVVSw6T0V28DvTFqBOviWdXZbKuTZ05sxMenRH/7EJx3zaBuOwS0jPeyJyC9yuH3pK55Kh0+eMM9p0Pyk9PL8c4//TCVKkVoQbRRcUspzj2dDOfBYtkG0GCgIUXKuLBzGfs0b7U+F4gjxKDRZciLqtILqVBXpkmPBujKf2uuhd5uEsaWADxSvOdoOQhgpSov5DYE6BXYy+qoeeSEddZ4b/ZR0Av5HseJjVsnLtE9GiV75xk1cOcjIlu2DzKUh2da8DzxZMq+fHBPa2H8bzl+A4Q+6YUOX1chjuttwoHzvvowOR2uGJH3Cx51hbcopvzfB4K97i2QHb3rmXtACKr+4bZaFWLPyrUkL//T0fSX8FQgAk93CEIGbaYS4Jt2x8h2VnLtJgWXZBBPZjEe610EHziFLEvbdx5kHMvB4NzG0QsyLjYluqsmUsze+So8RHG5RWBff5S5xsEzUN8tmHvKdm66oY3fY471bJKXueDsyO5qdTM155vP/hRrkyoAPdbxpggmdCJiYKejJiJq3PbbLhKMtVM4ZKN+hG1LPvBpAJ/IhpOjjBGyyPmxfYhke+Sak9RB9IAUwQ7DXWGDCWolEY5O9Y1plP6O/NrjX1BKxxSXbpDr9mqhliyrZxzFT5TzVAqVECdYt3Wz3G51X3ohjJmFqw1cV598qFlRvCMNbwnMmL0Pklw0pufU+yNe3YuKEE8eR4p343Rpxfdd6QZarTy4P24bZQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

