apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAHbcB5DeyzgG+klnyu1daYhM/d2PguyqjVZF1mAJApXPSbVYjZSBrdu7PFXCU1YYZJJnzLToqvoKkyN9a48jdrayYyMTlRq5a7MUyTDGUQWEaS7fWn18trLtCRkWTFnDfzfKxgdm0Vef8qasLjx3GbfQRktmYVFnwuqMOEtMmTX7EtA44vS+F6LB5ARchNNFpZIjxTQi+93m5pThXxBmZOtEA838+JyE4n4mCSDg4QLvQtWQOZ+TpCnkQIkafep/CMI7jbdJ/wUyV5UofNxQdkXo1Q3xwB5ON3c9iSxbRBWXA137w+oxbjQubFs1hjC04TyQekP0bKtgEwMf0B1rtAlZomllENyyY7s0hcEcYr1hONpOcCKtiN+ZVufRJWxZo+baT+/bQA2FEoJW5b0/ODY2ZuX8ZCJgkxtCVgovSdEiTzZ4dHeND+2hsdXMcrUcBEx7S/nFocwqiDPqf3fFcuiHB6qmuXdk9MxAYl6r9PLwp610cPEl3DWwK2PeShYlTITt5ChTOQylO+YUJ3Tjha3PAwz2lMK4lTsepYoBLVlEz/v6Imo1uaRbKxKNYoZn3A1AjzLnqw933sNpuprCDwXua088oKJjFbcT/FXl+rUwdUq6VUqPwPNtDOarW/Udbkp1JD/NaqTsL2SUU5LcJmc6cz1UXnSSnBml0hAHG0/xQ9c9souuySkIvCxmVyP7Zg1cnvL7RcXPaMoHgkoUhjO3VYTUIqBlvwzKqtE85dutDpIOkjwC97qOAnmyccL5TdwbLZUeEmftTsKj9ahEkZl/IYu1TyOodbevPhnIrkHvImp+exECtfjc3mV23MtdLWLT41+c9ZIqqnR87dd9W0qOP1S0hTrIhyaw6BYdgJ36F+2hKaGsY/ZUDJvb4iZHaTgHQrkVoTVnmP5fH0NEmAEUU0THwr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

