apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgC69JajMV1+EByvDTiSfDCe4x7n7qsmiEmwSobZgLYenLua6VCCFU1zirAyravsHvnRBElr1mOYfzWiCnrr+5CDDnt3VL4OExqt24syjtTbic5+Vdigvus9t8aAxm/pGJExuWlZ7+iVfaRos+NmFEfAHS0X1LbsroD40IXsxFyOjpx1TVLMOwfw8qb1HLq7yd+vrTDsJGpIhuh/2bFp/O//nC1qd7Ci5Wa2IOnoM+tZyzIK/9RNh6sqUQffAJnlXkcRsvnny7UC51VWmxy5LlRUC4VUIyLLZ6vLQ3EBODJV9Qf0VDOoeyMTm605p1+9NI7b+0aifeeGqTQIpo6w45q8R8fiXCk3JF/3xEYT2wWlXQwMRBnPOPNRcD213cJ3OyNdWVtr059glX+XKlssWmW7mMvWq7XHjpkeorXIAu4ODu73H3Mraag7G4ADdkoABe/s6gSQ6sNrBzBU49lERuh51h89fJpkbVukkAO+hzWk634quUldzb04mJ97SIaX9xYeua5Ajrj3n/ZsVMA7KA9m7mCFvlKqq/05Z1paZ0Ux/UbtnsIXo8MpnYKMlvtOvuUO23UDAZqwKhqwY3o9HqF/l9F9BWPxdV01qjf/9Q+CYBbdDz6/MMvxXPVcCGVn993qqgmoAcGJJHIrJuAPzpfVu+NAZ71Hr7nlqrYXH1ayFyGWwRjMCoL/ey1KpLZSPqKS0EzdbTOL8BKc/R6Q0s2kQJjJ+6vvnhbILIYXTYuLDwDB1dy0OvYz76mcSrsHRPg0bnnX0k5ZV3VV/JSEenyMKNNTK6C0mt4xn4vZGBqCTgZ8z8qRUGOULOB4gPYCwp1igiISAljHKS1EYb4f5MqTBPjuqty2zQhpMK8ZjfZ5w0Bhvuplly5vxr0Iic9g4lHZ6GprJxyIvNhtCHXkaAIVbnVoSn7F
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

