apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBnaXgk71+/ODMLQ7/wbhMJaQYNqKKISltbMJEEVEIVPlK/CGBBZK88UHEeJK1FTOOpW6QITVos27pK7I1k8f4LBhx9WSYN1kaXFLiEip6W4vRSroxkkHbvjjOLH1z/U9jLjkdPU4ol3XVTSGY6/Z4s1KCXxzblst42ClMnCajGWLU3ClF9Q5UcX0Zq870sOd5kkF0jxbJgqW58K4/QxBIHpi2NQVSOAj7XGQbcTw4/1VeJjOQy5c1PjxNj/wtrZNeMHmn7pWO86mmMTank+mvBaIpvJAs7wS5kkIiJW6vzO/Bblq4cpnXLlcApOtsgDPGIhVVxT+9dKeSP1HZK32dIWCdMbXmzL2sYe7VsDJv1b2gfpHHYtF9+GXqWWmcXZyrrbectaD0JpwJuwVNwhQ8/E5Q3az1VTKP59GD9JYsJfj3smugoXN52Upr7uxQPYflf4zaXKgWHpoGB6k0XdnelB+m128DDOsCr6A8nKjiZFbU7ZMfrE1f0xfGqZ34udPFomdPFkAhSzChAiM6Lj4Dqiu5u8tNTgBK1i3fs5EN4yHmWbaYcKcj0Xj9AaK8K/3dOuh4xleiH4iWy+7ijdrg2ZicFSPpPumZtCz2sz00txfUW2KfOgt7S/zmWad9IKk9uU5FsgAkiCTwMM1V5FjvvmZIyduqOlLYxNc7QCctz2KZIwqoCKpaaJKHPqFpMP/HXOjjIVLSGUBcobinJw9oBUzwwXsagSL0vwHQyraYuniUKD7gAui3RVNSTBsomwPq03i3BXpszSrhRdP1BOh5H2CHCVBtOrkPNWlejsKNMjGUXUkRQR3Nd9gjmCIB3jP0q/kYeOdrSMBIAUb0ZeHFgTITbpZRGgS39ckawj2txBrxQq4Io2R+egvpFzzM4da0glhq9ZbnQAYEb0hx++2T/OrL+1lYc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

