apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCGMuq5cpPiw9OuZ6dPAbe5xq8xcGAqR+glShjNycPnwfZf3toANmTQiYvvUgCOXY3YddFH77pmLlp197aPGaMvx3DcP4DscwAAB6iW0zGSuF+5eVipRyfiFLjxeqcXlsrmO2KVUlX5oz0z+Z3seCnnAcnMcuqwUwEeGNLHEP/sn2PqXhe7KTWIHOeHSpq0gplceH3xGonZmuwtGnee3+BIYXa8KzdYj+8E4TX8YcH3m1WrDNjFSLsj+bAApZZ4kexpCQP/S/dGhoWGDib2FFc//TtPgCdEU66xiDcg5pwwJlV+vq67ZD5jSG+K0zol1GBA705UId3Xeac+fTavvL+YBA/pg6EJZj7CKjmf3R2XgpD95F0ZOYzxvWltBNTlzpyF4lyGEN4M7bUE8QgGjiWs3CtFDUNNaZBuEcWemMJaW8SMqqyMetOI3LjoPB3mamBdbj+D9fmJGlbtC1DzNd5TC2vc9zwthe/YKRmww6AG3NGHgxiWKLS+LSgUGJ5RloMXISdLJuyHLeZSxBkxEYQ8stxpvUp2ZaCGCUHZhzcB0bjOqM0DfWMxgrriuns+3KkLONZY55BnL0PEvnA1ZwoJqiY4tkbqAiQGfwVH10moZ+6uvbKNDet6bDOgucpx1xHpqihInUrYZsfUq8qPZJUjMW+jpn1JdXjEErZHE8PJxEZY4fUeqC2QWXernNZT+qd7O/ZegeDdNicTDa0ZdceW7Xz5lgdjMkaU3xfJRG/HGa/fzxno8/ZMSnmsTLYvKLeIpYcF5aKiTk/tWkWOPh76iiBSq7LbjIDRY9GB2IL9Pc8WPN4JI5TQxZ5NuPFkdab6rRhOdaCgC+xZ8UYC+1+6rSWXpPZFgzR44zogEUVgWbq5kjJBajNn/x+N0qJz9QHesWotM1FVliEUt6+/PA28mhaaSZ3t
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

