apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCqlAXav3Es0w5FRfzxObtu6Xxg+j8A+fx3eJVmv9xtgZmYIpjHbTpVBUZnMt1duEg2iqS6FWxkRMd6VLjqsI7ab+ntIEIfoviyHuavZhXhvipCO5BMjFEY+jCzFXMDAPu2Yv/Xu4vPWNmTV/5lHyf0O/WjhwWqoklshEcvQIWCN15XsSS2WH+zP4AhXEjbRYCH9UyFvN1gynWf2BJP1JUgG54uaMePlWA4z+Nae7gjgGB0lVQExCF/tDhQMgY3FHYUmWO50uCzkZ+src/A1KmZbZ3h5+3b3FmOdGmWXg4BboJxovRBxvS/Dt0Jc9i3Y3aj/qkpZaIWo1GNch2TZFQm4z7ZZJNx5q/wWZQYJT63nXmhmGtbZDvlcT+ZO9SIxW3ssvJE6+4bhoHM2gDZF+Kvj5S8qD2LhbCOyHVreJLPnM217c4vOyMzrEbf1qtmClVtCqv+U7IZmeLS0qFF3GzI/4Qf1qcOr7j3h9t8Su1YSeqBjNG5FpyzGck81HMY39imszdM12uozFdd6hQ1GcqtFinGEfcj8Lzm8UolY+QggrT/ZyZMcqV4QK+8djoNQ3it7e+gVwALhgvpGG6AujuGxlZQVU2xPnDQPFXEJuIWpY/i6lGZOk+VDluqJ5jIyD+rAzqR6V7Cz+6GciRNWyrofZDwJa6qLOAKKARaHPPKHa2AXH6Q/BDsv54Ss6c6rZiCDD9JhkVOYKDrwVUqt+p7QbVli5hEjSQ9WLmbDfK9eyQSr5gmC35AeW6YhJBsWybCPMs3fgiu/ooRQlmsXZmhl92KQNZj98zCdT97YT+2MScDzRkXX+/1eC9TA8ns34Qbawe5mzLQfx5K9LTfJWG5Qd5Yb8itRo7ZccJQqWONIDf7ZBw1CkY6Jnct+crpaQjiJgQLSDmmeTDaFFEH8VfmYSbnkdoa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

