apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAzA7j+glLPKgjEme8wlHxeVytNZpONPvoGaghqKbvBL5J6Wkht2PgXmpr0clT6awz1GzQNr926A5hx90JEdQU3yPT3yX4zecUIjpHJBZUoo/3C9ZANXZU1957tZNH2NWmjyZ/yzvYUP0qY9vK31+HAYY8j5Re1rUU475yaOaF7HkFgYW7a7yhTcAZposOHMirVr+wXQ2ZV+TAkCQ/V9fTauAEJYnezrUbxtjAuDzhcEATXJF33FP17E2GqG0EHizhMC4RtGAvTvjZYgaZOwjheBfoui4y4SwuN0aRibF14mRT7KlQ7imdCjMQB/O8Eb3WgDmyy1DD1pmjWRTBbI2kWANpApbxvIvEAf6zRuS/YDSe5feCAjVk6abNs2Ejbs7JTznyQaMA6czugivwtCYQCOnNuzMKaffTeLXi/wvaYBobhUHUVJxRTgKmvPYqE9OvStZsNFhbaDJ3W0qQCzjee5+jth0lqGEA5otaasS5PlPbd/234rL7St882L6+ppi1UTux5Edq/dxUJRHdBol267vOqBmaHMJvJ7suzO3YFlwFK4w9+7dPGHuDu3kv8vK8p/79+Wbx/4M/stzCpLZ8VUUT5PFtu+NOUsHu3aVfwS70EmW0Kolv0yndO7+SpkwaeTeAx2WFSYXkohfqP70WxpPquXcMTkMCo1KRIsZxcq3hiE9Bnzan189xhggv9iP7lvXyQQPJ7qvWzfc8t5kCtG0Qq0QdVFHM/YZjLUEesig8ekH8r6hwUN3DAqEnyszWw+gLCP7M+QGwGqO+XKtEJrplUcRJ4hHrXxiXZw/2UOPHCsiG4uQQrEbLI0eu943KwtBG3F2asXyBk5Hyi7mqRTPLosjb7UGWR53mRq3h6PGlWWoAZyDSlzth4HCGw5gq+f/CeTN5fzXsvbQKVifbMusNrY8v3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

