apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBL0PHe1vN/2OH7s4br/OOuBLLOYYIcaaAZDah2tQKXrfne0jrAt7EJlGwSEj1TPxKsDBIggxXhdREjJjggYR7cUXVLT8XjJDAnO4orXxuH4sR9kjBy9rVNtZDRKvA2lkOeZoXG5hAqy1kKBjB+mHhBl5RAOYYk1BZUsj/2RDx3lxPz9z4vjPbknStENc3s2Au27UKqffpeSGR2oyLyOj2hhVgYAPbS825FW1vCVhP706Hr+wZtVpR1pL/ZobX4LEX02rpl56CER+W98vlNvaq2gx2RjOSmvbhb7wotWUM06O8u6E59+HTLsB+/8VsXwOVOOCsV4PnTiez7erS7E3G6RD4K7zzF1Ju8p1WZsSKtbRK8CmChaqccGnLb/jMk26wIixqPEOi3yfDyAIcSZcjtsIwg+ulPR1YfMwZnAhnNCSLeF7th2MIM6L6BlQyqnENL3pG10pfjKuN+x+6M5ENZdMEKv+nGXa67jQFJDfKKmd7CKBRhmxUZavhBuNIM/1glZuKiLmo/lxlkbcYg5Q7k9uJDRHCVXuhkZZiS1SH7EuKsFlrriZslxBQtCMb/HXWzP7EixWsD5x7BNCSgKmno5vL7vkcqEsjSYo1kF5QzAJmjoIowDbt8POyM8A38fqiy+YsN+bQFP0K7Fm+hlhvW6a2RnUdrwmltu74DkYLf56sFQjR5G/1tsJfWNK1IEPHskc2ilGRXwd4A9Lk94JVvpyEiOHE0rYFwlfx8KVr4HFnPJKQaxs7R6b+TlWJqlGzyz3zbSq9BBlL5Jpi8exRdeZ1nKVj49N7JHZgbBbWsmP7SWRcLLEa40B3WWyfpqN1DSZ0wq3+zEfmmKBq08+jKzb7nTBED1+/Mj9RvG788qqj+yn5R+IT4UzIw3eT327YstS8qEg6fO46qG8oakAwbIkEJPAtW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

