apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCeU6lIdFmeqpwEb3Xc7rixTVBGYDzoLIZ+T3MnChZ1lnJvI3SP69IAWt72bQvowzrTGf0WbV9XSya6oLL25F1XBEKRInWdrt5cEh+KBZoNjS7QZPXT/eb2G8oEIFfIvYleAB195lGBkgqD7jCmpJpoNGRutFaRZE1MJhoX0Pz0hgToDcpBt7fCYAnN5jSARMOECM3czkAIRm8rdFYqlogb+Wjnu5R7SDGPi7GbDLzmuMwOUvA3E9Ro/gPAu5EH22TBiLk6FphvzRtDSPRtXCdYmW74qB2W5XsdfI3whnRBLqtYv2ORj7v7Q6ugabHOJcPGZf210Z7nXaJUM79EEYCfx3s+KibONQ3LD8WiqgmrYyE6hhoQ08QcbCtB5XaOpnVZzOEuoQ9Ny+4BkbiOq0wxVcN3O109RrHWVvtlgD778CeOepMiM/nSa4Fcvxl2Bk3kA0VzOZ9bqExPNfhpbC7NCaWH4XMDwbBMz6zwBoBd0aL6avLSOZIWQ/+ovXPuVIJD8IuEhyowHwvxNGbNu8nn/dF6Nwa+jRAjje1vZZ+nj2x/cTZ11QNAAi2Zn3wn7ekxhEsi6IHtE8R/vwwOsUs20FmhyM318BGSb3eVDoPko6Ly8OFNMH9Zf+uaEIn4hzVIUXEXOPJwKWJ0bC5yn1naD+zWqkZhhALNPEHTCkh0JF+oAumin4bx6QTYGVGbzbGUeIkmEkAk9rFSLwHdYFwynq10h23mk8WqEYKR8qG3nqUPebuKFbASjMAV9K7zBuwuu1wFtfRqgG62/mIxrBstC6cMP+iw60hyhL+2aNedsBaz3oMJO7rLU/wYwHS9DAqTt96ecRVuWcHNeuApVzOtthQtVDFMyu46chPEBapUBkcAcRi1kY+bmShe6Hkb0cBcEh7rSpBQQTK8zsDbiUbOYI4hUyyF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

