apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB/CIfd63IeGS4u/bkRcXA7ruAJsE5k2xiEm12J4SWIGq+jl8QoKaXlwT7dfp7F1U0nheNYpt4WOtmv6DorD4yMsdFAy394q192pK1u5qTB/b8/n/1cpAz2O5iDQAWHaj6gKJC1+765oPDONXUwCyhtF090PYcpQPyO/5xb8T5oK94QpJVgHnnvXyT4Qaed4jBzSoB2pkm9pu8j4D9E9LZ0TWsFTGBLk5owDpev3czkjxWl3gar9uz4u66QGTtGV4p5chZFwxYbMKkbk1wr5zz1tpAFvSzSlYF5hCtatI81B1biDBlI8U/NFsLFMHnmDrinVKDiAzQvbZoL6Fta00iM47o2DLP8+sg7Azaw03erff+K6f2hj1m5Ak2mwUW6LaQLtUMUm6un1X04GIgMoleBWj9THBa64UboWqQkU9B2u8GfNNvCpScwQeaQUck/AobeZTth12DnCou26Kh3nw7m9+SgYcscLtbMpxzJpf2QUUgie75amnd1a142WRb6lrBdZpxcVCjgY2YgUprVI4BKRDQDLKypDFcX6BwWvKom8SUDyP8e5EMtMkpGG1tSUqdptnTBkwshU0RS9zH0cNgEbpQZ/fuplp+1qFlp2+k68uE99QEKFInQOOiqbXRT85dnaislKQaB1GPJkEE9U60s4ARB5A1pVj3DrPS6E+J7piHLdDoHzmMJ/FOk7msD0QOYm4ol8odGvZaN0fYCS8bRIXyFrAFTkkZIYbDKZC/5KzNjEBEMAtNih1+e0o93j98zFxk3OsrGy/EssYkYU71cf0Ys89OQGfGs+qMGI4bDK9sLLSRsnzZlqgeFW8+3yWxEaHN3f/iOPZUR0kEUO4FEtnP+93ccCCfDnzDBrkMJsKr5MbnBhI5/QyuwNTdUpCR0dshJBriPCEMQoeF+prFawoQJIRYc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

