apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCN549JzKZZJC4vNybWhqfB6lGbdm/nxZ2vJx1zLsWeD9gCn7n4LlA3lxQ1Xd/PS4FggFtZinqKbxlF6bxfjB0g4sJ9sYu56SCoid3ty75+0qZzTzvo7vH99Cfb/r14NwSwWWJakDf8uzhIsepRDaqHMT0GEVPVAhGF7q2Lsvt0CyRGNLPAk9i3JA6eu3bTwc9FkBoFM4Fc5vuEOChpA+p1CwAa9Wi6YEJ6iWO0fxmkhLzQ/40xTEn0e77rz1aWpTvX8aM70huIFcTxy0pUapaL62R3Jp4kKpOmK0UFa6JPs+9FLyCJi4ZBWq/GVuBUvqcHlWzFDKVlUZZvjflO324ahP5uTxp7QadDBCUZi7VKmhI36aeBHR2ZpJs3YVmcRYmAF966/2UPB9OMSTRoF3f0YO7KvPVXPTwRQ3N3K3JfoAODgwOQvvpUWsRI1yyP8yIq5Hd16fh/3uyrEV6ZTJJVKdjnnKSjGOnYkzkscCZUYUAfGSMXINPOrq/Hbawex2mV5uLUmmEAAqWKr2o/bAGZquRqCaroz9uKwY354WMW+aJxpNPpikYmBCrjjQLBwgYG05ct9jRCUmQvmLcld2AiKUg40Lc63rWCO5SMmzEJc2bgpEf+bA2S1f0DozXcGUTmYFffwcfr1bDXHWzh6zKwrU/w1Kd+MYofH0D05O9GcAMAeJh9pkPmnDI3Njdej0r/og/LQHACT4j7fEqmyuROAHMkbygPeM7xtAc6DzjEPPgDKj3PPECxjOaaQDwvMAqgh13O+Jz8e8FyrfQNYaKElzRZMEZY3bxVIGbKa8WDVRH7Fo1r3YK/r81ONqsYWZQZrJOdZfFeFgRpUPkz9wWkg5Cjzvh8ui/D14X7cnQA+X7hGfZDFMqylo77fQhSkLZykVV3VQc2pQlmdRP6lZ2ltuomQjqY
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

