apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBDNnHeNmUoBv4AOkVqPRGgKzQeoroOroM2Qmv34VhI/LzTIxD532hukyd4EQ9RcEKQVTMbW85bU8zrat2rqwJ8Wj8fK6nOazGU9M7pg7w8O35QP47W5vJY4jb6LxpAMnYBJhjZnnVxlONZ+osxPFopEuLGZDqp29uslZkuJVlJjP1wXHM63rOJLCFRC47OJkHUlkyq4wFYn6eXjZi8QA4WkmkmHnUJ34HoBiJBPZ/MWOJjJNb/MYNZOWHa0lvc+YQlyzH8NyBJo+sgZ50LZhhvelViTfvQKyyE9uPZVvyWXre/vwT8c5U8CZ5zQhXsBSt9uvn+ZMxuhjZPWJn6tFvSCq99++hWmT454+by0fSx9ZmYCnq79K6bO4GxVUyppRfmay1lcwbxZKArudeBc2RKthQUYqDu7y9wvkVNPQIzWGvtrasnlj9O6FvHfZcEN/UweeGYd80FaGqhxTVBKv2sz5a07Xan+ClLOR0/L1/krhStq/iD9UZzy+ma5OWvCbrTiuzkTOLDALup3djHrzWav/La4ItpZUdkPN5u4Wsby31iy/FY8QZ9LAwXRQE50ycEEKln223zeq2Jz8VLMHjMtp4HGOrJUN+l1YIvFkOX7orjKLBcaX032MtKJ6A0yXlro0bfd14PQizcg54n8dNjIABqBV3ZlrgsgKJ/QLypHWUIq223l0GCB6tNtxGulMXWJAXVo4KoJb6DbqJrBzXF/h3U8a243De2N7Fqs5MNjwQK1c6P9p1a8IOe5hbqHbijuIj+2E3WCoRxtciyLhqZhgnRdmhfuJwPOyQcZ9axawZQ0S6EKZ/BmtxLTirXz5v97YteX5Snn6pPzNbK4w5yVJtBS3EsPevbxO0uLLqqQCOllwrxcsMPnTJTA/ZPdIVLZ+/H8PhvoYLTUI4Y/wSCFB8S2nEc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

