apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAaFZv+0NNrMwJ4rVmZ/+qdKwAgVQJawcsTsAngrfuGicEVfEAu4qUiuJb4JPL1HvyYar51HAJDSFatMo7R+jm36OUv+2rK3x8A5zG4e3czWgeJolYzNIqMAew5l+BnsB5leT1B5mB/33lQ31zrwkvhbnBUAAQAhsvF6I6K6w005XLWoCNgFuZEN+6xyZDQ03t6vs+MNaqxYpR/Elf0cUJPAMN7CvNkgiGggtCg1pm1YBEUP6fkGyu4Zwu9F1fda+44lBpX44m35G3/EfsCuUVSCOJt/ogZMVX4W2gohiGS6wY7aTajoWUuujLuiV5OaH0PrfqkvvNnRW2ak9pyAiENsh6pNTFvZFyBRNP6aZXbbgXitaC+CZqrhAd2/0X5Xxk920TPJqsB/FFcBlcwBLnrmCAevBpqG+V/5Vq0pc2CNlAAVSFcbILJFc4Cnw/ymzUmwZrAZMJkSCBuIQ5Hw5Darcz33b+M8ynXAd1J0dhABmhtPql2tJ9aXAGw7MjWyUCaoARD6G4RcjhQY4YFzRgC652qR9hQnBaBRLpA4yE3sN/C3YbPm8Y233OHf9z8+Q50k9m3HnTJs7dxsoy23pzwgsMu8zpO0QaFutU485hq4g8Bd14HAYXDDYiAhTexqCqWSnP3JdtBg6ytDyYg9yeSIwi6t5QpL4NzEA1fzMV1EF2KFxtK/oDYCZsYxLVU7JkfThYXbX+3J72VifomJI7HIYlovXyw+/hxZL5Ao/OdHC2HTtDpgiYLOyvH6B9CeOsZYXVFSvRLB8yFvjqXhsStfLVoXbCb2smZ5BETqEqrP02Ic5bNjlPkZhM9T7SbxXCpIZPDrbtWjboNrkSr7Mtz4tvrPrMASWZ5RQqcD6ELm6ypSl9lM+Rk+pbaELVJYtcFhi55CXSVFae/Cd715GVFWMxEUoR2
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

