apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCBdzM/Xw4N43ilwEEuqAdZr+I3x0cgTdPDF3/DFCKOPo8YypImJIT3jZumGc0XgGweDbUj7Kwywhbyd2HkTMBO7JAw0XiMWS//fiKAmDNt7QAd2Qt+qr1OqlKWwukRp6LhISPLFRGKkm7tM61LfiTjP1znIl/5p1zZ9rZwPiDRXfV80Q2FZQ+MXnGZ7wCJQi+5QoIU3NIJO1yHSkM528uahqoQs9N1sLL8sbplP0Z5qa2rDtuhilimfr411X4HkxSREWT3cLZJ1UyXi0mtGNP+4QG8uDKFswPaAyE2KaiqHRaEi/vd9/fQuZbFY9t9hyHnnsA3MZzatEDCaXGFMHbVVDw0qIVu2sQ/PLf1cQVmIxBY/ZxzVlfXOfKtY5aL0KzLZuxJBv3fPLYXHY1v3FHfGHRHNMv1dUnR5qB7FqDP+sxy73g6pKJG5nKWIOWa/nH/IuG/XyrHp/DmhFxBf+D1joG4GB1I3z8eWxxfOKe6OCOFDnXdNeYCUFlIdDq+dw8AmwpszdELUI5O/gMqyEhwCAD2UAj4yKbW7hVXsPdBm9KpaTSc2x6WyYqfh1XnJT0fv+AItcACLT3c6CfFh+0SGfglBQuhXjFtt2S499IX9Paj2jnlGfoyMo8ZS13h/NxBBb0yYVT4JzjTesk34h0Xzn7GrNYZxahixVPMXnRzEdso4RQUlc+W2PesyK94FCyLzve6VpH4etZUIrbgACDZL7uleByNIrWt33NCyKLRzD47typWXBGoW2jE7k795zZjepbevQsMSSDTJDQr9kOFFhY3Te+ek3YoQVPzKcMrETIan7lDMZzCPn8ZG0+qFxPeIEgj2+gV4oRQuESF+LlpfYITKLWbOPpgUcTy2q8j+f21EbZ3L4mn5ez/HAvkVY6YVpqTXq8UUCOCvkadUjV03u2EHwx8
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

