apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAM/nY0gxLjcxe8rsXxLgWJW2jemdkhp629qkVRRNEynhFgPe/R8WCW65i/Rjoie8SLoqzenjr702IokA8gF07tgyQBtRriEPiAVn6pHBD04qXzwejZwwjKslDlAj3627vlAH+vcelKnfIP0Bhk+se9XmDGefKqzr/RWyKr62jTwfPgt8q2kJgjnH7S2PAXkhg7SPanNWOpVscaDSvJyqf1Lo0tYrYnVPnVsLX+31800010CrdSIHsuwrGboB10zNDbJvJexQY1fUV3uCR7Hw7T+8Nq5jT3S0IxfdkUOlaqXPDVPFjTiwVTHsPjeeaxk9nXFhb/esG2aQiBMwTQthBdO5UCPjaNmj18dqHqj3YZQTvtZqIonTWauKEmi2AXOQ5XPrDZBl9DSQOUuINMD4o/sSyaYwzTJzTDws9iA2eAJRXjR/6mFkT05drQ9XaY7Bri4ck69s/BSonPZ8pPvl95jIl9CprhbxJVEVvT1/urCClM66FukVHouvmI8itHPbDvZtfphtOHrtOeSVdlSsmnKUH514k5zYAxIvZn+T4P7Ru0PC+AI9KEwu1di1xR/SQH/Fvl/V1YogVpHmYs7NmmMbBFfc3y1yoziPIYEGWu+O8t/dRMdnEweBIESbE3V5cqPFxIQyTFw/hPHihLCR8wVBGyusRrpQWIT2viX+ze2bkwFtyTaRKjWPmmdTXAUJWLMFCFB2zceHRfl8fTuGphXG63NpT8gmHckUoFeeNIxLTbv906mpA8JAKlnRJsbRVJQN+/SKNSkYoP8onhXRDTj1edl/aacnr4pgV4fA0R4P58IbfmEbjqLx9AqZSQmtoVDOh8cy8X1pyHMtTB0DVBrLmJjCEkrsXd7MOAvW9gVMv9HZilAgOStt7P6+wFRhMHE3uImnrxnRl0VkqQmrTK1fsUuaUu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

