apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBE8irpRQrMuLEjSljX1adYKYs7/XmDBQA3dnRrZaiY4PB5+sgLIeM+6trfKQJwsGWaKjyfVOyl5dgj/P0+xwfQ0KVn2/RgCdDDYkTsAa7ya7R/AdYqHNjGipjCgB6Rf9t9lLHm+LmhjhZ2EQQqUEJHgXioe1VSH4YliWWBT72zZlINGl+mNS0MSpw+kfyCQWzNVy5h6pYgMRoy6VjSMkmfpqe6C81CZ9x3Q7tsG4LR/Z0z9GdqJgaqTMJC84sHC+qkQT23mE2OyurEu1fSR8Y/AMq4Pzrbzey49o7mZ/7sU6PjUdwV9dNudGcoaG1a7Q9+V7MGsMdARmkyoQFcb+3K0eACgVxeGGwoUAtR375hkcQr2swBH3hvp2t23lnpag1I3N8kraE+0aN6+iiwCxsalmdP3mpphczBwQjE60ZSoP9WxEi20t02pl9ZV5UAgIRuftFKkcnLGdMgbKYkil6occJkarfp6Ti5BridM0W1sG1sokWucOYWlOK701JEBamre/hgVw/T4lWfcx7lFbdADwpsu8yA/TWQ5bvst6zKDm2EcR+t8AtYVUdOWe7ptAd1p980bLqTq0VX29kbMgB8wW9ri+zLKkWc0PLWXXmh4wlNx9e3znHoFMpC4afA7CH4/xQg1/5D8maQ0BJrRMR9Sut2PE9etY4BA21oAdABaSRkn9NV8HlkMxCIx+bWP/cDoH+2XCUTu5oCcbvNv6JiZtTEN8Pp5pF7zrwv87riy44w88IaUH0Izs9xdzxRXNlSGidqC+0afTHQTF1tpZLza/uBLpa0GzzMt5qGZZGlaxKRaLGELAL28Bt0Mz67lVL3YRrBVOS3xUjN1z9zycVYP8VjrbY7oMhFj6MIFbiYqij3rxEbJbm5Edyg5aI9Dh/UXH4wzEDdt7FFL4WoF5y0ROr2VGxc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

