apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCIVx/aOqAWf7RUg8VO203wAQLbu+3RiDksCMWTAITDp+Nmt/pU/JJ/d8z/q29LMECj4ExRwcWvAdMBORXHpmveUvE5pRW3GuyQDZoTKTQw27v6v8S8suYDXt01HLb8oZVZ13DHnP2zwPOkqIw/K8uYCBpFheB1UOjAHrqRSP1+IAUA02g5wpUE3uwqYVS+061W10rFl59ryXuGKYsxs2mlTzhoilm4MbVPCf/BM7a7lGJ1Xyt/sSjgo6SOZEsHYT6l2E1aVSV8VnuHp8LR4KtQjsFzc4wcdUovyBz19ym2w57wRyQHr7OScsWJ4mc3Sn/fjoVtwCLdieljsArX+BLgWxbQQo02NYuV6UcCteb2yduZNqUmVMCU/uxoJ9IJsm0suXOizjaQNEfvVIRqVhSiab0djpXHAom/t+BvG+o1RlFE3k5UFPpVTDLCJtIs+LVzpc5uXO0SldP1j6cQqpJH0eEZDu1nGRBiqLfZbY0WtblY3bmo6oWc4QfRzNPiuNBa7nIg9hkpcK642ReGZhoOPlZT0dIRA1QMpVqDsf1QVssPX7CdnwwKGdy2TYcvH0T8UjimdMa9BCZrhzTqBVhyA4u8GLk4ziqHjdiN6jyeFGYsQXwPMLW6N/LXILTV5/me30I0FlNbY0AQC4cDFy6AICPe6VGv9vftO+k5yckQOZ8uFhRRQAkws3lGAKpzwK5ZEtWairj+I+CJA0N45TW07BqnX2QF2gGj2FUJtBEGnQk95p74DO6XB0CSRVLzsRG5wYYN3qknCQGVVGZKLpZ8WvFt0gkQOwkIosVE7afMxzgvtwIxwAkJ/nTeI9HuX3weGgp1En8/ZbwnIXs4esd3vY8buDYctR1e37sgBJraBZQ2keH8G9LWM1pohJ3tjLrSrw3rhkyevjOdb0Ske3ZXQ2lUDCDw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

