apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBvYEdvldaICEDaIbGQjAuZrAMR2Qqc067HnFn71I3aHDzVrliifqwb5++PXmig/e9r4TqWRwXUdE/EU5T3o/9TWnjbR+Vwd5KAP2nYH6mcDsuUiEwpnSyKblrPf8ojDA9w/rKqV3sr6ZL0FNBdY26Sq3gjPGqUaf03W4lbXOFJrjeP5PgjHUYoDX++nB4eUMmLxus+3tXoBKGplDh+9K8wWbVhq+NFxp1NmKA4mwftF0I32ixVxCiyShTrPsFemhT7u0hIFIWsWLSy2pmIaIsmJMTvcNEV4sYmC2l/CyaRxYUrV/EUve/FxHxP6ICuyO8QL7ka1PkOYCmX35n2FqcSdUdeMnPavnSXyRXzD6qFK7TtPXDMp3IcZLLY2pK8SgYLjuv03rH7vFIan48lenaTEcbzcPhY0/wx/kErkGPjyTNyr9WbI8jLVqa6TqFKQZdhQ0+C3H0atTmEbsT4ZWquI0npOoGhgCABKJIU8CGxxAvNdRjyLbAhtGNkO/ZzMXrytI6aSVjbK8x4a3ykAqOASqF9vOm/RCWJjPy4odN9Q7eHEXYEmJSZzSv1bD7OKf9Sj4mE57SwHb92qyFEin8md4m2TFOPO8qwYZeV3vA5a58lhiDD1zIQ2ABuhF15Y49eEWCU7dcznmfl3rP4Rtpptpr4Hl23qeBRKYv+FqI2tdDmXhIQwoYLFZBRHpl5sMzvU3yoKIjwaY3hLmEeiDK5BQST+0schKxIAgr+2ccQl0VQT2kHKsoqg7vz8zxaYFJAKL18c6f+7KiLf9xZEcI2KHN7T2gEy5OQhpeOZ5liOxxKG6Olh9QiTwG1E1cp7lc1g/OH+g6z+MZ7LR3slsaXKrdkfSjGkh71OtMgTSMMLmoP73LyiH+2B1FwBsJnWR8D2Ef+yC4+Wr+Zn0Sq/HOrsfGon421
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

