apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCA0C/yoAHdZwKTxmMqdPf5ZGo3bhM01NFTkY5RqADxvz6WpX37rdOWSd8GhkoaLr5Zil2VyfkhunZiFSRSKYT6umiYqRgwsboEfkHwkfG17389zU5NnPi219odm8yBZZtZ/rvG6I+l2ipu3K65OagCKrCtR+rntTbrtgnFCdrDany4NTX/Xpjopdk3w6NtPpqD7Uoh2OdaGsfFHZnirb2lpzZyIT2lHtXSJ0afWZfPGfqMZ1DqNgWxemCmG2tfNO4M8bLDD70AEDs3lq1ir8z4JbI45i8/qX/vO23AIG/nJgPr9yVVRkU5ethpymuS7XGfsZMci2KKP3CBNrR/411k+W5yDe109wVJo2vVhhkc+odQmVCMSULXBpYFwKK2KlAyOB/pMBCtIVVJLpiPqNRD3VFyfLJY+H4CCme+TAa4K3wtUCDSvycM8xtAJMnGE00OTSB7+WWtMoc/TTIpv9QyYbb9Zv3JynnzuLpEl27S29Ph/rDLbHWUUVF99Q9MQXusyk79qQbAx2NjbcobUu6n+9bkr7KcaeZVas1K7WW0x3vaIENe7GWUpX738SQlfvdx9HF/iIsdVsIiSMUytsSPR+7ack5K01inJeM8bPXYBtM6z3yj1cIbdVvOGH+kTJ+KAMpLQtyNekYzdVMozMx4JasqXqTMZUco+7jlXwRwJ5DmPooYKIGMXILOu3GGeYXNd1YjHfMYJdLn0kvUwtgu0KWzhLT15qQEyH5XSak2mJq13HSdNchQtV13XD6NGaPGCTMOtNwk5np80/O/M2u3ffLgR6DS9dO70og6Ex3HY+B74kGaFdNltVhA1ERpVtqerfOcPb6qKiMTrnp+1J4I4zmqLrCuc0E5rIxBZWLi5vxj7qGW/jL1OUo6/XvKGoPzTZSmn+k+RXB7MTygIwRjAUmL+jzi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

