apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCfG7mbjxgSVbwWWGu/kNh+WNsT76rPqSOPxdFH8Bqsn/AOBwvQ7ZuJO7DzHjQ7izWzy+hnaX2LNeMwqIJhNhhgjwsKq+ybaAvCwXogNHuHFdEf0Jp1NPpGqMxqcvwzviCePRla8fGGYY+wrrMIHSOA53J3YOSTa73neT1D/NPoXz32gaoOiwpyGr6HYxjHpKz0MDVLGjEqeAqgJ7bq7GUus7Dy+IZaKtoiwm0IOFfFWqNiCRxjlLjmWNlHwalsnDGh6loOxRuo1zhYo8eeo6dcl0v0LUMkh08LZdLiMC8JsncA3ofVkA+VwK5q3IEU381durdeTVYsKZTolGenUuplVl05tcoLQBuoERIJpjCUsWJvNwjwePIO0p9uGr6e/iiEG1i9jtVUXPh+3xN1Oi48r7d4t+3Xsq3EWGtcPnOpxlcUzr3UvKqVhfIl/K2b7gGEKPZXEmWkZfYP1KarhEIHCF+Xzbg3Hlf6Uc1wpkBxKrvAGafGTiDCRAEYKhodtLnlWJTVUsuKk3hCwbVGMUDWddTX4ovPeNyiQCVyzJ/57AeqbCH+f0Skm8jJMqP8CoHjiN6d+fVogLrL+qxAb/nI6NmsU1+qcEE8nk/6FvzAx/tn2Q6YGU0peHRAgN4XAqhIipBNU0251EBBzh+a2rYOpOrvHhu3BtQuDiDUmrlL5YM4nfVkvQc6QQKKSfOGFrWdxUUeQJYMukO5DXFP4oyHZ27DRf5nFmlSTdSTjHYGE4E0vmIi0bhgwFHZNxjnbiLa8glhbcpCfFjAASzJiD3QxRy7OM4oNB7eFEBsroDUEDC5EPpG3gojNhsqSP1eH1wbs/d548dStKtv5qKRSkkfMt33/91TJRAMhMg9bjvKQ9KHO6x7cZrK3Q58Rv8L43MOHg9qctYdoRJEoIOvin5niIdOswYa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

