apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCgfdwV8fd9i31mJcK8X965dMdP74k2b8lNTU6j2t0xT3wUiIk8aftvo1TQyI+NRHRI6ZFLuFWFlPRxywK8HOwlCd0frU702xsPGVEYz/LNCDZ8OpENMBgN8QPApXEaJKfvcskQgSvrUOPfbK4h9vNIIuV9NnEKjB8lxq+7X5zwYELIlLKY50Oo/q58a33BPeFXHPKtPoJrCRiVStCNDMv61bG0csnw640rZiTBnI/4LO7QLaxRo8HWQ6eVoqH9zakueraU8mSJ49npfAYmSoAIV2tvgdAA5oPxVoq2RBXP0qZakU6P0uBG2kSFHG6qIzMlVXJgy4IwQDAciv2n1nkrZ0igk9GB2TX67BFzs4P58s9R/e8RvRj+uotQh178KMVQDTgMOUBJ3sXZATyxtLY7Q3prlOHb7O5oKV+TaXxcAabg/7T3OUWp62Wwgsd96/n3PPAa4Qzj84BxTIKlIRevg17w6afsSibxVQGkjoSM+5KFYebhsmFQmh1V6zPV77Ac0e/r10HswMG0LcEYkbxMwvOWRwMdaUSOchEaTsiva5ySM56+PTIScE7nS+S8VssAdRLNs/y6gbvoQoYznN51zHVD8rBgBNfnRzwPqTLyQrpKuedUC0fYS7woizGDIngWdHuOVYnkm6p4iB+eRj591zSvmA5iCgztuMczDslbBQGE5wrFOM/8mSAQaMXRMZ6pkMADEkakaFr/jBxqvSuk/szFKfACglvn12ccv9APibLFlUAd6YDvclV0KHOdQSNgWydZ89Ip816Ctz6NjacMcgKFXMe716w2m0y4yoBjG0b6QD3qe6O0z/RAuL9QigKgOM2F9REz1RkdKvOIlzaeancJdg3ZGdtYWIFhUkT9nTK2BcWgaW3Lbln9WUCzHeMHeL29rU2f2VBrDgtSQwOZKADo85Li
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

