apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBy7oAoL4goLGnXpqgZc9pIJ3tIT69JvvudZMPa1P5INuVKYxxTrUqP7RNhy5n683CZ2QihbECrtw21hN2e9kGthuxTbNsevozkNhZqCmBB3PEK9Bn5Bl1W4lpV0PvBj1W70IWuKNkemPuBy7ze/AxkxTSVnwHodvcfbhoctVn9CtXQe7kjgNu6XqW1UELMR6qVNoj1gyhCKN9kLwoJRpQ7WBXO0EMqtRx9CPGLE/aM5hEHvfS0n5tGd7xOais3W84jY2Z9uKxsPQFxj/23uqa+T8FjG8q8S6yjOre0N7Uo9E0PQ/Yq1ZS+ZxSqFlY82ZLbv0Cq7cTF6M67F3UYBFZXEJ/xQ6kTduqsX+pw9FyprPxuumqxKj4UsmiTnZS6hifXqgJLEZ3ZlS/GMheA8iHyFqjqwm+lJe+J90uCT9FEY+QAxhRIXaJqfRo87gyv5Ycdt4xaIEdcAYPB+havSp725hGWpawp8B/lDhozLwo70dzjefISq7weZombg2muar6Zi4ZG1s/EX7a8dUiKdqJ0FuGmUY5TginG4hUu5ikHr0OK+u7TUOPGd/qPgK5Rwwf/zS0MocMc8kTuabv72XPXPxbeNKCQsFGGSFmMcq3NkmBHU8ggNmTCvLtk5haABl0n7J3ZlDewYAe0RlDcwa1P4y/kXkALSs/YTW80DhW+gwyIw5JQVsaGUmAC/jWKKmHJf2PpCmUOW17PRcBf1Hp25mgeN0J3ohVgz0dSdFfXfezZbns2DwCPqUNfqIAek8qP6yRPdu38H9U6w24Zi0Ww9n2R4d/2Jdj+ycezDlAPPDPEeCmlFzEJ8h6rp6y8ntN8VDjwzdDpbIVYNqTa1NZsEQepphimNZ3484KBy8MWNKkVEkGKdgh5C1CC3bdwxW5nTVkN0scr3MdL5qQVVgYZA1e5BSSg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

