apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB1poV8A9SYCFAZL03nGbE0oD5gyifwE3WK2UHTudBynLvazg6Xx2fZsexC1l1z0vXKSAopWIzOW7ShIa7hoemGHEy2dXMPyRFNSzFsANEuuUNHiOrzlUFKui6Yg2kyqkXFy7eMU4bTrHmnF0zv4cOujoS0GbL+LjFoYAXLJWJqgDD3uU9d5+BKUZgtR1Ni0msM4njZH+25vAS8cvi7eVTDvnP0GTsR7a9CeZSLxEHPIijn/v1hfcRp358plRIvzVAaQ3TR0bTf0C5tEvAH6k+5EuO4ssvMxd5hogeSM6z6tu42yaNkikJv/sNf496qyzU90hrQsXYQdXD6JdBpntV1rplcGh2SjuUbNiFDa56/O4lgCiBK+VZzwY9rJyjLIIincmCyw9LbjZ1/t5XeZ4zZVQgsPNHMQ03cuZJTvzyTogC7aQ6knjw/0/qkqcpoSWMsqNaG58aKI1+J7JyH0X9vymmJGfyikyAlpJTKfCpJFBO+p9YL+PCEd1Sj4xYhAIzpLfOF28TJTEacpyfIO3mfIsS5KUF3aarT4HXabX4ppzqL8BMmeEhElXLkZFWF1bU3KY64TyDkbr/e06PMOV3BmrNE+7f9FZAYaguEW3ayUAKYxOPebd5iLk92AFPVTiKOdlxt4LQLpXS4mciQL1H4k3p/OrPRCks4IrN5ad8jcNo57T1VTC+nexzk/gTzYabM0ha9IP+7Z6PXPNIPZpYYsnngE4TthFrakvQhbnlIm5tl+D2kyr0+I+Ksx4Slnvv90RWtZ4GYXFSv3Qrsq0Rda7CobDMgFvGj6ioDzozhpl6aZ0ouCAUCWiPAEL6mXcheOdxfK1um8/JQ+xEWsHFtw1tH2qOFJZRGwSMBaFJ+hXCAlnEeLbXstL4zv/jwywHBrL7/kV3Tf0Cagz506cDmsOa5qVFe
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

