apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCW3i6zHvwqnwGRVx2BuuOBJy75cJaQkk+GfmgFHi5Dmmk7tUbEwouy+TEDjdpLvIie2t3xRIt64Tod6E8rgxPq/ity4brevLjGQkd6buozuAm7ct19pHsiTseiRiVlxBZF8jh4bYDJOshQR8XfLIz9yetPx3l46HZCcL4a/FhTX8Uk/f+vjERbE2l9srLv1JJSP/bL7RUy2PY6adnmizncEOyuehiRJSiMxeHFyhrfz5T2L6RGQUi2QX/ECNEwCxWOFgnlYS5g45DjXO08bMxPb+qyVW2O+yGS4ags5ndAwT3JYx/F943FGnXvz9vfz/4FtNU/V12GPqWebZDO9vmcwx3aD8v3PRJRS6rTDaEsQ2eS46Kb4+KE+v+hcZTuUvngh4MOU8LFXYxTok/EZJjKtV6wvkiFEyu6aDzuKTcKRLlEA7tOeRxGa0V/SKJP4W8PmyLWefAH0ZW9c0mrWdg1ISbTxhqdx8zqOkn0lWbt/OXjW8602Q4GgUkIsbV2Q7p4APcRJeLr0ExVa2DgJArx2LmkY9gu4xrD6hRBYBUzT5ssnZHCO6SJnNUlF4HbozBR1HiTwWJfWOX/xcpzBLycf/6PojW6VGHOJcdVwU9woXS5cICnMs+DpSED/820GaVHsFNI35W33vfLS5RE8UOS0ybfLZ4qTW3NcxrcmX1pb3MtoLm4JzMm5wW6qFbXKebNxENRpUw70XPTo6RPnpAO70RQBC9g9ioO3NOjSv9CYdMNfwD9p1oJ9Xez5YOtP9TlBQcqDZdiEssQSLU0DuccROjkxadxiQ6Ox91+acs1pWrBsxn5ms5N0pUoXOvRWTBLK9326Tn57OOaOT732Lh5irhakaBc1uIFiHXEMfoAG5xJO8ae1dpoiOiCo3S9xpN5eioLkOmm+vUPiXcIq1yKhBZ4ZT30
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

