apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB475KUv8QJ3vr3grzvQnKCUdt/etKVFrDjtIraMer6KmUG12XulLOjuDs+H1bExhsOk3D3fc5zBG7KC1DX3Cf0HA3J6UmBMB9SYKMLDoRhsBnSESWh37l8vmsYt6NSyuJt5xW4Gqy9id8fAiGRBsfgV58cXuUTrkhf7XuE4Qz2Ogu1UYZHVVJRU4Zo+2OOfWs8qcfgfyjUN0EUrGEIHlqTzwR5p/ENff4wFhdWGsxF72+x7i31vqcG8sejdFn7FmKqq0ydkyKwm13dSit54v5BKLhOKRRpH/7c2L7/e53bZqCbR2/lr0M43Rknj/0aE3U4+KFqZvSKx+YxwcHr0dP04/nHh274ieZSfehBQb+3MXGkAuKg2K691kwz2I2mCv8kMyxgRzKKXUe4PM+iRYw3illcOnWa0Ot/FMYhgj4p9Vsy2SrPxHXMSzUtek0qiJ8ernfdCeHUMY0m9UStXg2C1nsZ47nszVlKOjcMPpr350saYdFufcMGCidpYSrLef95M1iU0O5AMpExQG1MV8lP5myy2xc8rOULPFTSW0qGSOywr/c3+mRlaIRiLilGXz3DR8tT91dREidm7zNmDKHB5ku/rO2UNVhM5M5koPs5Tkv1rRIXZ3YVKnj68S7FSG0FIhuX8Q3QvTeWdYAYtBhNb22KX2K6n6iMuh1kyfO50UNPNrlpmNUdJEWzw0hq4nC/Gb5L2jD1iSlWGUE2xROZ1u4IAr+whOs42rj4NtDcf98tdC9OnYI4WtIwNlt71yOtF91h7TEanJtUk1Dzw4bA1qhEE8nxZSGl6o57eHyvHkaIiEXmKsVoTXn1cfw6cUP/zcSpbDrU5V3INYMaNr9cTXMEWQF5Bh7zuhR8eInBc4KEu+S3eNiIaRXetgj9RYH0PiAqvUIsZ2gNqyehrWwcOua5Fjzw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

