apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA5f1soRFg9ybmWqrAppfYi3LA+9Lq5WbUs7zcQsx57uJ0SNwrqoii+s/OPqehlyD978MTvLtBXqqNxDWgaQyn34iNPKp9DiA7bk/wFTtMsg6DVj8fWno+CPA6kBNNumXhZEFnSrYRi2Bo14FTH5nYXVNUHzfoa+DCcBDtFxfKGh1LBoj6LogWNtM26mRgidx1ZX/uzZm9X1N7ZU0MtEdNcfShDGk74vRF+G7j3oYn5hTo1Ia3rtkegrx3OrPMzNd65PVbQYGkhKq9/z9pgU5GayuYmRBF836CzLCgV3m4G5TpFV0n84O3wyttBgfbU4MrCgxTLJxoHjsJ3iuTjGTrb+dtpRTnEb3ubuMLUhorGQxxorTNKKXFa1fZunn3fTHbYuMFBLqCQI4Y4tVZR/y7rfyrrARQQgzbi/XlynIHwVbu01Adk4F6pPWNOU0brC8RP3AVEWySWsIzlnp495WqrJP8/wjI+FqyYC8sRkyMfX46TFP1QBHxb2OWnjhD6SMU1BydeVfy/GbVZLAQM/qCmk6xd4iizhQYVG8hNBHJxKSHGwARQYr2NgO7t5C+mvxs8Z1eDied3l1I+I4k9QU9bebEDBBwdmgtJaCzR1B2BhOXdIdYLgToVxV8w0lh1N64oDOvXRrA0SrkBc0AgVZgiRdJV3VcKkuX4gy+8wZ1g4PwFuOqJhAc76nvRAGb3WZuU1V9v+v6lReQcjAWgL8/RwsGUMgKWce03CgEpH7rZf1eeSwCI9Nn8mw6m4R+IqPvkNiUqvgBKKVtqimV55o40OMv6V1VmunTv/pCg+uu13bB9T1SZjoef7MeX/MsqEDCFIVMLVAgmdxY+leAyFcedSIP9bCPDoIbcWeVgQOQ9Wb+YAvCns8SLO0oX2RU0jbrtpKcKFjeednVpQ6xkUwoQ6DFWaZ+l
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

