apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAKHPjtm9DcpbWBUfe2AAWQ4Xun8ABsTW3ZlyrJTKygDfyf8oOy10RlgLgFLXexBR8/HVvmWst5URjvQsCA88rCBfzaegbWLtkigYY5AzvclaA6KYBTT8CKB7uO770iLpEhTmUDnzRRT7UlnpRIkhr5TxUM7y8Hg6JEycfbeXnn7ZP4nDXR0LBwoc1ZsJ/ZUYqvkj+zIcmadq8kwX20gvgCXv5MK5/CZzmqC1wESqQWiot4AcZtWhOz19Czfk/gTxLofN4z/bRHPW8FecHwiwjbVwFHbOD+ykCQbG40dB7Dpfi9rbEbdggRvB2jcTHtCpATHo4zm6O4LFQOdOGtreZi54h30d4YG/PKPrxc9DYf2NMbB6+Di0+i4T51yjv68jBPGI1SVpIRUuWhcJPOGRgfMuK/GhjO3NNWC3wvq75gKV53sIUaFWU91xNOy81kCAQmXbI8ZwO/rg7koN/PQBQyPlK9Y595CIwhe1TvP11ptDR5YblOgqaaf9lZAktcJOAn3rvwd9AMxDvBUhKIk8ef/jwXEXRoAqM7zEpYDXiSRxpcP1nC9AtVtWnZE/FHsd6qWKeGstzf2atypRBWPEP4zzURRAwF5O1UAScxXTZkeWycs+puZywJfUIPGbVU0UbFS6z/+r/e461flNny77G3K6+u9ma6HvEgSw/VZAx8IXuyRfwf7gcx4jJ6200s7olnRWr1vc0OM3lm31QrIqrJWXy7jPAhyHQsRNkA0IeUryBqNb7C2ObeOd9Bin2oQU5aC+RNnxyKzq/hWqAYLMSD5XzvJY81QissH0UOHtMnX5YhrlmkFk8yOrHq2Hge+1Clb/ZV2fSyeDcgVfhEUqb9yBzNpFMJrtpoW4qkddvcaff4qlluA/NsU3ikRXdDQNkBs2VQeClQY7XsRFmqPDNJ5ze1QfFt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

