apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBO6Zztqa0SyPw568uA3FwZKrVei9eIwEXgi4RlAMPctttQ945wbBWde4s8BrsDEwO+sRV1IfJ7ChaMbdYGEedV+Zw6sB+dwLs6CIqqbmY6vXm3PQiyeKmW2A7NkL6JeCZoejUXF+Uv9RvcUMoUqTPzhekrOeBQuLmBm0NL1Wxycq1DxWO8SD+49IYyw53P2bmmcd4pR1G0ed0HIbm2R3IZUy2OSFuRKfPDayBbeIIhRpVLjFBEkSJi1/kWfBaPd2h4i6D/n6zbkmCdaqg3yHO1hY5qMhTRYWIxsX/qQ6qUXGRv7XQMvWkAxJS9ETOgrTMTkzeNoBvQy6qGrPpGSsnjY+p1DOIqfIagVbfUB8Z1S1D9awuGFmMsiOwgv1UvaB6U0gGhyjmzgTvFr5mhA4utUvnbh6cVR1ZDMGGDOO7aj5GmwgQyArrLKPYQHCAV1/thLoKcHTlV+FZg4thSxirT29f5Ye/AefJ3Iad2izHhdDM2Bj/cnO8D+9nETWPLJphaEQFCjBjg4stdoCW5W0UGZLWTg6HcwRqj/FY48yPkvFQ0KfDavjJ4v10aXo0+DvcFbQHtWgr0dnpIJlN19KcU43BZ5RzVPFt0tTbuG/r5bMnbud65TNYyPHIo5mIppWx/BvTtWGFYCqmRlNrrGPGooc1VlKjHUZGQcGIwTr/TmODNZKUJLHFKvxyMJwFrNS/oxdOxG58sZTgySs0U4QnaAcT3kZE046DmafwvNNmZCOfM2yyqGN9hIXit+9PVxxQmWKARwhhe9xGGWtbib+2ruWaNjtwIGSwArbnD6aEJ8Gyho6lmjz5gFAl78Q5oGXF//N52nYJN7lrApTSeg2QAgiuulD11YYUYNvBis+3x9Ztqj2JZ3eiGuntWOTlAXR/Y7+QVbEW20Do8YIOmHOoHzjlkLPAX
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

