apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCwvzG/YJQZADoChQGeBjjUElXU21TCgQuJjSRypTM+0+/FxIVKiMb9NF1MCbTrYibFEiEx67D3azuiXkGPu34UrLd8rVxsIASIC5vcHm3VncElKwsxcHvGChavN+uAmeIppIQjLRLnEd4m3at3ZnnHoZUQmFT6m24Ur+6WAok5k5WLYBKPNqEDnLw/6bUxhZw7Mfv9n1GDWKeRb8U3DJqC+U4ITiSKDkD7HUJ6ARgO2SWadkzlkes7vSrkOUPxzXsBgN4Cdi0MxySuIUXhHx5akj/s28IYmSj+bI2auOROu5u4XY8mEpr9/sy9zpZM/lmFQVhWhkchKoEqeTAVVMGyEI1BvuIXzSxTu1dio/dMamSF6OgI6Tfv1XHCQAUitiWR2vkGTRb2WbLHmsdk3+kTfS2U+nQBsMl/rkbSb3Y0bTxxbCrTrX6NM6mKjHxjYb7LeeBmaBIGO9LaL1ngSSGJHW3Wep8Uhat2K4RGHChdpBl9jLuZig3BjUQr0HmkeU+o8ZCFfIOp4QU8Fhxtc71Lnc4RI5PccQG5AmbfNPPhY5Hqc65aNLe7c/8QOoZtI46K+RgDtil/oB2eHqJUgaHQHCcUqTmlaZMLKqJxw+j3cNhZYQQoklYziyL/vjbhYhL883m9xrSUdIfwodKPOQKN6F38d6tnGKSmSBBD/NTdBALz6YugkNXOwYpPDkOeKOHDC3a3eNGiE0lOzBz00GyalMMKMuitPRad+kOAEnCJOntEF6Ws0KrtWWt883+XfDDmUvQM3mC1C+IkLH1qQaDHksnYUpLbpF62XBklqqVAITpRBqf+VUOaF7VxkVqLTjhRpXAVmDIAH8nI14L5wl3YkIL2n18mhfWWRMtDak5UfIsKqe8v1Vxnvpt2J8DS21MZ+1QL41uuqzfxIpthLoxeRJfy7kpn
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

