apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBI4Cjinz0OMTMhSgBMD1YL8M9UxShN/3C0GJcrTReC3b/Lb1ykZYKO2/kFxEOs2jalID+aQbpsJBYJd4gyjlrcXOdG67QeqOvZfmezrNfLmZCmnjKHy5cshQHPwzoFCcKWwnL6HKNihMntbpCL0CJS6mwEKXkNL5jh4zonkf6NQE73pGQCK+iwWJc+liGVULmX0lJ7+XObHJCLH5SMdro8AFXUeVJS9RBvsW54fVDCticsVtVQd53RyGHpmY7lihq6qFOvWyWL+SL/cf6wwFixOUP5KX7E4Zm+7ih+JQIzv5HArloRhCqZwe11luaRO8UMbwKekVgK7INfb9Gkk2wON3DabCYvrDtgnfAGcRKO+GkX7O8Lk5pewEKXEIZGiNDzuOShyjklu4HREE+wyLO6FFrhPKmXaRgyqbEAEZKyU2GRZqfoeKNBkABNY7gBBF3iAqbwGC+ApcGudoAcp76EilhdhMjWmkxnPuvJdoqF+du8g6cbdKqvYwj6S6ZxMuLXJI6/XIUSgnUhHmJXL977yQz1RIIwV33c8YfrmsKLYi11yUYW5eTO/GCxnkMvmLnoQcwAXT2Yuq1dNhTJSdUiU69WJgIiwc/ILZcDcyJY4x5TefOQJXOgoY4ATk/KSv7pPQYSg61iitg6ntr0UB+4lC+oB48vjJXxJdfLyP06f4WmS/gMy64Zu9R8VgpVvanUG1wBUR2fmU6M5Hj8KNEB7ctuecHFfY6M7ck+2VFybWj6Rim7h48JvvxhbcISwvCO23QbWLlURQOVmRg85y0Df+te58jIw+anFDjGZE2JrX6CNJCOvBiCXtMDd6l84kBKqI+WzOPLtDO/DR35Ai49hEqb6NAQg30+0tpW5tvX0yPEGdorRZTZmpYyrHDHhyuWnSqVXv5gf59OjweqakUUwr1WiSeV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

