apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: longhorn-system
spec:
  encryptedData:
    .dockerconfigjson: AgARCW2mQ3UfcQJ7HSqGLbSHA1Za84NtZbWg18UXcxBEEXPGyRHu0roDaxPB/gkRia0Ypmy2wzA2CURiHP4nzxk8VesA+3g7ytZHbMgJRVfj0zrEJ5NB6HTjbMxlGophBMMzRxAGsH9LCaGeopuJqSk7gQJpq14YRxq7jUS7QaopegWcjpr8bQtpwHQLsAJ2YIGv5Vr/kDITdj2M4tziyWwGauYp/lLJWo7L6aV5MCxpVSV0+taHJjD/pt3x2pJ1B8ByW6MEeWLzkvDBF6A5uktb1qGF35FQkTS1NzMjbjOSlcB6VHNBKz2waVDh5w25og/cVVs9WSo0LiGk+q2Z0Bbsd5CXx4MOS/+EU+ihuWIKxsW8DMrgjW9XdGbjoTTrUL9yOjJiyCdhpYw0cQqtonUu/CpVivbp4J14g60Pbm5PxNEAonQX3tRe7FtKzpyXqJ/N5B6vTp1wN7gvepwleSZ58iOKVe2iGXDgZBlV17b+x7RNd+V2zGt8aFkHqMiTAodrKIoQ1wkhkp/onSRgrUGtVfbIiQ3l3eKAAum7B35esJtJzxfsPoUSgs+TOCIkgIB39nmSq3pNbizfC/cQxTcbvOJftXTvhPcC/s3JjZE9MJ30gYpk6Nb5ZtjyDzEl2zfg/Nseou9E+OhNj1UYDIc1MVwIiY+/IFlgAvjhYQQLrhxiPk8doBItdidCHQ7iEjwEjzIzx7v7qEHcBhVmXCWNeFuL8qEjEXynLoTXZG2VAsZtOUBTB8IFh2tWNlSxV4WgGXr2GfhuPG4Lx8/vkfrjIWrM2Z5tdRXyrckbsacmEiE/M9nbg8vzQj6p+wq+OjCif1rrhhvpPxTnJ03uRXx2rO3qHA0qriQhjDDAH+A4N4wbB0hvOnvyA+WgpCgwdPeEmjvL6jhV6OLHgdJZIxOSNXSnhQBE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: longhorn-system
    type: kubernetes.io/dockerconfigjson

