apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBQfz7zKFZwdY7mmO73TpUaTkvjyEh7vSDTJSXZ3QnU1e5sZUGVOEelEJSmt+KSdijCBbAtLXE2lZyvQgux9GMDgCYJuduTQAdT+joGAe1VYXIPGN7NliQZ4mvz1Dp8GM9MIfTYsRVFIajYCFM0Lf+ilzOfmks+qUIS6xErFmrgSHGkEx7qR0f58pNvZPCgveR8QvWjyLKkk+DAFK+xzFC0CS19o/gcxK+ojHohyf0jU2N9vAkDqP882EZkI7RGwX2Akfup1iZGoJ7fMZfeNr4YjXAhd7LL9wpkiSTYvc3qNb8913U6GpdkuXygaSeGsJJ9mCNZl/+Ti7d0mOaM0PROrEmvfTg0LqeJ449wyOx6lAq5O7f0OHBRlDIlgAkglpjqicC9pVmN0Ik5GYUQst5HP1Elu5rOysFgPn7xcL4qnyVMRoUKAbY6icjNHw2APL8VSoDYgOU2s5M1N2/S3ZjBsZpwmBLnKBxHRuD2a3bijGuCUrM3IdnWwGUpDewRsCsNrkGELdYK65kF1tFUDKkm4LZ5sHF7nTN2Kwz6VhGUtGebNDG3IpCPTkC5Sb3urWuje5FcvlAjSvl7wVp7F77b1nsRs358DfTi+T4hlvg2IOdrkKGjuIGDK/YmiDSipb4YIqUeJNPuReZt6Uu5SuScqKMI1GEP3Jle9+56kNb8Xs0VUQXQ9aKkR6iqgMBR1ThAfViyxu/qkEP7/OJ9jmhJk30cCW46HNz0cRg5Lg5KZBOi9cxnd6/rm/8OKubaz1nIRlyaXOWs1zj0354da/6hBFOA5xFm92607xMiwloAzU+q0gFAkqTRhlXDSDEzMWtMBYkHdXXXp1Eja0bSvHYTgLy+4bgpH8Mq+EjQ6Kzf0B/6Wxk7cPYjxBFypjU6Zi9Ofg5cTAjgZdK6ZM8Fpmzq7p6XqgSs
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

