apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: longhorn-system
spec:
  encryptedData:
    .dockerconfigjson: AgCXA0UZTJ3PDIBtMPBKsEY3XwezA+Ek7AkvIB0t/8fcNFNMDXUrjn0oD2CZ3q+fbBpS6hnpnvXApMxsLLrnRHy3ZAO7hEezfXmFj+tq9+AUlaTPRe6+69P2HiY4E57VaZr6D0Ic/gwkciOoJ40ZB245AY6s8FynP96B18rvR0PhF2HOkEiOaR58QKCE0Z2u7C9MvjyLCdV+bEvc/IwlyFdyimrc08ookUd5iOkB0kSeeEXEngGCby92LbKqeZ/Z28OSUHZ/CrC531k4QxARBWU0H4xK98TxE9P7RmJbMKm4nnmeoU4AYvq0YwuMvo1oSPTSoJgzkxay3L9uR84Q9sMunU8MzGZAoaJIef5m9FURCboyMfJfZypTLmO69g4Qe3EXwWSN/kSEb2rFq7wbb1tssHxkSMsxtl0ejbpHkcAxYUNw8dcaDX6zzMzA6sG7jOSr0KtYFG2d0ekoPOkkrb40ym1SjHxfOaI6bBu0FiOurfN2zn+tm5LtLRrDZh7O1n/jbKi+kpi+8liCEmn1KtfFHWdor7LicKSVqNtkLffBi6V4qXDeswm37jhScFsIM7qepkzCBRALSBZ4InKoShK8QsgBh4xgDK5Ud5rC0ogMGCAIJ3qv968P/VtHbVBJIQ0177cvsqWaYn8ocJxN/JDGFtpG7J3sLmV1pt2ZbHCH4J7Df0IyBoOostYQ/KqQk1iaS7j1uqPmwkIIGxLa9D/W/IDqu2fLVs/QoVeLBQn5OYCkJD4df7/MbcvcytgQ4Qs/XCw+hEHPehYvR4vPlh+NPNRdvv6tRO1llFvIEn8gBVA2rkEzgl8xrppSdKPwAtMkHhKSb5abwkumR77w0L9RJnUn+/yJf28JoHhT4EwRp/xmuQ7PfPB2rs5YCbvZji4hzLtNh8nasvfbU3Da6RfgUDuSOYUj
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: longhorn-system
    type: kubernetes.io/dockerconfigjson

