apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBA4CdY02x+ieGXyQo3MxDlQ5k2Tyd9oM0MgpA10LC4sVGFeMKk+Zp1TOxGEstWWuBX//FahQw8ovGthxPAGLsbGGt4vXYo2cNocLCyWsdwW+/rGiGxAvUzRAbbHM70SHGyCaewiiddDCsxEkQtSsx/6gxm9kINZiBoylvpoOau8c/MFUOoIp5aUqwoh3gW47jbUccCZfbmr1jwJWlt6Kz2T/YRk4pcLIKfwM/SR73yxGhG/zUTumnmX1Nj9BbKrffqMMyW4A+adR5UGW1xBLIAmGAblSB7tMSgI6C6HKJdQG5rKP7wd5iQAlj/0l7ogLFsvgjA8m3uIqNvL+XvjIqZAzJZxQQ4qI9IhmI0Dgkv31F7Ms94bWUT0hQaTGkYA+EHUsJCizuB9Uct8sex/I/v+tlN89QhVMtJnIeopgoMP6oLDcv00eY+wSM2By4334MLY31/kjI5D8yfdaFpUp7nnvt8CL4y6gO+/ud7Y5zDgNAQ4hso01x6fYI8ZnpyOUbyKMCZcpTHsnGv4Coqxo9WF9rguSzeTP+L9KxwUxKu3jqLpkSUCYmMlnudx9AUkCINVvvp0gA/4uxd4QBNbiEDIhrqJxN5JkzxhtpmasAn5nyGShkME66hSrZr6a/ZWCTO3e8YFNUyQI9mCWpy+37UA+cReA7mhaGSYHJt1UBFfBgmPG8kpnhs+tzRTWlpxLAo/toofBMAMCyotoVzOhfK3q4F8H5zDr2DdzBY4e3s3fL5y7PhiM+u7rp9wSLromeidU6iAPyJ5r5iNDkHe+aQhHLOBTv42gADAqoEZMuy2i4VZ/F0Jpj9tFfdtbhqn6g+mEYGPtCkBfU5Rwqe+SX4RT8R6lw6E+X3x2jJ2hORXGXi8EBvhwRO2QL42/2VLcuRnk00m+tkdJ3UwCrWIKHcX9y5hhrv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

