apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBGNpiqnzzTRGCGTyOabi3MZMLlnho+PJXyJI/JHJC4fN9yovtY2royLtn5tTi0zavOlTDDMJzofNH9TksIbdLl/WEckR21EUIKfRo2UNtxb9l0u8B94fzQzOK04hPR74L4+YVfik7juozQrlOxTwUR6dWg5zGHRSeEgjjrsXZrYWmpHo6FUCtl3u2ZuRcL0kNaAbGrf4RVF4DZ6UzEGrm4Lswg0Pex1KwjlDKf6HheVwgtdyhggtNfw7YI5+ISBcf2kEyPM9AY2dthTyz8OPhNF6YU4FSQ71/0vSxstI5trxhOWUjGoof5F/ykWj1Kem8D/W/NUZMX1R1c9zU9cMfclaLSrKftz52qiBm0nfSgHXGsOB9TRs9pKZon9sQ4QWouFBweYYm9qqXXpEEljzkMH3GlRbO0KGsE+TOFa7iLkpV0BzmGnPmiAOaP4mlmBKTLCFmU2D2yoORIs4yOFb4G/Ot9ppZlxnhOwGXNKILgKr6YTIbxdHj0F/BVNBXdGnSl1Sck8gza745TFKtDMqj5hU61UhWAs5LkjZrf++u8VpBImoChx+AUOtdgKZympgvDp3JXXg3Xyc9CsBEHDDzlkBPNiUU3Y3g0pu023NMv88GvYN4b1sMhXf7DEqxJJArYfEpZWbvi0qBLrgQgzsKE1yoSMwDlOGqeGZ9shhAL0pccHXYgzblsBMvxpvWoHhYdRo2XQx6I1JpEHqsn6OkA0bBrL3w+EpgQ1CpJmY7R8J9t8abHDrl8rBUgGPJHwPO64BycoaNK15D0FRqc23ElK2zErzM/7ZhL6U2ZylkKtDBY9ngh25nzf92bvqszuUaA63WqQiAtSZ6xslHgUosL/9do3zrtpPVay4ZRBJ4SYFcbiaRzaq7TAEFX8J/hxgpcl6NLDZnASMWcU+hZaEpvYaMKj587
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

