apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgDA3XYTpi3jGZ6K+uFn+7jD9+ycLQIuMUMYVyRn4SeMaSzosO8NPBsnJg2hRoh8XD7usVCfrxttpA3G+11lxRHFx7ZEoY9aOjdPd8SIO/5uF0SpEaeyMA9+UKxqO+3EOqjH/LahIM8frqjRDESc1st6wKEgztWjuSps967ZG9NRib15IFeeSNV/PzWXfIonR2SCl0RckkpIhGX5gXRS+M3sG3EnwtPiVzS9teegp7KwRkl+HFxfk6S9Qin9nAQHwosVIlN0b/7/W2qdG2z+OEJ6SyRcl+1jE5xnbmybih4YezQfJw1h0BMtaSVO+sHChnIZQJ6vcZ2BOGisFuJczcwkL+WLZy466O//mSuyC48MCE2N3RviET+21uGMWEJdsm4WtZaOvgY45B4C13hAvIPQDNlrNSB+zHHoItlyf/gQcEJZtSFUnjYQQCKc6StHXhd62S/S4DDQsC5ptjWStJO7120nc6hUrqkTIQ9Xtb53Lgtbl1d/m9p8ULOgIgdE9Jvzrdq2fBgVs0fXlonxNKq0/WT7yrWOtOCwIKCYGgXfiNP+aR3POSSFObYv80GwHN+2mEt4l9nK1MhYL2BOdUDKFkfvcDu7bk8SU5yam3CC/bfYe1inuMAOnRUU4EK2mZEKDayBZf+85YdzEnurJHFzV3Rvj5tTQ9X1PK0Yo1EBD3d/uKej2YQPwuZ0Wrlp8heqUi+TYs8LrJTFWwCvL+M6d2HUd0xtnOSXj8XnT7qsjKC+wyKkjw3Xc0iDocU1o26RdyjnGz+PU/4OmpsO6c+AYAqQ5IdBgyUIxPgiF7Wj6EKpUM+pS8nBkXQABleOceEZ4I3eirgrsl4GP3SqMh40OE8U0aLrMaBvvMQDV8o2p71UBVselyDT06igwiyp/P5j/Sc+SY+lNj1LZ+TpPHYG7jQ2UdlP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

