apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB0BBcRcJRe+3LBPwPmCN6iv2yeWa2IkdlerUOzi9CRXYIzAFAbwblSqtAYmBIxEK8gaeD9vdjWjX9a6lLf3mJpN+7GtUONqZecG+e3nTdl6L+Kbt/gqFpz8aP20zpK1ILy1Qb6AI/vPs8otLVwFjceFo4YSY/f+hQgOiYkLPtXdBeFY9XXm/OnORS8X0xlDd1nkoNS2Gtt5DPaq7aDbf31bwoRGBB6uWOWJXxnQk4mGDr8OF9uj8+ZG5XkvitZtrCk0MEwgShSntC6CGvesdViX4u8HqxlcaYwhl23CAq/QewecXurRbIJYerAqaJ9eyYiJ8X9X8x8IRGuak7IJ62Ex3TXLluMTzQW7Hu0EZy9fCmgy63A0a4XvLsfWdlj8DPhVcHBwYgon8SrJbBpI7lf/53lfcgr29C0jx33RWjalfrNVxxGOa+kw2UOsnlfaHJPF4VYKFjSfAcK7ZOZ12RrPQwMh9KJ12EsQ9f11y9h6Dvsxc0JigHW6FA8b6Zj1JBgOxcsh2fXx2dL/FteHMVF5PT5ZUex47C0V6DU+pgacWS1DYW1Pjgn06FTAqybr1ZqLTODcwXpnTzfY8nr3LE5UFT+xi3Qb8SZOZJcq8DacbegaauwBO4qfDK9PdG8Sd15iIHoBPnYVtVYrP5s7Fz8HMFCtbCwaZbTiMuTjKI+6VcX2kox7CzI9CxtYncrhfgbGleTFHxxJT3vi5RtjdPqNYUyW7TX9I/JhLGsasysf6nohqcryNPwHPe8VRq56lglQ/iY5YG1+n2uUJKA9oBna1uMEfvZIlWx4lLEl4LtfaybdnE9M3eGSCHNYbv0MaNsvBopOv4ZlsqIJ4hXcwmmA/NuZi+Xzg7kljgA6SiBTnQ4tlDRH2jimOe9QP1lDXdRiNHQxExax8Kpk+veyzi7oleSimVm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

