apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCdftol6XagVyoAFPaZBvWD6NtWFc4nLRlqmC37awy+vQBLPhijo0BgPVrdZ/d6HJ1WOEOZZORHkwUo++LKFBtyg/WbGazQsc/qBDxfYRnC4lwaxhuNHsydodsvO/5Lg6CiFtne7OqwQkkWflaQOw1DGrwHh9ngSRMKUNfietQ4u/l4APHPwO2XspdoQTC70EE9L0SeuBMAevAWNiZ15E2k1Htxq0Iku4WwkxvDDzEv5racVYLgKTAOn0QW3hFJq7McDjPO82nFVNcKjaIoOeHEQIdmTD5F1Hma1/IoVu/nka7aw53PKTAGui+Bn17vBmltAvGWV88vac3ub+VojfZ4253aK9c8XzcK1KFCYrOOWvldfQ5gVL1ZsI4qlfLcep0CTaF7/NE9smInkASGqN3cIaGGpvIVt6lCFJnhpWUeu1wL66skTM0MGAXIdYQSo4C2lmSdj0SclVM6TYhnzk/oy+WsqwCemqvnwoPeSn8OQcMrVSgwkEvlDsWTpkJcqo7n0vCyQzgzuwOWuwsCByMjUvfZJ2uCNZ/fcI5rbm4ZOLIyPAs7UMBU3v7mNAzNN6qAfpZf6/6IlG5NHs/eH3Cy7OgVvRmys2TrQehG2CtOxRrBFjzuVfRAdgpx8Gz94xgbtsFyQCrxYCT80CAhbWO5GHq/qks7vd9MbrpRRAsAP7FjVnRj4Vp5KrRsaJodq6vlLxylWk6Wh4l2n/0C3KHlQ5ueIAko2Dl6yJaDKq/hdo9kcNVWp4HOPZ67abTuUANUP1yfg+EbwxQv57yqG0plLkOQbix+tpn3ht6JZvquG1tyVDYO9A/5/+EfimCHwsCmuvyxAD1DLXbWhfeXjJgSf4D1oW9keSCWh04Fpy/W2UqOKIMzGWMexlrlmYyZMfg3uubveAnw4YoP0FkwpX4kj2KEtcoA
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

