apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB5mehdx1mx9S6z3nhXt2+ombD9NqfLhuM+E1IoqK+ODB0dBD6qk1S/MagbCwAtWnIyuoeJqlY7zNIZrpkyjxFK0USxZ7ut9FTqDExwWMmA/Fv8RkAKo4Z1hGJawnm/AsBQLHSHwznRAegW3pqs7m+NlZu0+VdhdtuWSqHTJJirnzmF23y8qXd2UJiJvDzX+qJTUCdBFT0nK4tWCtGxx2pahbK6J/hcGrq5dRgVw9TmLr7+5OL1Jd8czsuZpFBG8xSPPDNXuAEk4dQfY9fE3r0dludQgmdXWPh6FkmYPCNd7mKdK/NMpnvs44FXUbF8vl0tRFnRMzwqY/4V4D6Pc0ONw0reZ4zJM7RCQE+tAU2D60B2lqFLeVH2vz5hgGo/vVKMJavtZrNzgDWbmrC6fdTLvHlEtxSLuCo93LPD47dpczHTvQclR+tn7X3sKT8PXeff8m+5upjoRaB2SjIAsENo+zIdWok8N1YKloCASlwEC9Di5687JXuv832B1cPcv0r9XjS4EgSLNO4fRDqlj+YgxsgBQ2xkBRZMD+NFHGMyf0H2SHYB1pq1TZdGb79Cq4htobEQBuCMN0b9qUV04yNBjEpS8BBBzf9V5fufwCFeeUe2saiYS2KDmdRiO0hSqWPRIt+aE6k+Rqbtp49iwVOedph6o3vmVdzeBQyWw4AwNyl2dyljEWbL+7ALrmiWGcoXnq3qM1i68UMpnaLDlZYleZlhFO40AWpskb5LmrSB0O7qmr0q4MplwJ4aEflGzm2bpNSSzmXtf6UMctW8WUpCJ6BA1mR8MA4G88Qq8vxftWMdGGYxi2d/8InHQlMmlFjqG7ZfP2j1hutRM4zoYIz1XiGnT0xaOM56vxMHxNGwS6IdOR1G3KKMTO1glvMjI9sg9d23BZE1yF+1oc+T4t2iBH9cEN16
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

