apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAG7tML3kpt6FjW1aoSxyjv6hBaeV7dMPKOXJzCxPlQa6yDzMx6Hgn2BWPSaQ8YZ2kibeIKdjnQVApjh0LuoRyqvJFUWhfzFX5djCFmba5YnJTiV5Qw+F/J52lt19YN82MlQxn/9Z4NLkDRkMkapLZ9EkTDFEHe4/Z6LQnhY3jV6/fub4Nj/Cb/NMXYEoq0454KDH3uJO6sycdqtbDVj9i/sBGHWPqMkNpGkJxihKhpUKEy7D2WakJ5VikMr3Ofp3UGdJWiH5VUmkLy9SzgXIfKogyUqBgrT8oIIdSLayy4CT0Plvp5EQ0ClxtLVo3OFU8fbcxdjztjNEu8jXTWkhkOAqi4otzhq9rwf94DchaQZRlpmdpfnrP1yBjGxmwBKSu5p1OYlKeFq7oCNgoU9UCVV4/dvCzeWGL+mou61Vh0DigOau5tVtiGc8H4Watsi8Fz3KmOotYd8mMg4lYofmFCYLZEVJJE+fiPT2OGIVn5yeHtyXg0QH1Do3WRoUf14OPsgnriG6RbUk/jz0bFhrn+PF9P43x6OV3KB+dXLWlc7BohnnAyzQ0VMnEL+qDkeV9uIeVTyrZeOp4yBxP+XfuXVYJ/bYbZ7e9df/rIfRSRd9aJGj/+VLsHYW9MxlsT/sgywiI1An01Xtvg6Z5OlIjWI12P+YrKTnu/0G8wcxSab4qpcEVnJIzQUZ47xLZlIznBqKUSPGR6LMLl/5NxoHwC1ecLFp6HpStcnWivlYEXx0sj0bubS6yTNH4kaYRwrw0lGkO2XA2fIc6P4J7NL3VAbp2jjecXOXtN+u9I6lFSwmrqCK6Gz0W7l0qKsykQ1pmdJvdIGSW8ow+M875Mq4cguEGZHoG+TBhcMFURBafEwwSlzWSwrMPnXaaealW6YKyB7SwJdb0NSMvNj8kkQtKL93PX/WHm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

