apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBH5t/YNdLBUrvjrVkMcO7tvZriqj1Vh8h5LQbbTgYVRlyoZE9pI5vbsoIvCve/Wg6QYKw6OZBI54ZeaHeCksKYmHrthzZ1sgWfO6xMhMtSxZSENEmDBhUaI/5L9hhmOStLkF7/UIE3QErFf9dTEQLlVb1PMbn0V9T1UzjGDDAejf4EkWx6OQJFxR8+eqrCJpok6UddO5fQQZCmUn+/K6B98e28oMNf1FUjRJlzcjLpnEBsvs9wjb6dqq5wPcGzO41xR8rAIwtzTrKi90+5/PMM+yrtX7NcrVhB0izJ5+2Ii6ZC3AkBAjo7CxcTq713lcMiTjwye1xLuiRye5IkHxtQKiBqZ21ejYIc9W9RzrOs5wNMICD87bHOKQseXJaHYjC34UPDBIAT/qhCEibHYqXR1nIab3Ktn03tL2TWbtUDeOr2WXflpxEhXhg+WVFDbf42WOzujMkBI9x/XGAd5LyLzRAiAlEbx4Noh7qxkp2RYv4OToXavfDv4tV3BMe58QneRKzAFCYNXAJ2Rg8h39RO1E04OsEaRiyFIrhexg7FjG+pCOQWDrSXbxPb9VgU0w7qX+dW2EYU2FvZEKE8zJmYSA11CeCs2zMpBdSTCFWJV9Ed65MMtQCRxkZ6Fj6X5lbw+4rk9YywPHRT4sj0Rz8iuPc9fRdAu/PVD4xXxhfBzh94sPm1iYTudMinpusrU3KsWPlkxv0Wn5+Q+3ap1DGaGfvnuYuOrnJtxXTbY8NWptehA7eVnKq4YNu6yT+NrhSxnpt3Y+nrYerukKvoX8frJspx4KSmgNBQbw4H5enMOF2mo/DTfCwg4jkYq83EaKWI60hS/bOuTYtuTJRExpiRKL3AcxVg2WI/Xz1JChq3JOQcQMoCjO4hJc5jVUuYzQhNRBm+e9hpNh3cVoZj0pg7Yjn6SKra
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

