apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBrYyd5m7dwyajam340r2BvNNlQj7+KJwKFFwE/4YI7ZYRq+GIC4fTIe6UYOrCUytE69NkfEz5eB9XPTwfEANRehL9yr5MVSOO+Atd7o3G0aYQ+nnk8Gfr40i9L0Himw9F2mB5LOFBFbPM2nGuPEZaZlYbGopG/3ceIirO9Egb0+BXDgw4Vj2XSpAlmh1DtQu0imphXesboCAKa+kuLCKb84Iw6xxL8cronNdp8H+F+kjAcP7rvThrj8eWOjVLYsQpaxxP5dnPv5YAMdRQHwuA5wMrFuYyXLCWK+MuX5Rjbl3AypKdvQ98Vw56+nFKrMpTDIvCsHPrCpdQRrQZTPcmQrNa01ZF1dhxUPOZiSpWtqb2YtXzhjZ1L8gb7IA6Wl42NHs6jo0gw1rIRMYGGOXYcZxpLA9Mz5WDMzfWD5xyc/WzJDaxAdCrqhw6vzSEPDmM/LFpuqOQxgrR0jeSsaNd+gaXGjraWu8T867oP5WK8QR/vATCr3BPxlNe8Iu3AmRLJU4jOtLhbl2McP/VVNKpr3aQW9k0BkeK0i1UbJoPRXCYLj+UaB0TqipcZ2mk44ju/CO0DP1Hk81gw46rqRNIs/T4YnynMnyA+JDfL9YAQ4vsixY8FI4WIG7NNj4ftYsmeZPAJOEUJo/YZCUMCwfV9hDZUj30vbYhbXqExda3hh53CETeWNkPBo97MQfQGX+5EIxCIt33ZSMoHafZIKmXyooWDIWgfFtaTS3oKPryRYcEwUXX+PwAbG8mHrAuXfP9wG2ckqhl5CloI2WWDAu0jmmhXvUbiMZ6I6D5qSQPSHPCJSjpHuioCFJH7nzQPi4CdTeGcTc6UZSw/BOb8GJ7QnVirzTJlOTaeklwopS/Hbc+3nJzb59MHqwpr/rn3LCUvKdnW04GgVL0JRwgf1Lb/t9GTHcYV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

