apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBOC4zxgy4YZvcsxhvyOyC4qUMKwtXBRB4bzFL8lMr+/4xl+acR/fzRBKU5ZKDqtkXh3ktJUnXv1TQPsndclbpBSPsarBnP37m4HyKwhq/OW00DOr9UqF4WAQcL5oh8ww+FNyanLZEqQAikPWJtehapaIipyKwsMNwhQq+OdB0obhjamAcIhiWxY7uFTibaqBpiX7eChsD485YrwgLLUvXlTKDiu4/NYe0sncWjy5NQYRHiC4iywHkyo8efLVrvXTSwPac4tpUy1RW2mNyToTKtYlNzj4tUxyGeP5SdkCBTHt0Pn5IGGStMk2oQ3jjD6V1FQcXHVDzoIixIwhyPavicYMtX9JeFxSplzFX4vN9QmTM9HgeMQyuyUbi/EEpu5wZzgrIHMyqR6w777rxbcrykBZrovMSUVkBNyZVmgc+FaT7gGqo59fKOn1kIhMhvwwtamT/vuvfUDBjE2165xjcrS1pArgJ5QvtJdR76w/0g7pDR/h3JC6lM8QraHsWDBxdvClZSiAMnulXpYP6j1ro163LLxTuZqmv/u+l0HrBQh5+plOj32eOLBQDzW7GxSr3UOrpYo1sSqbhGrJJDmkiZUEUZipplVtv8Uw1i8+oWEwripekokbxAmzC2KWQQRkivD+9s9v9qjmXXKYAj5w2drAgeC57jsShDZ8/K8nLFVjusRk3uCBnllUd1vj6sulLhhINh6WjmDk/iUFBfnwPjHRixd1AO47voylSHH11DhfqEMOsA7+oai9DhsOUcMO41CnUGGj4n/b0illS/wnL2MYgePRaX1hYWXSowGVFh4sN0oa/VCV1ldev2bDZAKsNz4f/lHlFz4m7Xxl3Dz4g1y7trC3hMYMmu5XDcYcDhng8hLbf3O8OvpY2guAPwqpml1sJjx3O61YfOO8lIgRUId8ayMCIx
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

