apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAa9nHFsqTK1rAhPg9Dk4dEd0nx4YZhlmP8Zirnhj1jJSkQXdtN99bnPY9PNv44V1iLFtGDRx0NRhiKIyHXUCHMBrXterS0Z9WFDWkbShSFQ1SQtoi8En10/YvkpZt+OrpI/3jf1LCV72j9tBxjiK9dG+3F6Q5jS2/T2sHG1LYi5f6DZvDLbVUWz2bkkeZDG5TFh4GEiAMiGBUkpTP2vHeMWviUZOWH89De87cbSEQn17VIbxj7O8fwM+HpUhBIEiFyplz5NbGZDhENluIaFjg83UF6LjQlcz3Hn+icIfoWLD/8bz2E/Dn+Q61Bv9IIJ/LUR0R+0aaOe107IwBLi01/wxSfJvLRgV/egCj/CqRefqn5aiSIQ5kCESGBukG44Ct2G7hy+SbOFMgaFE/CTM53BIC1W+sl66OFMmc8U4T6T+QO8r4oEWDQVHR12KtpjmTloKOPeXtIQzU/JOxOqdFRA+WLFmOVKa90mA1Z7jhvB2e3y8MzQegn+FTkTF/dNykudV9uZ6nAEZBNn2OsEdN7OcVkZJER7pKhCxpfC5UppI4aBA0mis/vuYuqMJFV+IWGC3SgRL7pTTSEma5gjKW8nh0WwTN5ytp/9/odzV92y2PPjUNksS0P67vMnJYh486bTBNR5iEGC1Wt87LcZRWynHkTa4iMHgTsjNfaWyvrq1LZztcAjrlz04DmHOA0r0hWiBz/oqOrzqcTLfQ+UpI8e4nXZec6X9ST8NPPFjKX6w39Y5vYo9L/eWO+ckiFA0HMJwBRusbdaMr0BWqxlf3ZJJB+KESk2DoFFx2HxSi9tb3ioNQi7e28j9uWNFq0EbUVKNQlhQW5gFkpJmxUXYbsq8n8/kbmP9k7Dkyjt/54LQy/sdrDFwUzUA8Yc7c259UmqxAFq8O5FrpAjXT4aqJXu/EGuCYh
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

