apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBlYq9aoHTQ7anLopDtLSA6UyOMCNHLjxrc6Je4Z/eTqXM4KcnVdM9GtOj/MGSgJnE2yl7l9H/yQcT9kREBCtuYVtEcgFoW3Sicrb8UKgEODemUgP/eGuMKbjdU9kPUeg0pf9uR4yjiEHHv9hZGDH4jywA0Jf2WZIyRptv4dNHJt43UuCLD/dhgf62e9b3FjodhUzuFvNP9xxRs/mFmmF3d/pfPrGumeAEJ+v8d9kJeH/fqprLqZ1z2361e+X2euXVnvPgmcsIF07vXcOuyb7tXaCV4P8QlmJCqGNBbfSVJ0x6XCxCU4yGEtsOJ8n/dhJx7O85wqdqaxqr/mKJI0FtyXTDBFJm93DCHWwIRaf4L3/KzGmFDn/NVkE8tuGkWjZx7KNdDhPdrc3c3TkAtYd+rCOB0Hp8Adn9aPmeWM+tRbxDHVJjFz5RfqUPO/0OIVdYbqoq75+UZQr3x81ivwp9RX/MFlEDszny8C51vDVXEn9qt1xtfrNTJ2fkHsucxuyllP6L3tnNYL9qP7EBQFqO6ZTiKgUoi3+xmzjreey9xZwP6QGq/g57k1ZVH6OA5J70bx0PPvHOPrLf8bDfFueguk4UlFCRGF3vcWh9xgtzmvFhs9Z5u1ZOQB1NFUwnlhsFzbEqaG6GxiOffTFePx0cp1wY8T69bDnZBT5qZZ7FjfeHeDDJSJNHr5XXFqkD9KQpczED9jYUU7QiqY/XO/zcfle7XwDgVk6z017OKubMsTWUwWsPzmeUAjD3bQw3Vy1YuYcLtVGRdFqRsJznkrSkMTARl5Ox4anI6KQo6hwYDXEzb5MTZ5vgJUpeRymR0KYCjmTiQHBR0eFXP1jxpyIzFNHuUd3+zYfgO77o0cFLZdL69kSXLkUpAmcXpXMNYYhL51UZA/XeXlsduAxfjpRfP+0f9UXnF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

