apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCkD9ryYjat5C8gaE3SuGpTDnLDjten7KkvqMXwJ9VqfQ12HOAYHBWfSJW2fYr5uEoIlPBCRuOro85h4sHM5/eU3sG+T939OUx517iveCOt6DxJeR0K3iZ/R/95SOL3Fbyeimcfes0Z7J94sKJmi8cvT0PbvJNdDDWOBx8WQ+5jj2REfjHk24dHAaw4nFVIuMMA7YNoKf+XBqzJn3bDxKxfoJEc9eG8hztEGODEBGKQxNfFcpBhMmLyy4hRNOjVQnk13PRpioktIemTbwO5FfsLEfgnNTL1jlZHWNKwCtUUFsMRQPqoZ33c6dVM1ekH3kqAWFBVqjokIpUykOM+hnrOzGYK1VlELhzXatFZ9XaFV+RR7P2Ca4HAQg8+NWGqt+O6UyoIUyZxvugWrOZLwpckwAoXHoWf++tvADxhgL+rev1OEiFb1D3znlktO4PpzL3rrAtfpM3g6H5Xoezk9eoYkWWV6eU+2kJCTMmzQAEEi8Vhj/lRLJfFXRPUqedt5B5cyagOXcV63I11exjx7PY/80x4Os/kuKNmPMXKSeipKiO/NBNcUOGqPWsLeJAh1iTRpbMCa49K++Dyi4F0jycPArbbakUNM/Slqy+6tRDoHdHne4+ZqKHJd/BxfzgYJNKGBgwz38qTZKGc6aJglP3xgowRBr6T1B+69CtBwqz4Z5UJ/Pv3mjkRFTLaxJsGcO05P3TcqW8FpIfqmygiJ7acslvjauN/3g6mi9UAMBiJ7CouP4aff8AHQf8VTglH9N5Z/aCapKdd/0WXm/aCEZ11d5AwRq9puy/RejrPXp7sWWM+lcKCAMqaZ1BgBSCJoM+ug9m90EbpV+A1RLNi0lYDJVGtIKBkM1n3yifEP5/hS84VLMiHbWq7tZSWfVDYw/IvGwpwgncBnGNG9l95TUnK2qR0Jo7y
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

