apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgDS/rQyhcJOQVw6l/eT7wGtrsJvH+PQSxokpiMI+W1RrD1wcZ6x9z98pdx0G/uxR0gQ5CcbnuSVSPv++LX/tVsE4futuQPnTI+FhSt6sO5qvZS+yVFKgYb2hhrA1MGcALkg8kgrXWd1Y7RCAuGyKMxaTqD6HyQ66lT0234oTTyW8bPTU3mwaNYwytZVPhtdfa07tf+E3uQGjO4+UYXCAPZlx2H4NGtnqa7yaQ5CwzOr363XPG+G7xf62tEAO06S4nHSSYZaZ8mbppsW8Pj2ZIO4vtIyL25/BiIcWNyT92uC0Sh4kKwAckxB6asJFPHzDumBQGJ+kdtiBF8UPz6i6HOtJ8qAtk1J/1LKvqUbuPZ/YbCPzGBPnIpjO2vUmp8cOECaOuRMGJt7J+CDY1e3M2y2Qo1RSkzFcyRcn3RIzJKrJv7QQM+i7a9WsCdeUCkS3FPlKF+AfTNJuS/gL5NHPl76DhSV8o/OaGVRN5mnFGMa0rFRfx+kC+3d+r4RB793d7vZkIHcNTN/0rNJCAwlUMqa1JkLwXXtt90YMpzexLp/v0l00sQ42xiONAsRDASg8pdpnauMVDzOmnFMdjp6+QEGx4VS8XM7lvovmZTXl1dtteqFmDlBOswyhudPjHF4H4y0vD+EQA+36e1VAXAVwf/dow2UcJojJBuMooFf4ADDfMpopLczFPsl05nqEHE3u9YQBvYRuwrVdpwfvbBex3MUKrEkHQK0m0eKEPhKltUCbbA1HSjT2AZ/wnakRsEIYumGXqltPp90P7TrBg3pIf1hoS4t2CxxCyNA4ije/0Jo9bjebJyDh6p3WySBICBnxRUTyR9xfCj2KgMroMDBcPxlloL/+Fo6P9ogrf9a1SztaLP+5nNiuiHMEvkVFYi6Kzk6jOtIWwpRJ+889gxEVQz3eLT/iOe9
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

