apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBZ6uoXamcTMwi+0XgaLIMmhnjJ+Gdf23UXynSvI00dqc6syg6TnvH1G0QwxR5N6Ol90wG84HYUL8+iQH+mZfd4LUa8oM1F05Q6+toqjdPGFme62Lqbgv0xk+e2xT0tsDL/nyzKZSkYScYb3qJTNc4LbDXVJMcbVt/H9bKKbzMvzLF110um1PaC87tIxVm3LUN/ABsnVIuPSx5gp+tl5f2VAG0fwsUNXjKCd8B6fpbDofwV25g+6XLVpY+bg/F4Ts2wsv6HFkGglxKHZYLbUoF1Lm/XPZXpBX0byAsDB3SdH5K+I0JP0Zsni04UpfeoKX5Iir4YncWmqVhq4G4+HfWKl77JMxoEhk2T2Bfr+NTd81qtLylTcZMd2KMlw+ks/Bh0jffNMBV1zOLmU457Ort4AYt5ihh7bj9rsnbQPQp9cthygVoDj8Kvh6l90TQU0cdrQafx8z1zxCRhXso/KGXtn3eneWLLAHdFi1d3WAnw9i/fxOZ8qzkcIFwKF8rExyS4grR7yVAj0JdlPpyaKwzy2VNWt0AsTE37/1q8Yg6ZHY2TOULxo/tZpG/YW+TzP4ESQp8cmLsmE7NyRqziRLCJHGy6BUgK2n2r0ZJEdr1Hm1DNQXV2DE/GEAJx/D9yDVnfItU4gY+5R1f0SqbSF93fBeR+L2IDCPOUGFBjSYWn5eF/pb2UMoGc1HuA/+qi4FEQWs4G9AUunSCB11Aj95PumACI2TDG+rPX5W56D0vbtZy7Oo0wY5sNtlT5CjjKudC4AeZZfADM7kEhYa0xAWxWSP/ToRFUtjclREPMLevPoetu+UF6ftMZoHApeXx8oL1DrUJ47k/j8UTDFrH0142HN0hC0CkJWlTr7IgjjyE68EEBbsIG92co6XX3jFUuN/qgo25ZZguaeIb9AByjzgN548tLgvex
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

