apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCY1OLWWBQ+twaGBz6n8oN8+zkhFLrivqs0+Cb1hYqVq+JSGO4k1XVtise+B8TlR63YqZqpPsy6V/SyWmyv53TbK4SY0LWT15K1deOlRtvKrAc4CUhA8c62hOBDWmZoa+LGKhCkSTuaDICfDcJhJDKWmaZk3y/zfUjaPMVbLWiccqM5fi+ZlaWTcFLwMxa1B7v2z0Ivr3RqDaNmTys2m736qwe/qVwKZUL9b0sXmLi+BaR9c139/5+Htyawk6JTZqiFGRlG7/4KJXuk4Yods2ZJrvrTXh0e2e40izHkTzk/LAJSKFm3GfcRx3n2WoXvtRJZ49oGVphEPQvPM6qbiB0JcvUVCGGpU/1AnT4XH+RAPTi2bLDiydUdEhtqjg88h4d1ghpvy+w5F4EzBMSwlKwxY/L+F0vfr/gooGWhaM+S9IwO3tnbRvt0IFpIWtQr+WX5MymmUBanbQ13dd4O3V2DuKUMRim5hIblZTUjjNmpFV2HOoMfRdNri5m6HVnxBBGF3Yxn0ejGXZsrUUimWHH1FCxKZ93iSrAhNJJtXOZbBYnP5RUY9XooJFFMAiY9o4RVH21LV+37DqUfree4zq9R1w7ioddPB2u6QOSM55VoReclJOFQCx3FNexgXduS4VqW3ujuqklzarZ99egUJhKRE6VptO2zaGGa05/vpQekIGAHyEJr520kgNkUdZ12KVRGWfgHir7OiWh4ohKgYJ2I6qodO5ks6oCSaimWZofeRGOn4LZ6cFeibBTBVkMIcBJqA4zXz0UgElJlHYPr/BeI8oNGn6FL4qonqVhG/4DU/ZAABR+AR40OjTdm7/Vb5TiKcgfk7brwT2r55y1YW4DwROBzRRVoh23dcYIaI0I7YQ/SFbjAFKElEAgnwBPPDy6b3sjFUE/c86xwUjajCs4vn8YXYVYG
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

