apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBD/6vFVBVu1tX/8CXGQYzBQvv7QxsAS9JfX6TLFlLF/MyM+ih3EaS+VLFkOa6Zp0BkXRpzaGEwHUXMRqqMrvuyAeA8DskF2KCpEC4BbuiHGCe8ki4M53Cqekbqw10fNs1wQc/+Ncl46Ux3gokFe5aCAlASa85cjei3TLgajpt2EUpGizXLS3y61At9RW0DrPnBSvyNi8yS3wVxYfydS6+NrBGHSQ5H8j8EOfRarNnFHdjY7P3AO2m3FBXjpzWh5a+6Lp+aBHEk7t4DqDI7o6tllUplM5aqjz8KTDrtnergJRml5i8ch9HbWCfymWNgEu+pEnp8fvWEOkrIAtDX68sAk40PudqfZidHLeNa7VLu7cw84V9L90vVr/qrmdW42Hn7NQqnZLHnw4TFcCXbUn4GN9f29lgsHvgCwg8QfXCTi/vAjI9wDRUxlir0zX4/4FkuP2aeXKpby82iVDk6mpav8WPi1QBPB3qP3vcKhjUPNLknZQ0MPL6BDhzJF5Lv4ka42pcXNFV7zJf/rjDVtB9jDznWWMDlMEkTJuCfMQnax92V1OFNqqIEEXitahdwAGpKwKMn/az45nOLNUH8Ha8qFTJGs1VwCcOLPGNF/8pGXn1y49Yoxg0LFJnRJFpOMoZCEXkClNt7GrWe2/ppo0CxXPASCXf2zJ77V9wqQuYAEbAWf5gqLXzusEk5NjOUPu1rcOIGMmgYt65LGpplk4AFTOruQzoxD3EVWkbh1vf5gi0uc5BrxiMawBA5R7cF11rSgR5sHMmeNcEP4d8lpeFhFSz95jODbIhJSuh62BzR5tGfmpNmWHr7iny2cm/EyW7MgH/K7lNhjvfFcAypTaYcD+XYTHYiimzQg7dmPVOWlv097VRJ56gxNw71LqV6dplgAgF3Fbc3NX5poCPS5d7LcSiZnQ/J
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

