apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA92u19k+plx4KSIB6UBKA9uvd7IiAkNlWFc6mQac6q9GhjJQRauuN6tMmtBiz9yBV8hW44cWZBaxLq6LYm/c/cuFSH8Dcp6XQvuJ2E04OzLj4r61jwF0Uus0PKII+JiA0QjBbZm7zIhw/L9Hg9rzs+e+nqlHF1vvb6kwJdriQgEWe2oJdjMXn7vf/RyQDox4YdrTtwOIWvhmQN8kzVDAvsEm45mE+mLXFUwbGOalZBVIdK7YsqqaxVAZP5S+cSsAFQC/SYSivzPiwibOIckeCnvNQuTxCDheq05nC+tNGHVuew0+FvJjX+f05o4EbReWvtK5z/ce2bIdGLYlEyA13mQQ/OqPVsKnfbPjp7xdzI5CLnQ9bRP9H9NGbwq5dccosRZDDa4NlohNdVlW+KQM67HRdgnhPaKUTlGUJfObtLt/HUlXbo7vGd6+nIrKhLMwRp0c4yCTzaXYbG9k/ZDHFbi2X2XhPksxjNBPcG4oVSea6KIIhrr/Cjc0o8/bJDMj1LzrwmZiN52arasz9Ia0i7iDoJYuz22PlnLMKMEZ3nkOp8vH4q9sQ3oUQbkNzhqMXYup5fzHC1lUyUDjRW/p/AIZ8IFxs/nDZr4q/CFT4om0NvM+im+UqADK+3pP+jrB7H/YzfRDaqh/1n1/Qk0pEe7ZK20nxG8Kz4GD0QMN+cMB6ZqTZER4Co1y6N1cJMjmiiCpVU5ZUwxN2ksvMkbm7ja4ce17l0bWOB+kovDxFdj6x0ML5/uqDZKyGtbIixKPJ5UUp94OsOyP9xh1zaS71GLj+4K392PdY7BjVadqljkwiVbyjj3D0Y1fqS7H5Qtfzd/OzvFfKog6eybmkKc2kICy7rtwShSuYWCNQzBSioWWQ1kIa34Bzld6vylsJhYojNVEDQObSc/na4vfZrR0ZytY2KdQsq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

