apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgClL7F31VRbCOi/T4JFlUBPSNiws06r5LpR0f/ANzO+aK1qEFH+CYOI1iwMsx9OJpczhpxMkP1bbermfM7IKufr0xUs33YG51Ux9/UOCm7SrDFTEcjjmONsY7Hommbvn/5/kHqvehcZupl8Dkc4y7bIv/hmmhDYw2qCvY8uZhkuhd2TrEu132HxNqkDLNFSogQ1HF1AoUKUYrmdzyTFyyNMNqGvLlfWsBAu90HiHxFmyKPZ5SwlhkVyr7wcKkfCM10wygwhsnL+waKLKV+obL+40LXkyCowuP+VD6Ajm7Qg/6ZThU/gFEzXd/NI0msF724tmYRJIB9qRU+g9ij4VCEgQo3QJ7YbNYw5Mt50Y5xz385+FCbsowvb31qfLTFp/5F5mWPA8z/2i78ecC2U1ZcGT+u4xrplW7uTQLthFNHiCKrEamq6WNrKZMpX/4BanoXwLZKSXNymKyQ6Twz+m9qwRK0vYOTcVOymFGGkrysvuS/NeT1hJVhH+GGEMwOHw2Kdoil0Y5J/7sfsyyxK9DDEMEq7VhAUK1JnX/w5VogohopoOn708NdIQHJJMGfMX6ruuvXss3Vb4Qg9hBIDkS3Sqa11Tx+adhCTm05boR09Z1dF++yYAKAE+/1FLP8kocZz72oBC2F7I+1R6q+qhxtY+W7d4z9Qd+NMsGJcuoh59ZyUQQsZ7Iwr1hUb/z6lBTp3OmZbG6etgN32tWZQwj7sg94bpNY+zLsKLkTySt+HMqsp2/g/YikX5P3HL01pNrdIU+HeM6CH/vCtMVsxv8H3Ya6dKVpT/SiIr3HRkLqmCoicqS/UovLI40FPaEuS9FTcKf0DJmmyhAM/F2wGUNj3jmMJ03uxeuHPDr1JhyfXLU+wB1qWcuQp6b9fRBtk4ZQjcQfdkJgA4ePfRE/cx4kRQ+rAmhlE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

