apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAxErzv3o4zutopNioIihFrV763V8jBsjjtEx4jnAyNkEYOESZWW4ARLyY8HbzbJ5qcqS1o53nKWyliRLD94KC6UOdiqKr2LD8HEwh2b8GtRDZM23iuq6HuMEZcrkhMyX+gTzIyblUDnsqLyf8GXvgIKOa2swSj6xlOgoB7uXHLio7QKGrVFVEH5Tt/lLLqB/8/sJkyHfCvJeFMkhzvonIjnnknq+sNXmeSYmE2TkEqkNB11gyRQJF5ggFalCBjLxrcbwe84mMrWCWxwFx5urtLQjoVqeGli0liFxvevo19JzhCRuTTazKZLOz7oU2w6B7C8mhg8R2JQdeF+HY9TYmOkW71mTtZaIlEV7YkKRKc+idrnK1JgWxP5rMch6lwNgr5+/Ei2qk9Yh+yEGBGK5ELGFPCIldiWuWCRzzKzd40vtAExrp0JOIwN6lGr405hUNLXfxAjrLJiGoYajU3TVfazLl/7w+X1KlnuAsqG1QpbGN/37YuOgZ4VHWQz29k+LIvU7jiAGSzdMBBKRoWe7j60Vw5F69PSN6Ob7XY6+rgSylzMR8oO4D1lemcDwteuCgXf2Qjtm20yv9k7eifUms62o1Uuiz6WBXNSj3bfM7T8J4dof/MtwxfI9LZ32aR45/AXvSOLleeTwmG2lM9xoIqmLStVud1h4FpBPwEF1kSeyTtRL389KUOM9UnfzdSh+gz/ePIpO92R78szF4ZBMkLdAfQA9zVKq9SeUZvKB1QnegzGqnXx/8WLdQWJElvGnAQYSw8riROdMbL542WdL3m6ACiZT3EL/rOQUsetk0Un7b3c1or6S0eeEqNO8IrtLipStZtxHUxjJa5c+6nztkA0KvbFYIUK5uUfDxKlpMHVSMK7bavDE/lDQZj3WuyLzOiuQ50VyMWU/3FRKPM/5WEed9pDF3g
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

