apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAknkEkJ7QnYh4z6pcBL2P1e+GRado5jQf1XX9CHLRqO4Mp4VTJmGj4eLdo6R5swBmstEavT8ACuOMa13qyI9Q5apNLvui77x7YEYK3dDIrJbERQXHBVzGnfkXTKdbkw1Q0O+lzK6oq0Q4nPxUByHaC3KRkQeBFgqJUEokhsWEaNnIrcIaF9IK1KMxVa0XTznRjyPDgJLo0f6I/PH8shsnSljiBrvxzzaBdglsqHhM60FEkBK4k9xRnm34yctdWxbgJPqH9Vm759rM3Mor5a2DzKPl7oNgFYUwGmFzHEY0L5ZutKeDltwaq1avW03VnX0MDvRtcW7l9PeX2sNmQIInLu4dlmAPm3HLu/n7a+el2LtV8v6mzyInofOgjm/oQTlC+fbjwgG4pmBj3Oq9O/ez7T1CfzL7BzhWlfG85H2N5/e3XGLWgxfZrYA7CP8wDtN/ZLn2S6xcgs51Jnv62xAuLFWI2Q5Ug1FxRzSM2LZN02jMJe8LVl32oUKUrrtfqlv5papFI6WFbAOx/6hcuJWm4ZssyTN7N28qy5B36edqDU5Eg2BmqlrtBK8dlJu+PItuxq0aONkXAAosE6rAZWBxxArAQ/S9ftqqizt7/Y62bHzQ1RLY45aBH6DfXd0PiPQpWK+CG996TQ/IZvo8eG8H7Mwu1xuviEWC+bVczn/4/E4JccqsKu2k4qqPoIBVK3zqrQMO/4jfX7/cqRwDfAGlu8FAs444awxs+GpB3pbCFIh9MjJeW4Wl500EbkpNsG4atJ7URRZP12gxRo0xbZwRwDnof9/foUWnxjoivGOebWP8+an7SbiTMe0GyQWBk5wazR5jq9VwALSKB53gEzcIWVKjGmqhwDj7D8CNmQqDhOKVw5bRW/QPO2RzxZVitvvWoqCOROtEe7/+n3Cw+O7+OoBSTzDwr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

