apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAemTG/jPbrOeu8rJFegxfh2EqACbrMl2nxQHBBmlJ/2dR1KR74DBQjeEeKj9YaIu/75XENlAUy1uWNWZjJW91eO26aANoLFD7+Ob4feArNkQvSjLoRwLI9Xc7gcKcUxJsDsucbS2IR3KjSSQD5NyD+Q8Q/mT38YtQ0dirt5gnkznEri077OGhrl2HCuwS1NoK0uA28xHe378jbYdWHW3OUjE7sXwNnuScfomoy5olTwoW3TRxv/YpBUE+tJv1CJSCUAiJ/C/huVWJ8Uar0ik3j3ocJ1usgE/Ee1+oqbjKSVNQqABODncy1kxC1PpHz4dnrPq7GR/jNmOjSDk4Z6GAktbXNZD/yHZux4UTUwz3t5J6aM4AUP6tpbpEKv56RXCsdD8Rz2XkuQVMzFSBaB8XOvWomkttwqgCJOBjOFUmyMsIaZkq4h2Uxyd3jr0QsrIt4gxw+2jxNSqw93TFimHxAxN7htZw5xquKu/wdm7aRM8dqLViweEGhYio6xewWjiNhwXk48rRovjiCB+EsJ7gydxH7XAj0ZBu5JeI7+r3PqqkgH16L3l1g9c2KKCUWvW7n5wUw4h2iqEI+ad0aq6Pvb8jFEr2qOOEXKXcJ1HptaSQVP7MP36oJKnsclT1OT2RKS7OJX4gMJ9GGc2ZlAv7jq6KCosOnH25+rDxa9FpqIIWdFEuXBVFtLt9X0lsRbzk29RFTNf0zXNYdDuxsA9tzXo8hI5DGZTyNpkROXobdY4WGhTzrVpmOIAdK/yMh6ZpJuyNZrTILeJFpp7zMflypt4jO8QgE3xo7ROKACEJVV21iRld3IByJsQn/N16pZwKsWugkEve4Nr3jVAyEaRtMJHEkSBJNDugvVMVWloztJxKg/eGpqR9OEkXD+pYpVKmvseJI/JnBxn8Fx2xyheS7AIrp31mi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

