apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA9RElS9S5CKQU5cpekJf644ZNwdJ3QrwRI9OK9Bl07dBkLevx2giMFZJ9wG0EZhUd81rwDhjOOldR9TcKjY2LKgTjSpCaL+ifB161OIpFn0FwnRgyqQid12BkUd3awVmH1pTC4eYCuPqNzryO+MDrTXPXp7MGBaiE6X/7r/mHjrIz0wWhIDANI0vTgbsliTRdFGE4rSBy94TMZLKaN15O4LnGjQwLzILxBdNkmALmiQV4DWOIY1sjwx/OOWyJmU82OJ2JdOboUHzF3woL0dNBrPp1YJiGO7TwXAX4qNaM4wvM/anNQfqFbRnqWOgf3D6xgklR6tzGo1/rwXUrKg+0TXiKbvd/hJHQURt5HAMXUhFITnFAxRqoNb1aLgRT39K1wyEOVfrRD7e6qhPuo/qtnGY2HTrTwqv4XueofZfRDFBMgHsMGFSgb3KREA6qt0MeTXJMJ5HHqjA9Hwysdga+4VG7d02K8ZYXNfhTdUMr4zF2Xf6zOC4RFLin0HPeVyVcclm+Bq+hmtL50GrQJ7Z/U/+NIgoo4EmHzYylznj1FON/HPLIE7g5050MGHvQpocA+xTBOwuALvH8uP2/dZDoNxDgnJECnLXOoegYnW5pBqZJETLX3u63orhShCU+6aifeFMFieS6eXL5g4Y9484FHdhZDzItO/6BhVU285krurvai8lmovsk/lC9ib9FQRe8bGYUR+R8sRI80NUn6opbJwPYsWWxCgfd7N3mWN3INyA/EAZQcuebAirugUN1yXRyg3zbIbnZdpILuCBJTwmv9rYg1xQr+ios6MmzsVXvD0YBeF1I+k5gf3O39r1ElAwDDUSIVC/tjw6kFTbpj1EehLTqdj4gG7tKP65jkwu/y7Do7Bfkm782kBqrSVpVxFTCZ8w9MJz3fZ1fRomH5MWgawr+BiFQi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

