apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBCwICvC0hmhTNjONEjVnRwzaaD5KK74G1IGePYnlErt+qIXO25Cee2a+demGJdRtpLD2Y/pRbtwDIJuJtQA4IUloOAkiuBfoaoTYm2chrcbs4DLT2sT2fwln/QQ2B2ZG8VQoY/gP3ISY8NVYg19raFWRWKYV8bu6UPeU0VfZSXIFVqCLayn6kY+9TZ+Ew1EfLY4RZ1zSij87Sc20/6VwssopOQXXNOqK7OvCSD5Zwr6LWH8b7//H7b61abUlPmZXfsp/DeC+SHEx8MeVlZQCQW5kX2BXoFP29tFiCxWuiPap61LfIPCOr4uZYgvl61CkDImgzOY0VsbVCfZeN7NoGqx0ZGdXayBDS4Q42cGG+YqJn8gmnUIae9pkEaAvG1YEqpE9eg49BSot6XZ7L+LSyirqqBAga5yH12MHSUdcfLZQc7gHnAJwlYO6u4EmCLz0dJX5X+wpyfarNwV54s2+J9FDnnraeeRPhimDTVciLvWq8xGET4gxpxSr2pUhLkmURJeC4Wav6awB2S5b13LrvkoyX6/n/QUbC5aYJLfjeaWqaz3Y2Z7EeBWzBcxjHww8eGhtwYGYBrLNob3XqiXDCdR6zf3tyhdDLAb+CAR5FgaDAgj0QZiTuGM255PkvzxEZIP6GjU6FrNS5DVImKoHE1z38QnSNaph/VlXtw/CiZz/8lalO/BsU/qOxgvnL1aWQBvI78Doh5fRQ3XbmIg+H0UJOgvHsp5uqkA78Q7F2q6w02TTHM6ZqQUk+9BUgVs9bG1ge39FMMFcEydNqiD9YsoeI84Wi5KcgcK5MuUNqMUgpPCH19Z/pSfnqkXUw/lsRY16t8bBu8TmHTqpsLpi4AdsmtMlgsIv3pYLHNcziN9eD4KvGxLYyFrub8OcbcN9dzuy5ZxRnsAPkPdxDiUj6cTdKyinwb
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

