apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB6JJhIKYrB0jEwK8EluDrctQYxCIglUMhIvY97bCfHiezCLTiFhvyTqCEQ5VocRzhYh9/LjnAYDGYMxpDVduxXuFVLew6xF5ugrb8PRxthIMxsareT64fO7C6elY9jzHuXWoIZNo1dpmd6EftEUO65GFpvhFJPBmyXY3hLqRKb9tklJfJ57fI/eeEs2Xb2EEFkXjLfty2B7XpKCZ+KGResI4KIB1dyWLOH3DEYqVAW2Yopdd51Qm/4KajFDou2NbqnJ9YaWAuixvAublO1ooN/KSzPQqG7mZ6H2IQgqNItZY4iy0q5HIzUfAzj5c1l6K2y2UizD6h7OgT0sv8VCmC7EhwsTGDbPN4kEV3caJb7rnajjGkTV1TpmYAV65YS4FQtAQJ1LfDlFbTfRgB/vCd0Rxn4j4KYUBvg6Oh0/WH4mO+7UD5rC+SXey0c0SQimf8jgbpL5ojmyE7O7vb8XQH1HtESAk6vqxg3ExJ+sTpiabeUyFH98Bp46HMWjabs540xYGFiO3db2P6mzyE5NE85YIVjVG1y2tN2R6uSZm5UqmVFXUpAfGPuv3JOLWQd6v6p2caUoTqHHRMr/nxvavjQ2NlSWAvGjFiMh/3h5rgV7nrDAQ9ojRskXyPMRiqYOhQFT8LaelesIPqz/eAVQn79bq69ctX5cZg+wmQIjC1OGtp5VgXRCwyNto0ok39tgl2jwspACWOf9U9qfODg0lxzvBAfeeJmSDm7oQF56UXalHMe/5AXQXjqZwD5tK7Gs78b4F8m+a5gFocov1UY7HLBOcQd+j9e+vLQk19hSMzzGLj08fiwTsEUXZO67LtOQK7VkzP7AN42MsbVqpKm3cFydhyr53ulw94cBPqfrXW/iEUngbISo/KWbaE4BvP/SNQiMS3NLgCLqX6eLZlhNv8+RXSFKM2z
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

