apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBDuLO8JpBg42VLXiSyUFMiHmteOTY7XhNJM2vXnTDRqBWVm2xrjev67QJAZutBe7FXLbxGy3R7jsoLNreL1krJnO0FS7YS4QJmq62rdfiAzrL0oMVposC6EG96hcX/yUTQF/bmdsywW9JEoOBZdTpp5Ov03M+LjWS60YThEZKjH+/6JXbmzbOppFnnVoFvzYe3quT6WgBjqowSJ+N0vk2Lgk/0OCJmO+SOmyTLynoqzcdn+v6Tmm+kbMlFDC19/3JJuadiSnLik23bgkk/1x/1V9mDyEJ7sRwY789k0prbKCRK7NVWupuIlwJdGSTYm+CPoG3yOD0mGEThw++Oojttvvt+70HUrThF3MHUF6QcvhcbP8ZK3MLCEX3+Z/sOBxpT2RIgC6oFBK7Gf8JdlVvRH/2lErLIf8lBr6HXpEXNXvsaP4NLbx8f0JEo/lZ87cObSwqM2uCX+BOjfGv2djeHRTx+56vzXOxre+8968+FPVfbWoJjNOEl8ZBbjjoAXB6wKhNT9/d9p2jnS88Tgw4lYyV2IVQxNlt3pmMGERegYN5wn67a+jhDNjA0NIeHkHc+3hsADVwSOoiNm9eNL1ezEpirI/SAZCIKihwpHIiNSZdt8Qw2yj2qBvMZe8yUhnNiOTbB5O74r8uEFLyszGDhBPBnO7VMwibeP5ZGkWvv8AuNm2jrCfSzV1NnJSgbmBn09ijIpmGPpJaDuFOcXpXC4KfiWjExJa4KDNwKJYBLr0lxhnxWBaBD9YINPnjj/uFwK2BwQwHAd7nve/ni/3VDrWqhy/mKb/gY7A+6BI9biEoTFX8Jyreb0UcYpY6ZiXrQJa7v5Wx579s5PWTSZ6BR4s4gZifBMG7ejwlSolugFBGCJE9zhnm5ETvYjiFVfv3CCXdkV0jBguA8DQQvqwlgLu0yPbEB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

