apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCDPv4rHGNtshIYFjcsARJ5RuF7c5JNbgpu+udSD7oTGTCN5AaZX/uIz8LQOWZ1khs43BbMtBznv5MNE7QTP2PCPigzFvm3lyg/xevWTH6CwK8/dLl4tvLaB8SbhIz1SKhfeZsSNk5Ewn30/UxttHZ+bkdf1Wkyci2kMmxowA9yI8vNCzLPm7W793QOAvdPFGGSxXtwvhh456xsM0C/ZKvX3PHmxt6RiRdCgoIyqXIlkYbI2VD+l+whvYkgmIGFGjL3RtT2Cv6ee7Z2XI/PdBUfgYAW/CVYzjVhNe+yZbbVTw6kK8JYGZgU5srQxm3vzIlm17N68ykDmvgHipdb4px7Ja5MmFc+I0rhH91p442n2xXoP9Wzd8DH+HTq8xyeLqsMREeH9OR0IsZdL8OsoL/7I5m2g8g4Bn5EmLkoeP8x31cJ/0u0nknflMO1BatJfPXjXXkazMiKyg4jQgiPkIs1ZL1AkSC8lWf5GqHRClWapzkM5ZN+4e7HvGBzeS3Hl+u90yocq8wHcTv1gZvb9nzhsMG2vhOCVg5R7dGGhSMp3TXXIor9kqbUNXMIigj8ii8MtYAuCrRbXWFKFgdJqez2QsZptZ+socYzd2oq1XIggrpOlt4BjQJxhfZrI2hrwik9nX5mdQNP3+bOC7IzOy3WHR+grhXOUdRvFEdKs9evXB0iKATWolMZXp6JOMjdUTC2cwng0ln0T+PRZROUw1XQ0ujQ9GbriFgL7xZPw6MyffpBp923oAhRnAwRtaxHoqj9OEb1XIfasGpzfcCHcIE4YoJ0+HA6nf0kv+EjhV5uNuNPxDzqHQY5glnMlbellXRpJsFVUlQujmIl1MF8dkc4PZrl07dI5Ior3c99yWfmF4Qhe97ggDRsFhfkWUWRihVZ60XKUIspQd8abYVuHizJLo3jCgGK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

