apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCj55w7yFrF8wyTBH9J2AG+JX/sDj6fT9ESyOMeQ2m49Np6ebgAiZUQCC8dB2Yh7G10v22c9N00ybkuT7fEjEYa3KQc0BkbTSsewaO3PXvLQI4kelEIWxZ8qEp9XKkR1v5Tl80HWMLEDOQELdhJyyq+O1s6BP/AEKVo/9Zlg+MeggLTf9uGxSmeqOYoVhbDaL+Ut8va9HVgmrAVx1x1q9fDItcnEMDRoJcSrLqv9qFrcyBzdxC7l70ugLVWkMHEaQgHmGAu0XEBNp7/QZGH0dOzuQ4JTi3PBwJn6JOJW3wD+IDFnfVgO8B3cgzkDS6fd3eWkDd2aGcmdBc+UBovUnp7XMg3V7vAkGRoSMVLsNb5x/Cxsre7AS1vDSQ5BWAG7POaetjNqK8kBpbIbQcrbs6tP2gqq4MQoL46ElC3DAUwaU4v5Mmy5F8q7QOu1M80OyKHqkyHfw9UW542k5tapDT0SmMMOxIK0ywbPSyZHnEgWGtAQFxP0beN8cspDqf7Rofiei+Th2W/OKHydJ+fxZHVXF5/IxVue48Tnck4NJyx61j7ZFFMfYS1a7FdC74y5YslMIXjq4r/g1iABsb2UXbRmvOQipaoPwmYV1LRm7hDbEZ1H02LaFh+ExiN8z54tbcFFnLdHmqEyeNlesjM39U1VhyN4Apxfha4Iuf8u3K6i22+OX43lyOMNaBAcKl2+WCPoIOq/HoPsVghjf4xzQm94hS6LzMzgQ3Wrz4Vg7fFQFHXB7djUl0CVpuMNykPbqkHtegrGjIiHdobd0CpL2jFZwSNqkF7FJh2e3Bn84OpCRpAGRX/Wf6Y1XErpQvLNYh9oQ8vcQFsJgrc3C1Rf4ma9kIGFOV4wmcQFnyHAZXDQLz2kc6FjWOV9NCeDkRrIXSnDuBabOhYP44oGBpPkG5rvO6oNnsl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

