apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBEsvS1RKpJCbjOQRsJ/AOjK8eCcMjXJik0Pb7t45A9AebRA1Ow9jXp6qAKlCoeiANNxrISVZuJyjw1T1im1ohJBHu9jK41Cw/T71BKHgDLme6rwazup0LrcfBmxeOjgtsTlRs/aLCJ9G3lzLnQLMxhf+PuJFoZihVoW3yDkDbRXG+BRXFygAXRkMFdeyWVYdSQUlXbsk/jIHyLY6cAz7HlTsWtbd6ikkgD2wvCCjr9gHJvWkvMc9oZ4kAE/1w7G6VlusbZbFooKofhGp5xUj0vsFJhPocovXZZsK7JiDql1ADiV98N8u1DvXMCCiNPc6DCEKRF2UwMoUiGXQqSQDSR0d2fEInSVN+8AqpFJnCnyG1kmd0MbjMWb7AaVG74b+hTTaS0mtKsDmIkytytHoDz/LeysP6I8Gxv2fxl/FG9P0V/wC4Yko0Ra/P3JRmChK3DwNHAZ0clJR6xJBTvyUSMndtbLh2l39NV/N3wLnFKoYjzNRI7eXmRw8fC7XL+jKl3yw5oqeDvKU5OJ0Kitv+WpVYhHbNtp3/mzVoShtmg2s9S2HQpVnhi78ZgU/gsPaWttYqrMrfRAOgpumtA4ilPo+2UDiAG7Sw3SmiDvingKC8vLG8bC+Rji/TD5+cHwceIMxQws2RHtgNYK4mzt490Rjr/88zr+Y+wf1m9ZNxrm003gmYSMAyytkiR33Wauu7EjUyYndkwgy3Hu3SGTF2z0hKqUiS9cbBxJgAZirOrUQcyITA6DN/UsY9DJJXV9WbxcehMLKP3DVdEYUv0U2TxlAk637zfwDx3eONHls+fhvvWUSzaiIVbV/9ofOay+Sbffj75fOAVnwc3jvhwSnRpRW2TOV4OU9Q99qO0R62nKqsi23FXhExce5rpOrM/do8zK51a49yjE/kZTX1yLv857k32W2lW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

