apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCTjLMNjO726gid+IuxvsftSI9ykk7qqqLEckdD2MptvtcDcL/HZeRBHdo0U1wy7SmevL/PqQvRdJtkpCcETXMDAKLppi+2wPf+U5q0tuXdgh8ng9sfnLGYI0MZODU6ZBbWjXN2Z2rKhbdL9J48ezoSby10ldxGglPc94BZmAu56E71ndohHVXgiKXuvTsJgc0a+XI/LfjlQVu/XDjv81+nFFeA7aYH6HfsuJ4OGC9Ty0JC92fPkJhqj6WDhcVUtOslxAcem3T0P/on+pTTs6jswG14Grwhx/V47Fuq8e3YqHOlTHP1DKI0MqDSvn4HEa5IjRO9p/QTnGS5AOU5M9HeaquIiIsO15qflDazFiQvGI1DFZ6jIPe2EyBETniM+JQC8RvKsb+oFCPVHu8Yud3QEWm+YhAY20uzLHfYOIInkC9fVACDf6lGDnwS26L8wccn2Qm0lRbsW2EkIrV4YT9zPXlXq8INpUkMGlrBWgSRAVwqwvHX6zZxHMvEc1iduW/QsTDzpqfRUhw+Z/m9FUB9kfsU0H0qe7VX/kBPAvUsm3PaXzc0aBi4CG9seEeD8fA1UqZQ14VMsIAMECiDQVaDPDOcs1unIg8gbJEb3PX0lSM19ZACHSWs1NgUlmt6eoXstFzvog4HRhG+XZy6sdJwMUq10EbSqBmoqq+Z+iAgH1EQtB9aGa6UQMeNgeuc4E0UByORLy7IhDUiwa6elOaRtUT3EiY968PCMKUKx9f/jW/Fre86A4jujwtXOzyEtB/0akgdchdMorwv7xn5errOBvOqFaUPnFJEIO+HdCvB5RI3XuMJVu1xnGjKdfuD+wyldz420J3WsCE5DBhPwYahiWHOd5//hpEc0Sbr9wU6F+8mUkF42XxJMQELu4AEHPwLY2I/5aZoKyY3wDNWvO0OyJEunBzc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

