apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCIgKCK6OGd1zXVSmW+v475zLzPT2pXZr8+yAEJkhjb3S2dpfyjNAg4NCePI0nQte6p8T1jhAbeKVawgiU8Xmgkg+BRJ/N4Zq8YkBU+qjXKEQZ9XYn7UIKINQo+YhioV3dqCKWgNd8g8rXK80FDct6W+4P2Obw/CD0QIy1vsX1pWYY3eCMWyVeaS6CJud9haRyD5QOmDeq8OGg3NI5CtMsArltiiviCYCylTGEaIA/84AziNQ0SIVf3ItKsCy4mlBrrUv2en2jANN3NpcBSiKx2eBrH2v45DT/g0dSpkEkS5qUCDingyDtaJ8lgo150qTd2A9OTKFISD7yO+k3zhLZXBVkvf7hynYwEBm6MYXc9bIKGsle763DOKTmIAzxj7dlacMSZ9cIvh2dT7OoEWj4KiceAIdK8ZWg4spXK012uvqg8ThjI9CUHaiJpAge+9/KKeVNQIN+R0ALCACOzoObPwb11iM0OQpN8j+oghyoK/w2sxf1mt1U1CZ4kFUU5/U9RiVwmWfNilQn3HFvBUoeIeZ9NVDup+HahR64nMNxC6/hCUdL9Dn8YJkAgLp8sMjRxWnHJlNqjLXqkiAO+mavBtY8/qWPpgJTvFfnilm0kfpnMiu6TyM0VlSMcsg2ZZnYnC+BdaacyVcS8zqWhvyBt4q/BwTkYUXYKqQLqjnUKoxb/RgEw/TPjVAlWS7DM+HBZdc3KCJobb53pXHR+f8shIYZ5GAA6F1yytKCEcGRw9J0ct+7NPHMzvtoWe/tK1hZ/m2X862h+oUBS0IBPI1HZ+u7FZeenARPE/3aNs8Nk/uLPeITxV/m9hzdn8Yebi21T2bSa93AGkBlSuSbKu0PbNkS4+NU7r/gLModHRCIhOsLk5ZJ01He2GwLMvZWC7IkV/j4Wb1X0WLFSF5/ym9czNQwwn1he
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

