apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAEdgcHKCqWX4veePO62Fij43xaDz/Ux65ydre63NGTg9hJ/oBdXc2cnzVZgnrhsKQRQ9xKtwsCZQtaZ1Z7/buUjHuIXVI3pAU1I7VCcyKw0JIWeZfseor34XZta4q3gAg6c3ZfO9/Vi2TqfO6DpcvoyYr3P0T+ePb8Ysv1ZO87FmRxDtRYxtu63T836qmCumtwuX1W0Z2s9LSCM3xa8l/dVONaXAugdDLz64U7q8X0rJsil8NtvII18oRJZZQPM2A10Tx2fwZLtE5hzM+VGQlsa2PmNjb2hLUkai6Yf4xTXjtYFw1lhrx/NcA+ySYQKeKWavFHQiZB6z2PUbXfamxZ1zVKJ33YM5O3ygVMB64P/Ylm0ASbzlut4iLdoy6btt9axWtx1MXGKoAiXQ8M6ySthqTfeG+5QVvd+PrSNr6cRtyg3SUO6ANoNGz2Tf1fkOiwqGtUg7QTGR/bKXCxk5ezhgL9vXyIuke18OUg8zF9VSrrx6pVaDL9vYVMP8fdEUZ6q1+w//SGNhxZqYhTDeNk01anxPm14F8g+8+CtQRgAVcPvv/nTfAEuZI9LFjOmXW5EgTdGwI8PKXS25IQP5//LRXxiyZtjKonP0b8zAr41zpEZnd6K4EmpDvQE4ciyx6cvQI30ZYKBFPgeZ2qLmA/fjed3Hsu4sZx9LmZ22MaMlMJhYjVYKQNrYJEDlVRssmcA2TQtXLyX7mOQmVlEkYjDICWmWPNDeOQkUkuUhC6mhSJi/9F0Mt+LX8+vr26Kf8vz6k16gPtgQNvKVvzUWUH7aJUtm7HhbaDrX6VnMnEunLPavAras/BmH7vTeXRkSXJh1ClrEfEEfMP4TTcO8ZQuoH07VSTlAw7d7Rg8T8Tp8b9lD7b32KzJd2HFy6UBUCNdWQvh0lINzHNxrlga0kAd6t6AP/0
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

