apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBzWjpyBWOJ39YGFUN3ARXOhVA8yWJgj5zIrvzbJgq/QIAreaXVcjrnhLn4Yk95GIw2tHYJV/c9cCU5EmaXU6wmV42SxVVHT1qB6DUEsPeXiNbp0yAySis0ioclj66tJG/4jn91yvGRaZtarVRCkML3ixtILgMpXpys4mCg8wGeo6SSRlb53XSpvi0tZdF27jJoi/K2dyIF74G5PQSaUumRGBQuphpyPDu5AgRgcbuPLT4JoaPoy4Hhn8LRGaLJSbJ4evYjUq8lZ3Wevd5XdkZhERKwWnlXVk2DwCTlpFEAfaZYZIreAYAktAiNH+J0eawN3NC9AtXdTj6YUfwcec1rb1kRye9+7ay95Ugdq9xs+Lzba9t77HGlOcdLLgo9sVSYq+YULegJB9XfXHobee/y0S89gvabkk/vFpwyMDSk5iTOyVOUoyCnmZG3DPaGgqL+uykxy25uH74Aoz+PLjRZtA4b3485mW04KhlIvuyA8r9CsmYzkmmMDVjFmy97lR66X050AelMGZl3aftWyhaZIFFjcdXxgGfXRhjiii9lWgOYtgg6wPMnDFeha6BqrcM9A0jSBxxUU4kX3cl+0WEnWDpAeJviOKRXwUAhY5OqxEVRxox49DatS3nDG61f4TkA2u16cpqx8a5pBrmEpgSoM6vOUD1NgpK/UMeghu6ddFTaOwIwrlaVKBeL7JtspqZbIc80uYHGASpV7jPMUlW5Q5zR1ndW8BTuGCam3UiOxx7FQYSoB/ZFPi8nPaISwjqq+8vaqvvNIDIoFp6eH9CkcfDQPyg7Nw+Ol3bmWvgQqdveYF0CFgaFp6SQU/dNWLo1EIIM3VThk9RXMXB4sPUHorUvC0upv0UqrQMOgZj3dT4+nOD5ZL8QTUdYXvn7121zShSmgixWg37djtqcEGK5OmSV0CFu
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

