apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB539fPUvIPb+ICK3/nwuicE+aMzqO0vPVCS3rDbASkIeBLV2mLH7kb+7FqpNRi5ZKAXjvSp6L4ts8YE1Up1f5hZ4GE3u8RemEdoC+XLMkKVZQeND4UpStfL+LVUvBh4b538MPbZ9d4HxstovRp08DoV4lFaqp2/lDFrFIMVQdLEZkFrgSpPqRv0X5GIC7Mzb2amE+Ys9NT/HIGC1Y+zzlTPL9WKzNSmaJ/E3iDpmmUAgDvscL9/vO3xAuKRZd1+zgMHfmGQqCFkB//uFb9u2Uwt1UbU7Y6igXB3vSi+s/WUCVMJvn2EFLYmYhc6WP7Txpk0FP5tdn+B7L57HHyv5u//ptZqB6zXjQ1HRhW/al+EDltkkH+dsIj27eQn51wzmc3H5h1Nc5X/dCqcDKqF5RdWa6qDWy/O7YFNB4VSPQEgUdr5DqrqqbUfBNunwOLDt93kchbdsc7dQ1Z8iu5F55MJg1VrgbpX/m9RcyDtnSi2aXcv4DI1Rjo1CAk3l1RW1dYOVdS9U0oXcxOddN9Cm2Of6ITKwfrniVD0WciDE1phoqLys4TEZZ/ayfzr1IvLU7tMP5T4fnsqQBvEVNide7w/hLp4+3RMCrAiYXW9dG1lgnKMO6Psx6IigUBmO6C6SU14SMR1tymY/w7klq6Ch86SPTaEwixLFK4QWzArdgUiPcOxFAiX3GELbrWrIciFRnoZJO0xfd+5GnYAwq/TC3hleZC5PxyJKUHo/1mmYAgVWSnnqISvYiiaA7ckrlZJbUC5BjTnfFdRYrqpXf+xpCp3rPsVFgujrEASKmzKKc6db7rofEJFY0iWMzS62bcitSQ5ILJGLPP3hcYjHzMAmgcZOFDPYQrPjOq/Cd2MQCfBKop+8s3r8pxU5hFfOfjfrBTnu2xUHWlbYm2PMSHwpdLtjMkFJH7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

