apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgC0fpaF8Uup2fbjicLQAO6pF8SSZ2mY0hNi/PW4ZnVcjfa9hEOUcgcuvf+ZVNefyxtbNBDYnAt0mhjbG5u61fd/LkusuT88wb0hUYhFDoXbpWEB+xl6r7qY4CeOhQmuDNADKckfV2wc9G9KxtxhPAg/jgqWRjmicd8Mov4IovT95AhRn0gUAsvyBgFtWIIyXz8XCFAlGS2llgAiouRy56YeA5s+M4K55QE6BYKZiT379aHtNbycZVhIuv2h34C8Xi1Lcan/Tk+gWsf1T61mupvTp/XVVEVxAjx+WkgjYFkquShmuuJlyqky/p9lN3tu/ZtWZvdOVDdt563GfjWsYZX1YP+v9qNvl2JHBvAy4sN3rLvmjJ40KzNRdK4yYcAZ6nUYOLk+cuiS+pNeAyikaZJiJ9RrI4PAJuXZJQBRQJi70rCVSy8S4eE4M+mTeM9ESsi0IYQqSQP+1j7JMkjGDQUwlMbDsVqK1H7o1Bd5KG+znVtK2GIbknerb1isdwuCG+fgXNZN6FX15D+tQJ5yxNEpxv5p1L4cn7xbVCIrKdeai0AvtHf64q8rKrxLkPAzbaddgknsL3tSW2jWlxkWqGwDCD1fIY8tUb9tvMWhVMAfyyWSTqoP8d+UXwBlmuvmoJ8eB/aWBpeYzREk/CCEjfNBeZkxNv9xLICLuTL7o75706tCGIeJpURRz3AifOLGkYJGtHIcm0O9TNJrACVwMkyeS4cQHw9JGhoM8uMzTvJSJrsiNfK9rsYXPv9kj5QR1XEZYW8EEziCErg4kOQLPr1jyznqMCrjZZC+PSDa1LiPYebUZC1ewVv99i91aqNvphl6lKyvn737Ey0rO1LpbYNi3CEmI0TX9bRSTDDqrkktizQft6AmYo1VLynyth5t1rQ1mm3zg/l3w2R7JTVxXVMbO/SitdXf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

