apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgDO3bySYVSXBVuPFVZ6rbb4z9JkMTw0KLjMpf76bjKWfZWNMWcTRMYb/N7QH3DzeNGmEFJrbhgxjEEVG4V3Fy0iKlvj2P6HEP/YNIp1FiflBBsFKA7H3dSL9uoBXYdV6b8IHzT6wCWLq6O1nMiabQOmb2yv2i/fkHeRuoRdFPFkcBjnUq4lMAnMLaWTZAaFu6nNnIv4gaKDnvDrSNyp4PT6XtAKQvx5YbwvJ9OmaTqLMCLR0lUQoBT1T+K+gAB7n1eVu/tnC1+QuO20U6YvDJ9Y6AESGsYSbV4PtHaMaYRPKRxhDgFm03F0g+s5IIzaXUGFn9NW/WDUVn+zVUMZKFwxechd42d3XraigS5L5WPvpxW9ZuxA120LwvxWWfgcRXUoyvQt+Nw7b7IV1S7A9pP0rvJ7aIvl1gHLcgH+nAmXdFCzLbXrHStVEYi1w5LZldJiYX2R06+ohn9u+KbXrVmvaW/iE7KcAckIGCJvOjJmof0oZUkixnQC04DRNfOMoQ4HE8eSlwnysGkOxVZGUV1GEKpfVC6Ne5Fw0nW6FutAKUNOKI4FTiqhLj2SqXhkXxNoJ8iNzIWOoMKGDNznBXuXn8uRc9M5StReXX8kZJFwfv950UTO9hQi6m6Cp1Gwi6RPkbRQOOK8Mrnqu2BkpilzomLTcqhTLA8v/OdMdKERtmGev5Mbp/Wk8V37IhN/5furl8Ld1Zpwrijy/4q/1Ik1kz0HZ4+iwV+XWlOlYSHJWkSZdlbwQUawkGHE4P8+9sc5JGcvHZQHG+V+MHAefai3X7TjtBPD6/aQQdKLehRuuc/ZL7Wm1O8ljs6r8J+SLofg0p7sTQX0PDWPS0B+04rTOiQGbowEMU/BpW0h/SkMpTcc+0nnc8kgfQYOUfc9/9m964SitBmBBh/DZg12DcVTzPwHkRZM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

