apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCs+hC1SGgKaltPKpqVOBOjU2RAZluS6RdjCgrLD2S5Vsoaa9p2X/+jkiWNF7wxC7geFpOaH2I9JCX1DtH7JZJGvJ3LhEWiZjrfNP/RLDZhXrvxvnadynyVXAubM3ox24qiuomj+eXU3MUA449mnLWEJmPCzJ1hWLk+6Zktd/gxMrSYsi/wiqrN3gmuR+nP7FRhVej79MINRBAIDmYzALurbGQjnc0fLFjVUE3jNm+J5KBzTJuwxQsoujcrzBP7FieKjAm7kbUm1YvT8MqdFKx9jypTdZfsiaNAqo7A4KBu7dnuxU6xturPjglEO/wmwxBkMQYsURYZBsz0CuhdU6T77sHd/HrvSpdDoBDaKyI27xsSgCVFSEdKGeMbUzJMFNXKp2tBxsTTR5N8MnCd+xyYNASON2kCC5SiR/wp3Nb8saRNE/zI6EToFQky7Qd95r7P3BenLFewwTEzsojE3ddTQLV4V0TWxZPx1ONfv+RBJ3aNPCsZnzMVAbPqp+PvvruSIum8GMkRCVTy8np7tsTbUhtGY0bX3EuKxtPQQqhzAHMmMeG1tr2h481OP+/BSV5zKp0k2PqrIpWu0Uzn+K29w9Ypn1X/JnRn8URGWJPXMP5vWkRM3/oyVloF4ADiHk43nLguRf/HEUDx+d+iMPBXT9D6ahZocymbavY/c+lWgKxBqZbS1pQtWJ16KgECfIL2JVy7PnWg/MUMoRTNSw/elq+4yIKbl4W/4Tf2S2iRcj+sDWp0ElKj7PhYXocLjXsrF/i4Sgfj2mkzbi2UJMnJ+UnMKu1u7R0DugRCNGJJGX0nf5HEGcDxuzdujO8XIBmOwqns087AdLMbwxGb5KMyUt3JsSCP3/r4IaGmTxqZKuzCIhB7XnW36ZC4/SKIuOXxszSaWd2JV/vuxrZPKEXXtQ7mUCQ+
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

