apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBzSUePWB78nL4vrWS9emmov3ZNOfJOmLyW9xCBChaP4PnV1vIb0KHsVjhjbH0+Qg5TNtOXOPnVL+lnACHN5netOXum7D90cNdntoXsJ1xJFc42tbFbnxjPILLSwRNCGyQ/Pm3TyPTLSoGvZnCVpviWNqYR+XouCoPXSQWVUnhgVrIsknBYfS3feZ+82XFm/eZ43knUFrJUzo7zx9oF5ea6nyYAqotYr//AjVwUuAwsI3tRT5eT4qFBnwGG4HY9mAH0/OumWFTi+XWceAFzOiFOT7TvDt8hpRx7/jX50TGDX87RYFoJWg/87lY2hM1g+Cuj0LAZd4n6sSGPAwjcdzd1Y0EdkJmJ59qxTJAPqNNqlk3T1aFcRQpoTXgNrRwDDkc8Hoyu+dYCZ7IBX+rGw48FkotzIOh8Yq3AFcs4XAsA2YBnPrLLzz7nuMBuPBJssi3hPhgtAZfMRtt7SpKTqHAyJZZ8mBCVo1Y886VaTik+YvbZ3u6aXVTl5sg8X260nKxqEuC6xZoRQ9CgK2Zw5RyrKfhWSHekgSKQskxfY9nnYQmeajAZAbQFlIu5zaLyHGop10V2xB0L8SiyifXrZzvA4p7eIRZTdZWlry4l+9ZEC1xB8VWI8isFpMgVZg80hZ8aDB/TrYeUcVx3zQLIU6zP10EBTP9swnbECVVhQuuTX+4/JTcCBTirGBQTlfsAGdkrQKzRdq2HQn/Sce5zvn3q9fvLz4imLjQ3HAKk20/I13CE+UQd/5kImL8wKiAewiEJr9ubM3MKDT5BD9Q2mu9ou3uOIZazZVVYcVHKhKktDRFVPzZQp8ViOhSDYrdfXW6LbxC3LJi2ob7TAbfMBQ768KxSd78RA0RFVXhjnLzn4DjncwhbRGYYu3NS2YpcyY6e1mHXiohEyQcDjAfuon10c85jZVwk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

