apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgC051SALF+/neixGQeOcjsi4uY2vZLXAYce6RDhzXAyEcFSLyfWXXoYa1qF9Q7pUNSDKlcKFUGZDwHPqV5moLwHDuJbtRh5JBMlmh1j+P2OjyOXdAGp70Nj1623lP+n4AbcL3dNPAOGAbzh5XMYtXBpFogtxI11GF0T8keWjN2TpKHh3rshIuz2ltRzfr3cqLhNmFKOhbsabPo6jnTiTsDNdcv3Ab3PyA47X2B6qiCaG7+xthDr4mhDPhmVB8U+csafsEhj7YV48hsBRok6LLLYtfmXU5fNEojMWf3ncCM3CTAc+IytaERkFzcVF2PVHV2R8/FcMUgs3zYWFEHrkWHRDjHqm1CpKP+QmUEWBnYu68dZzU2OHAzLEsW9hGFYOSvpfssWyKrH86fU3q5MDjRsA46Ev+HgjwaJkE+iLhzcpKzFrbwkj+b2ba7kn9AT27A2rBvzKUtK03tN7sO4mr0cGQR7Jf/rDfVkU1z+ZmM5NIOAHsPgwwI1m7EKJUgZ+dqhM144M89ARTRbc0Cfj1LhtQj5uE6yWwuamcUCiSscq4f81nRGBEb2DvZCzvZ/RLwusqVs9icy99MQqkH/mUAHk34fPSLlPSY6R1II3Q3dmnOgQSTHkDnYacdK69KB4NFSKC2GK+2MwkYeH/TfyDTyX2hQCD8ezP151gfg8K5RMQ4kwv+w7KyP2idGtng906AHD8vmTSRuVNnwI0TCF8aMiYeUffev5FLGO9S5OcbMCy6SLf5skshAmFMUGXtlpvgr5s7ehZ2jSnc+nuaw9hQUGh8FlpB6Wsa4YVYU4ImTU9WDYLVrr3ucRsEtNzAq9rVD4IcGHo0wgVD2GPFNX6VuF7PRm9WcoYdM7rabb0BLFr0hbjjdJucgGYMOa3RBfHx/NUxRFepBgPuE4DQDXHeCEFj29s/P
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

