apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBiyrtYWpP3qM0uUPz/vnk97ind81wcjqkZ1XHkOBELE4RxtSnkUv3LuiwG1nZUDJWPHofd2myGaEVYW4E5vh1sfpIY/14OFkUHjniIgZEvzzuXVM7WW40nQ5edf5iHlOxweemHOqHuEh9CCJrH/xVdWTaXYK3RNPlYJbXZsB8yUnH8YxnCrq42aEjWnXOtuyvGfAceMDwbb2u2a2eW/8ZEqIJPNWRlx4vdkWUI/i1gawWGeKBR0IZdHNxeIl/VjYOrMXWNHTgJ9vx0OwdpUX+OGY4wIXFHKn27v57G+sa+rbvNIKC9K7T35B0Y50yW0Mi3OtKHMfsIFOak4KQE7TX6btmtQbkOyxrjDdO3dw/Y/k9Q23kOifghd2BHrxOWLOAouMBs0WJh0OH8DjxfwKcm6hp7+JZ5mP/ZXe1XRmntPmEGClrUOkmF69N9qCjTD699jGlkxJWTm5DjfBC565qBwVIyTTKvtDLP5gkI+LIoNF2KzN0OgRZqiMU4rcSFJscW4OXXG5txtBICwt1ekyvC7MrUg91y1WhBnbfct1hIr9Q2vYnvG3VlhZbK0R2d/gB60mByAj3aIYJH1BM6na0cguQQp+0b1gbdnNb+kQOBEWeUAKNU5hvIAiolt0sjjXTfjO/DN7TRXHNbJ2jgD32T3FNSn20L9EjtQXhE6pj+VW1tSRYicvFrhpHbAwxGtMYxEhh+//F+dsrBWzD4gXW0vZ9FJHVVV2yr30ncdpa12cPjvPuDPmIkLcyunXddaDBYsW6wZKLIvCZ5A+UiSnh7RGsrUld2HTYbm4TU1RMGMSEyVaaF55F148/9rO9Ne4x72L1vwXLLp1FDD16tbDBLB9B00X2VJSSN28iXO+OWKFMDvAUfA1PBpsiU6OVkJWBCY4XZNpLVlzM60sX4+1ziHoSaxQKQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

