apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAVYLzOBNeAELuq10w+KyN9uFpdIKm5KU0C9WtNUPGccMRdJqC6nkYRsMV+mqqe595D5qQ9FzCP5F5EwiaysOrg2wjHgENKIFeve/WWmCdrRM9Kuo5DWG+qfaWhoIh6I38JXMZVpdBCysWR8kNQQ+BItj+GhBBhK2vB9GSHojiUq+waJPDQq12T2OG87JfaXXnpnbCX5Ga3Vos0n0uPlbAf8VUGL/DKLdcB+Q5kmSMP2UDYMkL2InduXVLG4IO5vYs4guuD5pzGDSecHoEYdTfGjroNBrQR39nQIlwwo3Z9RC9aWzHtj5AeHOlMP3o1CxfHNIf7a2Fzb1FtpHI48vEh2GBrzc2OPHk0v0zjZoe7dUG9ceIxu6jxpG+U0kjMB23b9H6zRyklfUJRxGCdpkaEBf5eS769fMefSjFZYtZFkyRa3QLBEoobccrn1s1h66yMdAYWHwV8g3aZ28OZcOg6Za+dLA3/zTFSA9iUzdGxHsRF2iExdZCJSG8E5VacOqg8dmnWPAdXlNG4CiHZcbrbavyoWk1H2B94g/5rCOiS7UZzzw+x3lO3W+pP2qSI5/cv3QxLWZ2kl7pGeWdLNUsx1oukfXr0uQ4r1y/x+NJgCbZyWYGcSF3gkzEw46mZwfrSxsWi+68ZcMuakYF8W9c47vYLqVdi2Xpk1dzzb8fCUr6iMDyaVs4LtPqO+ypAJejMU0IZgoHkRHeYFciKs+5OqzBfjGXvepiGkU/Yc2mT89Ib75JMuUCpEQf47MdJ6wlKgsEtVInNGZTKbubb/V3wv+6eN8S/xousXsvlN5cxOlbnU2cMfrE06Pii7yRsy/yDvJKK2hOQOR4xWl8M3MR2s40NILmtkcusOEXJsduTrgPyJizjuP2JAvNEv9vPLtodwu0hx2zDkDaBSGdQ3chswIP4dmSm
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

