apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgB8H0F3o/98DrvB0TFVwRrgF7Cp6hsh2BX3vhwNka/pvr/p/cuiV2iVRK2tr2T1Nuqw3vj0/2VnyZnAjWLpHXK7Qwq12vu7vQtaUkq6Pm6XLsB+AFJw6S/Br9Gsdvesw5RfvkZ1IBaT3uFe8DpeuwOd03jV55V116qHrnwCQXHPGjyMWD0VZG23JP8cO7VZ32uTVEkkVtSGYxBqzSmNSQb+Bx7eHdKJwTF0Mq8qhWdjDyAVQlDGc5SVAtGjYUWdl52YQaGCkAt7uk4Q67wxAvvB9fLhys8ICYn1R0tGkyxHStFQMsVvqt5B3lB8UmaTW+zAqIxKyHNBsYU53J2a/rwXy7/M+q0Ox+JEC4hxQMh3CZWrHTliZdB7CU+mZeehgTsW7EOLSugbYV57SbJlYJfZbcPpap7SfSRZtu3IyrvB2GjHlXYTxm1ifKtNugcw1tP/h17MVLsTs2qbUVMplC2l/bIMdHsTj3DrrdChTRAWQAxgfJ+JXykoqC91/S5t5JCce1l24+GkIQAOnTa5527RJGvKyfph1+F3EuCgZoficB/6KvcKd16YqMTJA3DiendqaRnJ+7Wxm8IBke6HL/dwACcqKzHR7tvl9cYhlwpZopz4n65tVWAwWtghpJVjLn0Zs4+wNcCSUvRVryTT5ZFqeB5qFjw011R4FAQKXYbpMv0APgyua6weWI/+E0uwErus1Ajd8RfH2lgjpa9ppcGK1EKQOukDF4MZQbaonXPLNahOzGqn2qncyfkM6+zsZA3jMHMGzUXajQMgvH4TjR3mdMbQZCtVuy1CUvYdpySuL9dvrFrpOjfr8VTlt4Ray6bd8e62rxLxHlchOY4sYQZ+7z05wMisYd2uYxOuu+iJekBYSoMaXCl+OewYy4GckxtGBwj3esX7BQ19vJ9dYjIq2mTOx/NC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

