apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: longhorn-system
spec:
  encryptedData:
    .dockerconfigjson: AgChFr1KT+OzohrmXRFyyV3yK7A1vE1XUQlZ/lQbvC32luca21NbQkfXtdM5lIV/aQ4CEVoT/mOxBD8CHXXQB9rjyb1JK+9eAspAsrdZUTQdQ48EPZlnbA5Cr6CJOarondGk+MURHyuVRYEFIywExVLnZCE6637mMhRZagQqqfPwqiF6hGKs1vX11o2dxOce+lDroFR4H7Qq9M16afNTNwniuNYdX+6KkXXyXF03fj8W1i0Tg67gaVNCTuuR2qa3KSzl50qrw4pv7JOPSMwFMuTWytjUbnOvD5Y5QfJuEXma0ls5vUMJsDXQekXNke5v11DpUczDM/LTaOKOqDGEdwdwU903Q6vFixw8HC5+4NatvKsWVPS8USTYbGl6RESfWkhWX92AscYP7Armmtyc4gdqFXNtW0TsIRAcOv9MmhKWoVFl+Oc8P+/DOtkrBypwhpqteTAySHmQ4vynxLqJlX6d5IzYQ81ELsEx74GVgMcNcq+f8opO6XfWfKlbXmruJrMTIwgtvkq9IAO5fGdLFTWMGgHJzh/gm2dYPtACEjfbLRWNNXj715TSyIB5CxxzoAgUFa0X8ehfJWueyaYC8U0IpQT2aFrscu49XUA+vNdAC1o6Iega02fWUt5cDtUijdSpknjlBEGL2o/vi+5Pc6IXiV9Mk2UqKxCgdQGWrNlyeFJWa9FXDD7xEBY1CWAs/WZTZaFQfu+ixOaLki4uqT1pVFogDQc9UOoU+n7MpsXmWQhCtVOG/vkkxsjAX3eNXmbqwLydk/FLoL9Bejzs3PjIlQznezLAHhHmrAVZ3aYHGNkuBiTQ0ZGCAwrmDPbVVx/JYNiMS8yQ1UWK5pSnYJDP1Vsfb0sxC+sIuGKWXK7lmUP2c89DNpVW8Q+EjWmA54HIE83Nzc+xTdqI+BWJOfERmxi86HNq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: longhorn-system
    type: kubernetes.io/dockerconfigjson

