apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBT5UG5+PTVqiq0EiV61xTXOK1JeJtNzmZ1eY7gXYB5uT10C2EJ3JhGBREkJWNizJAApuQOUXZ9G5pItbvR2DJwd7NndqiNHjFoZ3exNAIdH5Al0yaz7aGWVymvlTW+DMOEiSu6VV1i+4rvNsL0kUfvylLaVK9N3No+WSB47qpnPZVtdgM2JgTF5w59mjDyeNyKGf6t+ho2DXCUIq40iSwudrYLVDiEGosHNCTiPsUSsgJf+EmSqnjf1tqrFbULbvjO2lwawku55InlmNXOyMkr5HLVPWeO7gGTFOjlMucBXU2BELIYBgNjbszmbLUDHKw3DJBEIV55Rtw0PU8VghzKS40Ydx7vs/v8dWkchtP9sXI/KhzKmZkWzKDbHHRRnJjXd/V1QPfo2hB/Vy+8T7IPnsQRksiiS9HX9Rzsbt1phG3rvgocYxCtaKxs1FfTyShRtMRommSqZHp3I8LRiSOCXoMVuf4XH2LcFKilyw7VgCvDnbMk9rcGOh5USFfrMCJbJN+yIfzbVoUaKrPxHjXvNTUyzQ0lj6KsHGVx7Fob6bqB06p0+ZzLM08XTE1IrHTaBPexetGZjz1oLKNkaIQiOMGHjCPpuVBzwYunf/DaauVRggD7lFTzifTyZcTHHuZZbDf7F6YCBEVoMipPBkIaNrygNw/nfm80qmQbEjJcwEpI0tr4Zn/1WP9Tbc0k+onNB9SrBirYXAofupVXg+KV0pRtWUJXFI42PpW4m05obWgZClKFIrpUrF/oEi8HYqazNgJy10VxlUe5M/g7nn0stB7MUFum0cPi3ro2Qkzwu3XjOZhdJDd3ryR1elkVmx/TuT/d8/etvNoYjWkCibWEDu9qLq/uSWxvnCvNYOy0gFHDpdlC5Jk9rgBPGX36f05dxYmgRXig18zHqXk1XHuhLv/Ew7ba
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

