apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAaeGT/XmD2RRNDJ8AI8PMnncU+Qy5m81oO1a8uQaq3tGdw/aIqw6msPG016l92Mof4v/qC7XjBDR8+HOmyyJ4IC9huppxwZpnWewMXOO27jwx+96CV2s9pUlyRskKvqB2t1uysDXUJj5uQmbeC2TWoN1U2F2TuRk1ATDIAECNtyOR9F9A5cOWda1agozzfAvxxih9UqPNze0t67YRpqwjPLT2pTtXwdzA/mtoDu0gSskBo2l0YzFmnI5z0320wbUKUSMvNLK3i4kjSDq0u9JLhZD/haU06abqzNG9zGn0JKBmFtsuacxxsJVMy1dvSH8H+8mfprcOdqQWrGqcYoFSdLjvaf6k13n9HIP0D9LqYElNOl1rwRAugKfnspPVUeT6Bw2yKwdAhG0rzWoRWsCFLCVEj7jV+czrT6rWfqsef3b13FaapoNMX9ZIa4uQXBED+cQGUorTTXeBYVwZBYgbx3/GFG/0XJAxguPpVq2YHH7JFiQl1si27PwNjIirpJbeFaivrTwOlHoQH4FlLD3bv8WINjYwMXUxh6STSKmXxNQ45m8AfgQYFpnVWuodJCazbVPqKTEgHDzPgmqBHbXSdA3pRjcfzTJUOHtbl9LNoQ65JWKP9MfDsFSnjz4MpysEtTyHa4o6mPoJ5+bi5XOI+mNtf4QZwS4q0yYhJWWSA/8PS6SzG1GlduFTEKLZ9UzFdAcondo+fgP2lv2cnay0ak7Jh7vtaw2JAtIwuLuTesou2OJNDb6woXCpZPaJ3LMJQCcdiAFVWx/cjb0WJW4p8xqOPsejjMqcVQ4VdAarGCoUZWkJCxd/g0m73JFwsGf5xx0sNFKf1ll5reCpnASqbqlXRGmJx2GbnO2oClWW5sv8+TXGeJKpgF1JzA3m2R7aBNgSOgAKGdqBz6uXIpai6VRTiFgMk
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

