apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCsOoJJRhgIgT8sjIujClryHYh6XyooFvbNsw3pHGKCSqziF3VdIBTDPwRy0z9vxOUmf666Qoz2VBPfbxbPtEZCPf87UntVidFDDFLoTs/t26a6uG3UNg/eoAZPe/W2HU//X6Wckcds1bo0Or0C4y6tWZPQKA0votqS2kKEdFnwSjP3rNJqRpEY4zh6CGzCnJ2lL+7kThvgjWFVP35qjrlD+LgGsyY6ZCfk8+tIpZFIpqB7i+0E9VoyGW2boQfs6tpQJ8JAxiIPcoLRiNGLyVtwgPmx6mK9heRXfeHrvfTl4Eb4URwwuHgFqQkrtdfUaE2/kxBx5f4WmSkwKirqjq+SpZ9KYrfLT5ppkgBjv6F+A/dqut/RV9o8gLPNSHY+qgm12bkN3TjE3XnJHxrBIXTCOrYStRSxqP0JukaIni4iQobaSslkDvjUy3CjtPZ+mEYejDpoyYaqECr+pPbCrkCxwFFfevvInon8vlRREJgcCl9019QqzkxMjy3N05oOSX1q7PAO5TUC3cvEZYHVbq7CQD0PO98TMY18MZJeuBMpshUpw9ZxZ36ZzvT92JO4pVk8uVc4G4bXlScEtafIc7H1QW4sCXfXMhoH6xtzy86OyVoABliNW5K2jJZaq7eknvOSCl75o6+1/2M8vCm4fnDQQFlA5As+W6WSnS6UOcdBnoDkGiz1qv4pEFe4Llhurruvvi01LBT94LANTxwC7IJsE4cwFW6TKGrop0MyrGPceNXDSfkRLDTdfjgZWotib7hc849kmQ8VX01QvoXWiWMv0uswVJBeLU36rBTNpNxttIMNrGuN4YNYLAr9x4pCgT73rDLU2hPGQdlZN2TgsM7F+cNFyD7ut7F8rRmjcCgQppXYAJk+0Rb2WGc2Z9ZY+Auk8Q10UUsLUifKLoTu8LGdYPF4bnM3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

