apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA86xTno2+Z0Zg3Vv8AxYWQN7zf+xZXWOTDNQx5WlKHu8LUOKJc9+KUK6bkpUO6ZPAg0zdjYJ9E3q+nC7IwhR8KQUTk2GrVkh8nKNx/XhwLritAVPrQE8o5Y4/L3eBu6N1Dm7GDgssKq0JRLNFyPfWtahMosM5cWZAczPstLyMp9VcZ2yBjreiFTJkx9tPvwU9W24zwN+yiFv7SnAT1YQKIaxguw4ZLtnuyC6+ed3vKx5wZwJ7fi2Hl50Nf6bC5djvXwE3hCgA9fMgmpGnXHvC+5uKoYfsWukGQNUpJpbF8HxRShOi8lptXazWz2wqntLwY/+7zSSwJa334Ti4Naz8mh2c40Ijh/NMrm68mH+gKF++tiQNAO9GLHwqZw6yNXXCBdxxx+++XxttiEKFx5mBYqkuOPVUJVjuDeihnz0jbGYV39Mz4Jy9a+i88sRoL9Ip4NxAcNiMa17MgZVvZtJUeujXtXHGqukXdGpQST+iOEFK+aKOffRnmKtCR81AXtY4fV/w+xQj0oBVRQlvN8W3fVRyrLIzQK0vcRLys/ptCJ3aoAygM1l3tevB/FyMCJwsMd4/wJTVx7DT/EEmDNV8QsE8lbi5rzVfGdEw8JVuMEZbEM9xrnr1ceR23HpNc35Hr/SO2MfOW6EWlxEqHmZWsn+B5AlesVU50ODpYHXiCy2wPmvgxsP055n8gpPgl3UUk5fYY5HAYaMIRxoqI55uN2G4tPrehxKuCXjCNcweyR1AaisPOUb4o7r0NDpjpMFXzHYxFbyOosLTqc4jDXymapYu6C+S6xD9ss6fXAaPxuaMDQcBCIZKAHPqo0m8VTN49vdAyJwHHlU1EHwRX0fttf86G/yPdj97hwIOyMFPqWrcVxjlVmU4moJdHB18Ldb/C0r9WaQnU8nvmqpgxT8MoTLS3T8ZE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

