apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgDAE+Hu5nVyZOUDNeww470LAgjLwjNhZKFzxK2+t3lPnyXBqo8zc1C1sGt78Jl2bNAnPVi+3Fk/vyvP7TX7woOis4E5JRsAgXn3NzL8h/g4REOoF2zt4iSKVhdUug3c0XIDwMP5Us4Mi9Q5l2sjBlo5zkFIGMFRos4YYPt2qkmQ1YLGxjBTSI5nhSuOUlED/UpsXxLluyDe62g+ip1oGeOtPE25bD5K4SUerxR2oWkB3x58+gkQ3RWEA1wpnEmWMXzxo2HP9gfaSgRn//NN+pVeh3bSmJHgifoImpGaSmjCz2a/YM8Ae+nwESI/PLIzYVEqslQoikPoPGwl40x5fhsHRpR8UrSoftmw3EbsHpKMxjKnGcxRhDBt7/8DL5WEnR5h61wr+nPijauV76hk34EqpjFwy3yFukN+MCyyCpnwG9K9CRtKtMBmaAyih3Vsz3Yb8sOLCpmCdNVNLLZQYm2spm9xnYZpxWQa8z0eX80G9TZhrZYLelPOyc9R+ZGFu7QcUVaZ+Tq1L8FtWaDHu15s//pKX6NZeyUtVdHciVBNpaPSXQZ3bJkYV7snL6Mr2wSOopeczvr1Pdjw4XVT7HtIFGVqca/dm/ZOSZdXMRGLV/uudXfEySRI2d0+UBev/DB2qhwdB4QDfuNlFfXhz260r3NfdifpRU4SOwAstJURSnpf+2CKLkKmHxdt/A6XI6JomuTNX0S5UE0LBBhuNFz6v41YyW6j7hJ1MOB4t1ydPAfYWBQqRoXoe+95fO6X0jPWrcNrUdXvsoSb1weWFU7v2sWrabjCVfxP4DM4EvtG/mX0OlzT3oZ8RaEogJqQLLkRi/Tv5oAoHEDEgUKSAMT6jsh8fkLkNDIAkPt1DGZgoZxkG/2L4l2eDWrEhuDTg554NQUWjNrVC3KLnGO3qXui7hgCYdT7
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

