apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgDLHL1r2ApFtrEG8d/tq+AmVB4cwZJ8RtKIA61ynBmAOrIboTdXONbLqalWnwRAKJU+r5gwb+h++GbL5uZbecdNLc4ttnYmyMMXDOV/UXIo4JIk5PUuWrOl38NyZuwotOTKWhS0c9s+yfi6HRzvyG1xmuJMDS0NV6FN4foMzYZSUHNOdQbWuA7vULP1lHLFql5geKrGROJXnlpKSFEFle/UaowaeDOVPg+XBFrSj3at0fCtEM5e8Kz0VSqsmorsm2TCXTM0X3SQBQluWUY0sADfe3c7vhPJFYwJeStr0+XIMYNEu6jjngqH5vDsDb2/RbNPHuxR8sYZJfomU76mQzMwHjFIaERvjHTNagbRkkAKeItKtI1OUNfq1mxUzXcKhsMkrXGwCHws8mz+rSIMExn8PDhEm8Ii3sIQfQMmDJxvBXm7Z6XsPxkHikxtqW1jf1aIulRVx8C12rJWcSF7HeCyQAA+VTfVRLvPmYJ0t6Wp+yk9JwKi66BqdHsDFayS6809adKVcVK+OeaGVEkDxBe2scFDyvMatjdZzpQJ3XuFO/96xD9lqg+mBlAd2Gs+z3b0zGxMO8o+CSphGUvPqAWyPGkTnQp9aiFk24YE6mbRjPcdwRz1Q6VtWPkPu3Z9DoY9guN0RbSNHmhqXTQUDfD+7M2Mv2x+CILxw6lVOTjr3mKL9WS3MqZ3dAuEN5IyWErZF82cqmriAjcmZ2KWrMAhnWxa4LOwepYiCxOibjfMvr3F51i+2QKPwK0baasCDz5V4HPWeM9rrDRdb2xgbIBihMw6Ed1evssppPebdWN+wXAGhHeZUOkG5o2a2XuMU9Cd81lnfGnTwawwJKJcjlQnDg6qq9tTm3rbnfnLx1sA+cI1A0K5fylVQifINMCSjkdXSpchQ/wa6U8fN1+sAkVi6BkZW9xw
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

