apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCl77fUZKkGg1LTwXq7/ywgqrBYzmTtq6ocFxsQ1ELVDu+6xXEpVQstQXlm0X/zL06DH+WH7lLu10ysFkUJgVIu45h+Wx823JnDvjh+kKGOIAi7/LhnGSQetilVRJkjMvVnUU8uS9Ju5mUT2BGGu1OOeMa4A5L3YNPdUmE03zg+3DmjW34ZUH/Dcmz8AGYwb7GEd7JeI27TRrJHgiQmPJhutveSI9zJyrcxyOg/W0cZaugK/0c203aoZMyrE8fmKVT8LbZMvllgRBfgh1cx6fz/sdilMPNlrGZ1RUY28u5+zmR+xvs9b5nmS0BCytOJjcGTBIHRQGBGgkUlV7uQ3K7SWGjyZsX6NSxgKYNkkvIXwVHAMtfnjjKvFqOvvstF4KozRrpT09pk0+X+0Ui1YxjmxjZLClaW2/QY2t/FjF14XqHFUT8D42KMrXKN16bkiiDWLAfP7CVO7HaySmsD2APA5Ueo3zlFdYVbGHF9aORyULf68GXkD3q6VMqqVnOUqBwBJ7mFwI6C0rrt+Ov4Br1E1BkviMtc0eolBrANMXchDC+FMOyt2Nrq+htV7rMgcaXSbqckJijPEUuF3dipnXCVUseaqla7loElSL66PzBHxnud1eT+wGjklMFGCTyYbjgfTN7NXyKXFkelra33Qb/DJzZWWS58uMY0VWa+VXUu/Vg7X9FB46D67UJlm+ZcwbH4EgQV00rujY2BmFLUCaDEUfu/e5Pz8yn1a4ZApAbMKX/oRwmsOmxhwsVVktVBAtAKrqzHFkxOu6tYq2OrWW55nH0KzhreBFP3VRD1ekac7freO22kRY2Kx9C8xmnI1UdgkGXFR2tbQNP1Zj1EJTB2zwjlCWXLFXTi0mJBBAIpXGIFpha8l7MLtrt/SrcuedaSHOqZNxbvFvl1XdgQa2kWRx6qqKbd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

