apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgAGOr4MWK8+RNsRzXc/LZzn64UbuMASftGck9+5i5fBKoFNJlEqH9wSnJCn5qOaZvg0lnMt164ebuhja3IDb7dDVeOpO8lm9Q608K6N5LhFY1qb8CspqvpvTcHraV3EPSJcDRBlMkHHlQhwK1GsU0EtmfBgFF7bC8JTwFLwOLKsKHJuUYW8lJjA/xHm6844Nrk+f9uu439ynjGMYkfA518aIRn+/ZirDGgA+9MaHtjRPXjVQrGwrjYcCM4yykL5Jha3SDQWB0Kdy5nW7o7Bj6/OkJfvWdFqLobcgqztEggn1v/ZcyXF3V6YOtaXT1E/AO0PVB98nMzvMAS7i0ytz2faEmp3GDV8OtCnmmePjz4u8jHF3jloFp7tR+0XHtpuzkFZLluCa2wMRH5sX3wXT+nJWKI1JzeSBsLLEO8xk4AuAvqvZSzTMcQOBHbWhLyfFB6HTkUUxKp1a/qFt0508u1WtbBxivMSfclWtv3SI2rcn+CGktOwQ24uWNBV5il/GV5HkvEspkJU1Fl4RcnQlaTCaxT/AwLl5XfnGt0VGxAzIxs49Bmd6LWpY9t5YE2wg8PpGRa+5NZUQu2xa1Vruehm84zvdiIxvbpp7YsT38zsArtZthiM6sXRxR7b3m69BYA/QPlTuN/db/2aoZvBj/S34iX6CFeQLKwv6uBTwG1q2bpg9v7kU5PVEzNq8gCdnnqN/caJuurJlEPj0b/64xrwwQyntNpeado/3TUjOA+0AFlSfNPNBcGCcfy9mcgjo3CJz+vYiwOEip5BQa/uOv3Kgxzd7mXtA5i4hx5nmnXKhTQhD2gs/5Qi8VGCL0Dj6VsWHddiwW6vqK8/SMNJ+8/UEJ8WaI3/VUiJO8UY/o+lkc5th6FFkui1IBKbTfz3oitrxJSZL6ZZbjZw/+heAVCV/MDyZrCp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

