apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBEcwlk/LnfKFs/NNFaui4A+gb3tOkq5fDAPttI8pKAfk5MsccpkVVuoytHIaTWoh/RHc3gYS5o+RiVLR/kMP2cSZ0KQ1K5M/rJ0wUJiZiNFOpTDdA5s6yBDI1W0ek3Ip7BwzuwAQvowPiwmW7jGowMc678KPKT0i6IGSUjZF2Z8CFNXXIGFpMCAxO6pZA7Ta7mg6fexIXfkar6/TZfXGpOOMWCyVmjlxt8Lzo1aW9JSXZpfNLHcwEQKZRQwWY3YhsGnVRjhPN+R8MzzFiewq1Aq54hTnt6apFV+r2W3oqc16g65xXJBHwijl/A5VAMq9FZynmECTnp3iJlWnzJhAzTLWLot5oiSh3ew7fWRM5LQBa1Ug0ts/YbwTgvQ3zTqo9s1XE45LNQhvURyweD9ShRY5n1WAy0BxSITwPDPAz1vl6EzNBm8DU1e4nSOLNDLNpPTnwB618dfJTESMcAQBav23HxAeOSjWs4YmvQLXXvjlmbgnQkEt43VdEiLg0A0WIqkOsOEn2Mi8jzqHgvm35D6XPZuL7lWer1F/U6gQ+44i5aEj2HeQxfWN/V+4AObvNk8T0poTLsGQLaDs9vlh5LkImNwJfjnPMCBSPUXeiLhXRR6vA5GlCnW4+1BBDxHMnMvB02OvxOxgYzVUubDb3BVF/BHhFysxt+ZEPXrn2NJFkZsP8ZRLKay2tD4cqzZS535m0p6XwxkuVl0zzX7b5jmJnZGO6+I6V4dJUckDDigasxSNmEix056BSfTwobyIB4yXQgyb8S+mlpNe2JNXfKi57+nGFbIrXFSKPEvz2h94OtmHvzgn6GjCSxfMvY7i2Vdc+l/qhcCHqaxgdnt/UIQ6BlqoHHWIHW4T0naFYPFW3hYZsjvvkDWme2UJIdctJAUtdyvDzEEAPfc25NB7aeZ+3sA13b
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

