apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA++PdPuGbmCECJmfuQ8qeKBPG23204Tw8N+jczbvrAd6fquPYHrPubUWuGuTyvt7qRFiDxtJyIbv/QnpEBDxuvQuxa/606dH9EsoVfAIqYwuXy8q9HPuEgVMR1k2vB1fhlQaT7BqdyriURC9DtL5du7J6SuCM41CIQlDBSbWK7YHNOm05mitAQU+wcEKRF+7Ha7IBofj32ejqSAsWh3r8n1w5ehihn7sHQrgnjfa5nCaeQqlnIrMyG/Kts0sLvZPhQ95tdOnegQqiy1aEMiyT9xIOU2keioZK5l5Z4FNFKoe2hPH3Q9jTuk8gIxyLM2HFrMckpgzCiT9gN919KmVY2HktIv+Bd08Ff0Q+JUA5wSYyAbIlnC/ymKPfWPleSUkE+RtrcmlntncULAU/JUE7ntIFso600kbaUfccg7iVAitX/k9ENoQun6eGmyYvynKKXHUBX2FrH5SAoXHRZgqv//nhyt5xfDJCpCD5QtTuUfmLyX9E+POrHoZop/u0ZaWgcKc6pDngIj21hqzSvvgrgkGe1wjEjiOiqXw85+LDfIkPgXzi0Wy6gMChFzsvHbgY/8RKUMcLQjp5aSB+YkgCNS4s66GVrNYSftySsAFSfm625pvPIfKXy+tODYMoDRGwNkUUdz/f0wtceLWTqGljmKfdS01WlvwLHl1MWv/b2QZQjV4B4dGvB0qujVOXxP5ZYC54bVvAFl+kbIZKnDWyfOzr00fl5vJKqLpHl2BUCQLo6RsGWN2S7lUJzogq0R20miJhxYt9Z8Au6cc4f7Dtz6FjzZFB97QhtXU+avwNUIHfUvS/VVIgqgNWBGGdwdRm8CfvmsuDOeyOn35hj1RzoxBe7OQ3/BY+fhw0uLJbfqWALEdn6TyIy2b+dg4LpUvZpIZMTJnJcJbYLBBOVZPMBLZowq3gg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

