apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgBsQOVPs6MG5aVvJoN4ca1krXmrABxUinbheczEqScbdmntK4ydIKkQj7x8r2Dz6PE0jxFEtjixsi3OtwJ1JHG+j6s4nOgK9E/A46FuCGpaAPyIbn9VotyA7u32/xGm49mWLwAqHHnR/JgXn6KOLO+K3YmHMViJqqq8nOi6fuMhU+eKmtbFYam+SxdwxFrVKU//eY1KjqcFNl0RHf3alycWR1GIepgg8IwmaGnJkDaMa7Ykva3Lk1gZisnH+QyraWpCfiA8k+XPDcv3sOhsQaOlg3+Wo5iu6SeOFwxDqJuTyJk5JtFoYgYvEMhMrG3LG8GLBmQmabkJ3bA6NCqCKShzxUXBX1p8nzLuqbxoa+T9bQiRxhluv8MkgEjtPJ2RY0DKbr6jegFdZxbqhpYz8EmrtF2dGxTDzNcGEVQc/2mqaCjuyRtawiW8bEtLvbPh1t825+PGpVJeIrh4d5nwGCIQO1nxEveJvwuzmIbCIgTNSlGjDIdmBx1sL/1uOzxoqHyRekLgEtqAhUjq0ZDtG1hoqZTyMZ4xmSukj6sP53E30AyBIqnOiSf5EtqmNLl1A0DW3W7qCshkntOcZkhRNuraqG/or9IjuBmf/zhDW7gORLQ5gQeNv216bOu2jER3KfwoZrlho9yeULxAuh48An3eB+RJM03hPFnyVpgxPJvoRJj/KxxkwKiz5sCH8Ud6W8BFBttEP/dhsi5/qSQolpeGy/CmtZzLsyYm5RA3pBMHyCztJlAtQhv6etFJVZZiPyNhy5zAK3LWhqbZVEsj0mMkeKhxzr+x+OYZdrfClGrg3vMBXIhydcntrMF4exfi84IpoJqlCJ0caigkorPAYkUuI60PkA8+E2lvTkc51Uo8uUs94nDko7fJN4wEXexFWWRfivpC+I2jHZ2n0jNCXGQEaZbUbbAz
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

