apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA8LBRzcxa8HJmOhnohQ02ETiU89GEWn9NdKuVYZfwLoAJmp7hHmnEV58VpOkPe/vpQteijTb/nYddW0j2TUnr69V4QjFa7qWmxwrt6Tgd4Qqaakb/6Jy/FkaDi6ZVA2aQlPfEy8Q+nenar4KFsAEvVTQmF03vVRsML8XeXyQ4mvl+oNCHsoAiMNncjeQE5Ehefmp6H6fIAu8hm66tOg1Nr5aYwXXT/2tlkir1r82c9/wIkl3NqCPuZYZQK5Hs10E4GNYJ6yUA9PRm0PA2SUiNaDiAmYB7MIwa4t+dQyhEXDQmvuY86ymI5fuHNBs0mGjXN7qqbIW1B5lAmtwdTa+BoE2m414o5I0pmiHmLfz1HjUrAM2x0daFRUoueF8tJE9921MSIhibqGOMTbeXiVlmTexBt8kIJuc6qwcgrPqTE3TOrciumJ5N5j03fxbay8x37ABpzP/qoiJM1UjBjyqixSuZNuRM+LyjDdRg4nXYR4oy1sxe7fowyprihBx5k47k+Ehhy3Fx6sXH/iXVmpl/czwfPBTnzyKy3M3mTA81C0V6GG9FiIbg4yMt8G2X1UljaCVJiSzRJw9+KgH1DdakjnFN571mxBoOL5F9liyoO+G33Gepghl61EFAQe3bF+Ky6A8Z44ohqN2WSpH5AmC5ffzbt0Th0O3BlEKzEFECRfhdj4hU1S/1nh1PHp20EH+cAj/s8rBfvUkoI+i8jNwi4BfPObbF+d+oNXhOEaXLy7I/nzUI3foeg9PjTcMTuLor2pAvbubIQxP68C7w88lxH/Q2yPDsque7odvcHrl/JkRFDXEFa7w0LzheykWW1TqADgsXb23onwMF3JCNRo/qQc2Ga5X/gNButu2TgzSq7849fYMVufpUK/7v73GGhRkomG25144v3CHGiOevQaCXjcr8k3dfi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

