apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCPno8os9cyK8Gso5Tf22/p5WwgCcdu4s9QDRsMy3OlhFgSqoYlFdc0vvp6sGhfAXVs0LlOY2dlVO02SbdsPewFy4RgSfgTDaiTO6HlMwhHIJqR+b9t+RxceOo6wumVyt5gF5A5WRLoURZQvDFy+je6RCg4icJILz1m5k3Dvdr5ZxuJlg1VSejvm1JdRtIWjvOncGLocR8JjMXaV/Tk5BRoANNL/jWCoqW25gJni+tfOJKjxdxRCCe/GsCdgMuG1ZCVIxpIT1nvKB9e0OyFdFIF11ODVzhGQlSP2z9oku6vCUJWI1mZurNtqhOEYFh9QNyt0q5UZGp22RfX4WKzY2BKfTVAEEc1L8emIwDlJLCfwpM3mxLaaqEZ9CZ8ajEuq7GTIFx7ajpWuJqqSh8sqvHOjfURiwh4/HdBYJLHewQM4Qmb2iDAYltQ2BhQnckA+kIeARNRic2tSuXR3AjPvkTkkAPYfh1r9sQa84ERoJOeVGgYvp7OldL0duiLj1MX+jpKAF7qaoN/188qv5bgi3pfXXbhop1/yLSF3VI+u393SplJ3SP/SPvEefr2GvkOhvYz7rC3l66YW4oR1WZDtsfBh6sjDwuSVIQdig0DGSXuZEyyu5j38Y2G4c7pgwsr6N5dYwmvABAexrE7vm5t5Au4fqgdy3G/VFn4/3wLma6dxdBFwjf5YAyef8bxlNwsA36KdjNY59KSXDGpI2c/VwfDpUIMUkGiYougyKwNKetCgsJ2STmnxdOozyaMb/fYzJnIBCIrOLXRPKsZo7bc6ojOU2J1yvulxHFhrqmXerlOa4mYqHaIc3f1BzuUYzfceoc1DMSSzB+dl9vaCsMZnAAWSpyfjkyhVyuAV0lZYFfA1CJd9i47fZSipfEyOMVxhIdLfIJdWvs4oaZvtyado3ScEyCGuAW1
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

