apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage-system
spec:
  encryptedData:
    .dockerconfigjson: AgBkhTzRNwm+KaVII1ycBhMh916s2Hhxg1YKSJKXEmS3RO2TOBhhKdP0x0oT8Nsy4mxfSbJAMdZMyji6L83ki+3FnHSxJw9Da6zFLKLKdvUiImXIPdi2sAx/0WM1AR6TBCRPY6eWHLgZ5c/d6eCl1gc2bw8zpyik/bGp/SONdewvorQ+d74Ur1tVCnSlD3PLWjd3ky0MSWC3WZgbHGXlTNqhBcNZuKgQ+CCAKl9vc5YuO12XKx0iFTFvC4D9zrcZfdfeRRXLTUHH2hbEY+b7n2LWRprwNHIKJIGhYEJp1slre8/egYbzuUoJ7lyZyQJLxeS7FSjTUgCmsJyoEDx6MxmHaC69woMrqStpD7m/Qkf2WaNSL7WgJQNpKxWT03tSSlqkee+rdb8bmFOOQv+UxjLoiO/SH6Hp7TWp5+rhrMv/PzOfHReWS9TFPDUmX2lUFju2Js1oPdce8jMLx0x+f7mWXMpZYcQkg6SDJbO+bWuuCaHQqPebWznsP8bgV9O9tmsTB+VkrIJbqChnTArOaMTYQlZYtjLQAukRtBTQJmq70ShsatHWb18Tokhi1BlPxN6t/Iw6cWtWVOpzorZvkcLQ4TMLTPqVBHYj+CeYuH3s6paqZA/qrfoRaLrtSXJB4g6M/87E9zaTLIKix22FdcOH9ot4sfcrnRwt1AFvwTU7U7ZIEa94Khyh+N+lKq4qKc6aVoW6TVZCQfVHaeK5cAeh/0rR79Rchm+JrkNt3xMTa9QhmtDM+NqKPO9hVlbvulv3CrCXPb8XZvaWV6e3ip6MUmIKDzHBOMAZ3AplaIJjnMl1xGuG8BMRHYIZCDNLhRFgH9091Lcixe7OHRWmnI81GOnDGewsACzzWLKhuSimiSxMzGrCktaPdztf0IWa90xj+HZUWCm+nb+fM6pMIwp9PfGcOs8B
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage-system
    type: kubernetes.io/dockerconfigjson

