apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgCNDrf59ufcBivRCjhTEJaB7TYlKsADx6denL4tUdG08dvW1tZ+WUqM11rpQjfOXXAS0U07RTkUbznFIyI0VMqQy6BEhkiJx0Hzhf8rvR986zRVeET37leuur0I4NyRjl525k+OsY3i7IJ4od+s58+TEPZeP4Q+lROcG9wzEJvvZ1mLCcQePqPvlfx3fLRTsghXnCNxzZVjqPEWlOYKTnQzVAtax2Fwu08fHucZcG0IJDJY4VSTdVIrv2fzUWLxg0H06028CFwjp6dj3E8OIJQCNuXcHdn9nl5f5XwHyzbivBEtDdj3zGAtoJfrG1owN10MU8o3KzwKlWFqvM7pRCPoGo9/KFPYgNcazGZ638WrkSlO+apaYDgxDaZVKJ/Jkwk1gbgHCKoO6J6UExW7m2jKR4w3PKtXRRNIvlb3edgRsDiA6W/pnWpAhh3k/oRbz/5qJSLlFw1/s91kPCy6jfBWO+cD+xYTHKi8DXR2MzHPQem5f3IdIRz0hGqFIYYzdZNTxtPC19cSbk36Voa0JLaK9ZeVytYJBCNwHjdgDdRee/YA34XeTbbxk/HSBn6dKVHpB8h9PP/4fYWDtEx/X0YaOuHNTRT6dgRMKhrxtJIg5pzjKrxMVxh/bz8++NfrqH2kV8yv00TeMI9g0OLkKXLX5Ey9Mi+LiYQVH4UhoM0AeHe2a9wBLnsnZDJESU+Xgg81nMuUwcvnquj7SseWaxO8Jpxxq6pRn3oEwE8pMB8QwRKriX+xF6kPs/QDWa6QKobc1tKZjaNV7XejpOvZAy5f1YYzNST5sdN3AX4QGwrZgpMWa3FewWZmlgX2+7L20dG96mRavx6DEOgGwjaDyJJmZ19p+fdSDVO50mZaVnzaEXkh8tOufyAXgSpkTysjZq/xbYUf8Yu25Zod4Xh4HLwlXbIgosUF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

