apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
spec:
  encryptedData:
    .dockerconfigjson: AgA2Wy6JfadVHlW0b7kkj8vZDfVIaLmsJmwmw4UWLu6gQ9uiLuGMjpDXzoKoKZRoGZby+lfOZ76fniakPhnFXVh76YQbd0XVwpWYJFsPes9Gv+BPU7c/iwBzz35ZWsiGx15VEBMnX05o9YNH5aqMqaNTDHw62aOim9mhIL49eiBkGvoC8fg5dyEfIRXEwpAx7hYzD5EWZCJci280DlLRi5BDGd0tA7oVjYKGAOIIuyneYyz3fpTQ7Xp/vPF9O2mGd2is7N8xOYTNrgS2LzHzbP7UC2l4PJrTYevADwUvtfwKG2JbEzqbaFH9aFP/qHIKXmGFaRfq1j1SQsASra3+QUhWRPldZEmCqz6wfKYApv+EUjNhrmHwVzPI4MV1ocecwKZXEnXDz0HGOylS3GCFnwBSueQQUaTGG6nLqNqLW2L9vcl96VgvEHWnT4D11fwG6Cyf0ctl0o4/cxxaQcPGTFhQpU6jLWQ2LNajubu6+/ZSgvLVJ+Z328RRcpRvpfTcjJLvxjxR2Zweh6eVdZo8sCn9xoFz9xaTMk0KxWuCauVhClJxG1YcIqZNUThAmLTeKtfiTMaaAVrHgLjNEHqXAHA5zbBwx5o+0Il0mo898oQ1BM+fxrQZRPqr0cX0fcZVHCzbaM8ickX7Q2rJi8d3mFFr+X6CkqzrqihssPhDcoSXflHNSH2A2Xf7RtjpOi4SjOobI2R5yRizDISaFz7ThAE8ixs7VdORbmRL8XRdKVQh9ZnFKkoI0p9r0xIFrv5kRGz6YbLsJlYd2/iUvQnlFcbckwgqgkaIb2PPkWwzYhFM44ZhRzjt1XZNnznUQDV/Omxw4w88tmC00VRqxCJHM82BeOGBikTSa3nPbGKVEnRAKcBIXeyUTKmr8sUDUOQT31nHbJUe3BVCkktMYzeWsIcnJ9fjxKDW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: storage
    type: kubernetes.io/dockerconfigjson

