apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbHZhcm9nZzc3NyIsInBhc3N3b3JkIjoiM2E1ZDc3MDRkNzJhZWI5NjkxZTMyNTI2MDcyYWM1ZWEiLCJlbWFpbCI6ImFsdmFyby5nYWxsZWdvNzc3QGdtYWlsLmNvbSIsImF1dGgiOiJZV3gyWVhKdloyYzNOemM2TTJFMVpEYzNNRFJrTnpKaFpXSTVOamt4WlRNeU5USTJNRGN5WVdNMVpXRT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: storage
type: kubernetes.io/dockerconfigjson
